import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:image/image.dart' as img;
import 'package:image_picker/image_picker.dart';
import 'package:nsfw_detector_flutter/nsfw_detector_flutter.dart';
import 'package:turqappv2/Core/app_snackbar.dart';
import 'package:turqappv2/Core/Repositories/booklet_repository.dart';
import 'package:turqappv2/Core/Services/app_image_picker_service.dart';
import 'package:turqappv2/Core/Services/webp_upload_service.dart';
import 'package:turqappv2/Models/Education/booklet_model.dart';
import 'package:turqappv2/Modules/Education/AnswerKey/CreateBook/create_book.dart';
import 'package:turqappv2/Services/current_user_service.dart';

part 'create_book_controller_base_part.dart';
part 'create_book_controller_class_part.dart';
part 'create_book_controller_answer_key_class_part.dart';
part 'create_book_controller_answer_key_fields_part.dart';
part 'create_book_controller_form_part.dart';
part 'create_book_controller_submission_part.dart';
part 'create_book_controller_answer_key_part.dart';
part 'create_book_controller_facade_part.dart';
part 'create_book_controller_fields_part.dart';
part 'create_book_controller_support_part.dart';
