const String _defaultProfileImageUrl =
    'https://firebasestorage.googleapis.com/v0/b/turqappteknoloji.firebasestorage.app/o/profileImage.png?alt=media&token=4e8e9d1f-658b-4c34-b8da-79cfe09acef2';

Map<String, dynamic> buildInitialUserDocument({
  required String uid,
  required String firstName,
  required String lastName,
  required String nickname,
  required String email,
  required String phoneNumber,
  required String password,
}) {
  final nowMs = DateTime.now().millisecondsSinceEpoch;
  final createdDate = '$nowMs';
  final normalizedNickname = nickname.trim();
  final username = normalizedNickname.toLowerCase();
  final normalizedEmail = email.trim().toLowerCase();
  final normalizedPhone = phoneNumber.trim();
  final normalizedFirstName = firstName.trim();
  final normalizedLastName = lastName.trim();

  const antPoint = 100;
  const counterFollowers = 0;
  const counterFollowings = 0;
  const counterPosts = 0;
  const counterLikes = 0;
  const dailyDurations = 0;
  const viewSelection = 1;

  final preferences = <String, dynamic>{
    'aramaIzin': false,
    'bildirim': false,
    'favoriMuzikler': <String>[],
    'ilgialanlari': <String>[],
    'kolayAdresSelection': '',
    'lastSearchList': <String>[],
    'mailIzin': false,
    'readStories': <String>[],
    'readStoriesTimes': <String, int>{},
    'rehber': false,
    'settings': '',
    'themeSettings': '',
    'whatsappIzin': false,
  };

  final account = <String, dynamic>{
    'ban': false,
    'bot': false,
    'deletedAccount': false,
    'emailVerified': false,
    'fcmToken': '',
    'refCode': '',
    'accountStatus': 'active',
  };

  final education = <String, dynamic>{
    'bolum': '',
    'defAnaBaslik': 'YKS',
    'defDers': 'Türkçe',
    'defSinavTuru': 'TYT',
    'educationLevel': '',
    'fakulte': '',
    'lise': '',
    'ogrenciNo': '',
    'ogretimTipi': '',
    'okul': '',
    'okulIlce': '',
    'okulSehir': '',
    'ortaOkul': '',
    'ortalamaPuan': '',
    'ortalamaPuan1': '',
    'ortalamaPuan2': '',
    'osymPuanTuru': '',
    'osysPuan': '',
    'osysPuani1': '',
    'osysPuani2': '',
    'sinif': '',
    'universite': '',
    'yuzlukSistem': true,
  };

  final family = <String, dynamic>{
    'bursVerebilir': false,
    'engelliRaporu': '',
    'evMulkiyeti': '',
    'familyInfo': '',
    'fatherJob': '',
    'fatherLiving': '',
    'fatherName': '',
    'fatherPhone': '',
    'fatherSalary': '',
    'fatherSurname': '',
    'isDisabled': false,
    'motherJob': '',
    'motherLiving': '',
    'motherName': '',
    'motherPhone': '',
    'motherSalary': '',
    'motherSurname': '',
    'mulkiyet': '',
    'totalLiving': 0,
    'yurt': '',
  };

  final finance = <String, dynamic>{
    'bank': '',
    'iban': '',
    'mail': '',
    'tc': '',
  };

  final profile = <String, dynamic>{
    'adres': '',
    'bio': '',
    'calismaDurumu': '',
    'canliYayin': '',
    'cinsiyet': '',
    'city': '',
    'createdDate': createdDate,
    'displayName': normalizedNickname,
    'email': normalizedEmail,
    'firstName': normalizedFirstName,
    'gizliHesap': false,
    'hesapOnayi': false,
    'ikametIlce': '',
    'ikametSehir': '',
    'il': '',
    'ilce': '',
    'lastName': normalizedLastName,
    'locationSehir': '',
    'medeniHal': '',
    'meslekKategori': '',
    'nickname': normalizedNickname,
    'nufusIlce': '',
    'nufusSehir': '',
    'nufusaKayitliOlduguYer': '',
    'pfImage': _defaultProfileImageUrl,
    'avatarUrl': _defaultProfileImageUrl,
    'photoURL': _defaultProfileImageUrl,
    'profileImageUrl': _defaultProfileImageUrl,
    'phoneNumber': normalizedPhone,
    'rozet': '',
    'signInMethod': 'Email',
    'town': '',
    'ulke': '',
    'userID': uid,
    'username': username,
    'dogumTarihi': '',
  };

  final stats = <String, dynamic>{
    'antPoint': antPoint,
    'counterOfFollowers': counterFollowers,
    'counterOfFollowings': counterFollowings,
    'counterOfLikes': counterLikes,
    'counterOfPosts': counterPosts,
    'dailyDurations': dailyDurations,
    'followerCount': counterFollowers,
    'followingCount': counterFollowings,
    'gonderSayisi': counterPosts,
    'postCount': counterPosts,
    'takipEdilenSayisi': counterFollowings,
    'takipciSayisi': counterFollowers,
    'viewSelection': viewSelection,
  };

  return <String, dynamic>{
    // Canonical root fields used by app + functions
    'userID': uid,
    'displayName': normalizedNickname,
    'username': username,
    'nickname': normalizedNickname,
    'firstName': normalizedFirstName,
    'lastName': normalizedLastName,
    'email': normalizedEmail,
    'phoneNumber': normalizedPhone,
    'pfImage': _defaultProfileImageUrl,
    'avatarUrl': _defaultProfileImageUrl,
    'photoURL': _defaultProfileImageUrl,
    'profileImageUrl': _defaultProfileImageUrl,
    'fcmToken': '',
    'refCode': '',
    'signInMethod': 'Email',
    'createdDate': createdDate,
    'accountStatus': 'active',
    'emailVerified': false,
    'sifre': password,

    // Root compatibility fields (legacy reads/writes)
    'adres': '',
    'antPoint': antPoint,
    'aramaIzin': false,
    'ban': false,
    'bank': '',
    'bildirim': false,
    'bio': '',
    'blockedUsers': <String>[],
    'bolum': '',
    'bot': false,
    'bursVerebilir': false,
    'calismaDurumu': '',
    'canliYayin': '',
    'cinsiyet': '',
    'city': '',
    'counterOfFollowers': counterFollowers,
    'counterOfFollowings': counterFollowings,
    'counterOfLikes': counterLikes,
    'counterOfPosts': counterPosts,
    'dailyDurations': dailyDurations,
    'defAnaBaslik': 'YKS',
    'defDers': 'Türkçe',
    'defSinavTuru': 'TYT',
    'deletedAccount': false,
    'device': '',
    'deviceID': '',
    'deviceVersion': '',
    'dogumTarihi': '',
    'educationLevel': '',
    'engelliRaporu': '',
    'evMulkiyeti': '',
    'fakulte': '',
    'familyInfo': '',
    'fatherJob': '',
    'fatherLiving': '',
    'fatherName': '',
    'fatherPhone': '',
    'fatherSalary': '',
    'fatherSurname': '',
    'favoriMuzikler': <String>[],
    'followerCount': counterFollowers,
    'followingCount': counterFollowings,
    'gizliHesap': false,
    'gonderSayisi': counterPosts,
    'hesapOnayi': false,
    'iban': '',
    'ikametIlce': '',
    'ikametSehir': '',
    'il': '',
    'ilce': '',
    'ilgialanlari': <String>[],
    'isDisabled': false,
    'kolayAdresSelection': '',
    'lastSearchList': <String>[],
    'lise': '',
    'locationSehir': '',
    'mail': '',
    'mailIzin': false,
    'medeniHal': '',
    'meslekKategori': '',
    'motherJob': '',
    'motherLiving': '',
    'motherName': '',
    'motherPhone': '',
    'motherSalary': '',
    'motherSurname': '',
    'mulkiyet': '',
    'nufusIlce': '',
    'nufusSehir': '',
    'nufusaKayitliOlduguYer': '',
    'ogrenciNo': '',
    'ogretimTipi': '',
    'okul': '',
    'okulIlce': '',
    'okulSehir': '',
    'ortaOkul': '',
    'ortalamaPuan': '',
    'ortalamaPuan1': '',
    'ortalamaPuan2': '',
    'osymPuanTuru': '',
    'osysPuan': '',
    'osysPuani1': '',
    'osysPuani2': '',
    'postCount': counterPosts,
    'readStories': <String>[],
    'readStoriesTimes': <String, int>{},
    'rehber': false,
    'rozet': '',
    'settings': '',
    'sinif': '',
    'takipEdilenSayisi': counterFollowings,
    'takipciSayisi': counterFollowers,
    'tc': '',
    'themeSettings': '',
    'token': '',
    'totalLiving': 0,
    'town': '',
    'ulke': '',
    'universite': '',
    'viewSelection': viewSelection,
    'whatsappIzin': false,
    'yurt': '',
    'yuzlukSistem': true,

    // Structured maps
    'account': account,
    'profile': profile,
    'family': family,
    'education': education,
    'finance': finance,
    'preferences': preferences,
    'stats': stats,
  };
}
