part of 'explore_controller.dart';

class _ExploreControllerState {
  final selection = 0.obs;
  final pageController = PageController(initialPage: 0);
  final searchController = TextEditingController();
  final searchFocus = FocusNode();
  final searchText = ''.obs;
  final searchedList = <OgrenciModel>[].obs;
  final recentSearchUsers = <OgrenciModel>[].obs;
  final searchedHashtags = <HashtagModel>[].obs;
  final searchedTags = <HashtagModel>[].obs;
  final showAllRecent = false.obs;
  final isKeyboardOpen = false.obs;
  final isSearchMode = false.obs;
  final scrollController = ScrollController();
  final trendingTags = <HashtagModel>[].obs;
  final exploreScroll = ScrollController();
  final explorePosts = <PostsModel>[].obs;
  DocumentSnapshot? lastExploreDoc;
  final exploreHasMore = true.obs;
  final exploreIsLoading = false.obs;
  final explorePreviewSuspended = false.obs;
  final explorePreviewFocusIndex = (-1).obs;
  final videoScroll = ScrollController();
  final exploreVideos = <PostsModel>[].obs;
  DocumentSnapshot? lastVideoDoc;
  final videoHasMore = true.obs;
  final videoIsLoading = false.obs;
  final photoScroll = ScrollController();
  final explorePhotos = <PostsModel>[].obs;
  DocumentSnapshot? lastPhotoDoc;
  final photoHasMore = true.obs;
  final photoIsLoading = false.obs;
  final floodsScroll = ScrollController();
  final exploreFloods = <PostsModel>[].obs;
  DocumentSnapshot? lastFloodsDoc;
  final floodsHasMore = true.obs;
  final floodsIsLoading = false.obs;
  final floodsVisibleIndex = (-1).obs;
  int? lastFloodVisibleIndex;
  String? pendingFloodDocId;
  final showScrollToTop = false.obs;
  final followingIDs = <String>{}.obs;
  int exploreEmptyScans = 0;
  int videoEmptyScans = 0;
  int photoEmptyScans = 0;
  int floodsEmptyScans = 0;
  Worker? currentUserWorker;
  Timer? searchDebounce;
  int searchRequestId = 0;
  String recentSearchReloadKey = '';
  Future<void>? startupPrepareFuture;
  bool startupShardHydrated = false;
  int? startupShardAgeMs;
}

extension ExploreControllerFieldsPart on ExploreController {
  RxInt get selection => _state.selection;
  PageController get pageController => _state.pageController;
  TextEditingController get searchController => _state.searchController;
  FocusNode get searchFocus => _state.searchFocus;
  RxString get searchText => _state.searchText;
  RxList<OgrenciModel> get searchedList => _state.searchedList;
  RxList<OgrenciModel> get recentSearchUsers => _state.recentSearchUsers;
  RxList<HashtagModel> get searchedHashtags => _state.searchedHashtags;
  RxList<HashtagModel> get searchedTags => _state.searchedTags;
  RxBool get showAllRecent => _state.showAllRecent;
  RxBool get isKeyboardOpen => _state.isKeyboardOpen;
  RxBool get isSearchMode => _state.isSearchMode;
  ScrollController get scrollController => _state.scrollController;
  RxList<HashtagModel> get trendingTags => _state.trendingTags;
  ScrollController get exploreScroll => _state.exploreScroll;
  RxList<PostsModel> get explorePosts => _state.explorePosts;
  DocumentSnapshot? get lastExploreDoc => _state.lastExploreDoc;
  set lastExploreDoc(DocumentSnapshot? value) => _state.lastExploreDoc = value;
  RxBool get exploreHasMore => _state.exploreHasMore;
  RxBool get exploreIsLoading => _state.exploreIsLoading;
  RxBool get explorePreviewSuspended => _state.explorePreviewSuspended;
  RxInt get explorePreviewFocusIndex => _state.explorePreviewFocusIndex;
  ScrollController get videoScroll => _state.videoScroll;
  RxList<PostsModel> get exploreVideos => _state.exploreVideos;
  DocumentSnapshot? get lastVideoDoc => _state.lastVideoDoc;
  set lastVideoDoc(DocumentSnapshot? value) => _state.lastVideoDoc = value;
  RxBool get videoHasMore => _state.videoHasMore;
  RxBool get videoIsLoading => _state.videoIsLoading;
  ScrollController get photoScroll => _state.photoScroll;
  RxList<PostsModel> get explorePhotos => _state.explorePhotos;
  DocumentSnapshot? get lastPhotoDoc => _state.lastPhotoDoc;
  set lastPhotoDoc(DocumentSnapshot? value) => _state.lastPhotoDoc = value;
  RxBool get photoHasMore => _state.photoHasMore;
  RxBool get photoIsLoading => _state.photoIsLoading;
  ScrollController get floodsScroll => _state.floodsScroll;
  RxList<PostsModel> get exploreFloods => _state.exploreFloods;
  DocumentSnapshot? get lastFloodsDoc => _state.lastFloodsDoc;
  set lastFloodsDoc(DocumentSnapshot? value) => _state.lastFloodsDoc = value;
  RxBool get floodsHasMore => _state.floodsHasMore;
  RxBool get floodsIsLoading => _state.floodsIsLoading;
  RxInt get floodsVisibleIndex => _state.floodsVisibleIndex;
  int? get lastFloodVisibleIndex => _state.lastFloodVisibleIndex;
  set lastFloodVisibleIndex(int? value) => _state.lastFloodVisibleIndex = value;
  String? get _pendingFloodDocId => _state.pendingFloodDocId;
  set _pendingFloodDocId(String? value) => _state.pendingFloodDocId = value;
  RxBool get showScrollToTop => _state.showScrollToTop;
  RxSet<String> get followingIDs => _state.followingIDs;
  int get _exploreEmptyScans => _state.exploreEmptyScans;
  set _exploreEmptyScans(int value) => _state.exploreEmptyScans = value;
  int get _videoEmptyScans => _state.videoEmptyScans;
  set _videoEmptyScans(int value) => _state.videoEmptyScans = value;
  int get _photoEmptyScans => _state.photoEmptyScans;
  set _photoEmptyScans(int value) => _state.photoEmptyScans = value;
  int get _floodsEmptyScans => _state.floodsEmptyScans;
  set _floodsEmptyScans(int value) => _state.floodsEmptyScans = value;
  Worker? get _currentUserWorker => _state.currentUserWorker;
  set _currentUserWorker(Worker? value) => _state.currentUserWorker = value;
  Timer? get _searchDebounce => _state.searchDebounce;
  set _searchDebounce(Timer? value) => _state.searchDebounce = value;
  int get _searchRequestId => _state.searchRequestId;
  set _searchRequestId(int value) => _state.searchRequestId = value;
  String get _recentSearchReloadKey => _state.recentSearchReloadKey;
  set _recentSearchReloadKey(String value) =>
      _state.recentSearchReloadKey = value;
  Future<void>? get _startupPrepareFuture => _state.startupPrepareFuture;
  set _startupPrepareFuture(Future<void>? value) =>
      _state.startupPrepareFuture = value;
  bool get _startupShardHydrated => _state.startupShardHydrated;
  set _startupShardHydrated(bool value) => _state.startupShardHydrated = value;
  int? get _startupShardAgeMs => _state.startupShardAgeMs;
  set _startupShardAgeMs(int? value) => _state.startupShardAgeMs = value;
}
