import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:turqappv2/Core/Repositories/config_repository.dart';
import 'package:turqappv2/Core/Helpers/safe_external_link_guard.dart';
import 'package:turqappv2/Core/app_snackbar.dart';
import 'package:turqappv2/Utils/empty_padding.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';
import 'dart:async';

import '../Short/short_controller.dart';
import '../Agenda/agenda_controller.dart';
import '../Explore/explore_controller.dart';
import '../Education/education_controller.dart';
import '../Education/pasaj_tabs.dart';
import '../JobFinder/job_finder_controller.dart';
import '../Market/market_controller.dart';
import '../Profile/MyProfile/profile_controller.dart';
import '../Story/StoryRow/story_row_controller.dart';
import '../../Core/Services/ContentPolicy/content_policy.dart';
import '../../Core/Services/audio_focus_coordinator.dart';
import '../../Core/Services/CacheFirst/cache_first.dart';
import '../../Core/Services/integration_test_mode.dart';
import '../../Core/Services/read_budget_registry.dart';
import '../../Core/Services/upload_queue_service.dart';
import '../../Core/Services/video_state_manager.dart';
import '../../Services/current_user_service.dart';
import '../Profile/Settings/settings_controller.dart';

part 'nav_bar_controller_lifecycle_part.dart';
part 'nav_bar_controller_base_part.dart';
part 'nav_bar_controller_class_part.dart';
part 'nav_bar_controller_facade_part.dart';
part 'nav_bar_controller_fields_part.dart';
part 'nav_bar_controller_support_part.dart';
part 'nav_bar_controller_update_part.dart';

typedef TextUpdate = String;
