import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:turqappv2/Core/app_snackbar.dart';
import 'package:turqappv2/Core/BottomSheets/no_yes_alert.dart';
import 'package:turqappv2/Core/Repositories/config_repository.dart';
import 'package:turqappv2/Core/Repositories/test_repository.dart';
import 'package:turqappv2/Core/Services/education_test_navigation_service.dart';
import 'package:turqappv2/Core/Services/profile_navigation_service.dart';
import 'package:turqappv2/Core/Services/user_summary_resolver.dart';
import 'package:turqappv2/Models/Education/tests_model.dart';
import 'package:turqappv2/Services/current_user_service.dart';

part 'tests_grid_controller_data_part.dart';
part 'tests_grid_controller_class_part.dart';
part 'tests_grid_controller_facade_part.dart';
part 'tests_grid_controller_fields_part.dart';
part 'tests_grid_controller_runtime_part.dart';
part 'tests_grid_controller_actions_part.dart';
