part of 'current_user_model.dart';

extension CurrentUserModelUtilsPart on CurrentUserModel {
  CurrentUserModel copyWith({
    String? userID,
    String? nickname,
    String? firstName,
    String? lastName,
    String? avatarUrl,
    String? email,
    String? phoneNumber,
    String? bio,
    String? rozet,
    bool? hesapOnayi,
    bool? gizliHesap,
    bool? aramaIzin,
    bool? mailIzin,
    int? viewSelection,
    List<String>? ilgialanlari,
    String? meslekKategori,
    int? counterOfFollowers,
    int? counterOfFollowings,
    int? counterOfPosts,
    int? counterOfLikes,
    int? moderationStrikeCount,
    int? moderationLevel,
    int? moderationRestrictedUntil,
    bool? moderationPermanentBan,
    String? moderationBanReason,
    int? moderationUpdatedAt,
    List<String>? blockedUsers,
    List<String>? lastSearchList,
    List<String>? readStories,
    Map<String, int>? readStoriesTimes,
  }) {
    final resolvedAramaIzin = aramaIzin ?? this.aramaIzin;
    final resolvedMailIzin = mailIzin ?? this.mailIzin;
    return CurrentUserModel(
      userID: userID ?? this.userID,
      nickname: nickname ?? this.nickname,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      email: email ?? this.email,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      tc: tc,
      dogumTarihi: dogumTarihi,
      cinsiyet: cinsiyet,
      bio: bio ?? this.bio,
      rozet: rozet ?? this.rozet,
      hesapOnayi: hesapOnayi ?? this.hesapOnayi,
      gizliHesap: gizliHesap ?? this.gizliHesap,
      viewSelection: viewSelection ?? this.viewSelection,
      ilgialanlari: ilgialanlari ?? this.ilgialanlari,
      favoriMuzikler: favoriMuzikler,
      meslekKategori: meslekKategori ?? this.meslekKategori,
      calismaDurumu: calismaDurumu,
      medeniHal: medeniHal,
      counterOfFollowers: counterOfFollowers ?? this.counterOfFollowers,
      counterOfFollowings: counterOfFollowings ?? this.counterOfFollowings,
      counterOfPosts: counterOfPosts ?? this.counterOfPosts,
      counterOfLikes: counterOfLikes ?? this.counterOfLikes,
      antPoint: antPoint,
      dailyDurations: dailyDurations,
      educationLevel: educationLevel,
      universite: universite,
      fakulte: fakulte,
      bolum: bolum,
      ogrenciNo: ogrenciNo,
      ogretimTipi: ogretimTipi,
      sinif: sinif,
      lise: lise,
      ortaOkul: ortaOkul,
      okul: okul,
      okulSehir: okulSehir,
      okulIlce: okulIlce,
      ortalamaPuan: ortalamaPuan,
      ortalamaPuan1: ortalamaPuan1,
      ortalamaPuan2: ortalamaPuan2,
      defAnaBaslik: defAnaBaslik,
      defDers: defDers,
      defSinavTuru: defSinavTuru,
      osymPuanTuru: osymPuanTuru,
      osysPuan: osysPuan,
      osysPuani1: osysPuani1,
      osysPuani2: osysPuani2,
      yuzlukSistem: yuzlukSistem,
      adres: adres,
      ulke: ulke,
      city: city,
      town: town,
      il: il,
      ilce: ilce,
      ikametSehir: ikametSehir,
      ikametIlce: ikametIlce,
      nufusSehir: nufusSehir,
      nufusIlce: nufusIlce,
      nufusaKayitliOlduguYer: nufusaKayitliOlduguYer,
      locationSehir: locationSehir,
      kolayAdresSelection: kolayAdresSelection,
      familyInfo: familyInfo,
      totalLiving: totalLiving,
      motherName: motherName,
      motherSurname: motherSurname,
      motherPhone: motherPhone,
      motherJob: motherJob,
      motherSalary: motherSalary,
      motherLiving: motherLiving,
      fatherName: fatherName,
      fatherSurname: fatherSurname,
      fatherPhone: fatherPhone,
      fatherJob: fatherJob,
      fatherSalary: fatherSalary,
      fatherLiving: fatherLiving,
      evMulkiyeti: evMulkiyeti,
      mulkiyet: mulkiyet,
      yurt: yurt,
      bursVerebilir: bursVerebilir,
      engelliRaporu: engelliRaporu,
      isDisabled: isDisabled,
      bank: bank,
      iban: iban,
      ban: ban,
      moderationStrikeCount:
          moderationStrikeCount ?? this.moderationStrikeCount,
      moderationLevel: moderationLevel ?? this.moderationLevel,
      moderationRestrictedUntil:
          moderationRestrictedUntil ?? this.moderationRestrictedUntil,
      moderationPermanentBan:
          moderationPermanentBan ?? this.moderationPermanentBan,
      moderationBanReason: moderationBanReason ?? this.moderationBanReason,
      moderationUpdatedAt: moderationUpdatedAt ?? this.moderationUpdatedAt,
      deletedAccount: deletedAccount,
      bot: bot,
      signInMethod: signInMethod,
      sifre: sifre,
      refCode: refCode,
      blockedUsers: blockedUsers ?? this.blockedUsers,
      device: device,
      deviceID: deviceID,
      deviceVersion: deviceVersion,
      token: token,
      createdDate: createdDate,
      bildirim: bildirim,
      aramaIzin: resolvedAramaIzin,
      mailIzin: resolvedMailIzin,
      whatsappIzin: whatsappIzin,
      rehber: rehber,
      settings: settings,
      themeSettings: themeSettings,
      canliYayin: canliYayin,
      lastSearchList: lastSearchList ?? this.lastSearchList,
      readStories: readStories ?? this.readStories,
      readStoriesTimes: readStoriesTimes ?? this.readStoriesTimes,
      mail: mail,
    );
  }

  String get fullName => '$firstName $lastName'.trim();
  bool get hasProfileImage => avatarUrl.isNotEmpty;
  bool get isVerified => hesapOnayi;
  bool get isPrivate => gizliHesap;
  bool get isBanned => ban;
  bool get isPermanentAppBan => ban || moderationPermanentBan;
  bool get hasActiveInteractionRestriction =>
      !isPermanentAppBan &&
      moderationLevel > 0 &&
      moderationRestrictedUntil > DateTime.now().millisecondsSinceEpoch;
  bool get hasBio => bio.isNotEmpty;
}
