import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:turqappv2/Core/Repositories/config_repository.dart';
import 'package:image_picker/image_picker.dart';
import 'package:nsfw_detector_flutter/nsfw_detector_flutter.dart';
import 'package:turqappv2/Core/external.dart';
import 'package:turqappv2/Core/Repositories/test_repository.dart';
import 'package:turqappv2/Core/Services/app_image_picker_service.dart';
import 'package:turqappv2/Core/Services/legacy_tests_feature_gate.dart';
import 'package:turqappv2/Core/Services/webp_upload_service.dart';
import 'package:turqappv2/Models/Education/test_readiness_model.dart';
import 'package:turqappv2/Models/Education/tests_model.dart';
import 'package:turqappv2/Modules/Education/Tests/AddTestQuestion/add_test_question.dart';
import 'package:turqappv2/Services/current_user_service.dart';

part 'create_test_controller_actions_part.dart';
part 'create_test_controller_base_part.dart';
part 'create_test_controller_class_part.dart';
part 'create_test_controller_data_part.dart';
part 'create_test_controller_facade_part.dart';
part 'create_test_controller_fields_part.dart';

const createTestTypeMiddleSchool = 'Ortaokul';
const createTestTypeHighSchool = 'Lise';
const createTestTypePrep = 'Hazırlık';
const createTestTypeLanguage = 'Dil';
const createTestTypeBranch = 'Branş';
