part of 'blocked_texts.dart';

final List<String> _kufurlerPart2 = <String>[
  "yaraksız",
  "yaraktr",
  "yaram",
  "yaraminbasi",
  "yaramn",
  "yararmorospunun",
  "yarra",
  "yarraaaa",
  "yarraak",
  "yarraam",
  "yarraamı",
  "yarragi",
  "yarragimi",
  "yarragina",
  "yarragindan",
  "yarragm",
  "yarrağ",
  "yarrağım",
  "yarrağımı",
  "yarraimin",
  "yarrak",
  "yarram",
  "yarramin",
  "yarraminbaşı",
  "yarramn",
  "yarran",
  "yarrana",
  "yarrrak",
  "yavak",
  "yavş",
  "yavşak",
  "yavşaktır",
  "yavuşak",
  "yılışık",
  "yilisik",
  "yogurtlayam",
  "yoğurtlayam",
  "yrrak",
  "zıkkımım",
  "zibidi",
  "zigsin",
  "zikeyim",
  "zikiiim",
  "zikiim",
  "zikik",
  "zikim",
  "ziksiiin",
  "ziksiin",
  "zulliyetini",
  "zviyetini",
  "ambiti",
  "amcık",
  "amck",
  "amık",
  "amını",
  "amına",
  "amında",
  "amsalak",
  "dalyarak",
  "daşak",
  "daşağı",
  "daşşak",
  "daşşağı",
  "domal",
  "fahişe",
  "folloş",
  "fuck",
  "fucker",
  "fucking",
  "gavat",
  "godoş",
  "göt",
  "hasiktir",
  "hassiktir",
  "ibne",
  "ipne",
  "kahbe",
  "kaltak",
  "kaltağ",
  "kancık",
  "kancığ",
  "kavat",
  "kerane",
  "kerhane",
  "kevaşe",
  "mastırbasyon",
  "masturbasyon",
  "mastürbasyon",
  "orosbu",
  "orospu",
  "orusbu",
  "oruspu",
  "orsp",
  "motherfucker",
  "pezevenk",
  "pzvnk",
  "qavat",
  "scheiße",
  "scheisse",
  "sakso",
  "shit",
  "shitty",
  "sıçar",
  "sıçayım",
  "sıçmak",
  "sıçsın",
  "sikem",
  "siker",
  "sikeyim",
  "sikici",
  "sikik",
  "sikim",
  "sikiş",
  "sikle",
  "sikme",
  "siktir",
  "sktr",
  "siktiği",
  "sokarım",
  "sokayım",
  "taşak",
  "taşağa",
  "taşağı",
  "taşşak",
  "taşşağa",
  "taşşağı",
  "yarağ",
  "yarra",
  "yrrk",
  "arschloch",
  "asshole",
  "cunt",
  "fotze",
  "hure",
  "hurensohn",
  "verfickt",
  "wichser",
  "Ağzını burnunu dağıtırım",
  "Ağzını yırtarım",
  "Aklını alırım",
  "Allah belanı versin",
  "Ameliyat ederim",
  "Anan kötü",
  "Anasına bak kızını al",
  "Arkana adam takarım",
  "Asarım keserim",
  "Aşağılık kadın",
  "Ateşin başına vurdu",
  "Ayağa düşürürüm",
  "Baban uyuz",
  "Babasının piçi",
  "Bacaklarını kırarım",
  "Benim kölemsin",
  "Bıçağı al karnına sok",
  "Boğazını kesecem",
  "Çerçeveni dağıtırım",
  "Çürük kadın",
  "Çürümüşsün",
  "Dadı",
  "Dağa kaldırırım",
  "Davul olasın",
  "Dayaktan öldürürüm",
  "Dostundan geliyorsun",
  "Dünyanın o...su",
  "Elimde kalırsın",
  "Eşyasın",
  "Eteğine ettiğimin karısı",
  "Façanı aşağı alırım",
  "Fahişe",
  "Genelev kadını",
  "Genelevlere düşesin",
  "Git o..luk yap getir",
  "Gittiğim kadınlar sana ayna olurlar",
  "Gözünü keserim",
  "İmansız",
  "Kafanı gözünü kıracam",
  "Kaltak",
  "Kancık",
  "Kanı bozuk",
  "Karnını deşerim",
  "Kavatın kızı",
  "Kızışmış",
  "Kimden peydahladın",
  "Komaya sokarım",
  "Kopartacam",
  "Kölemsin",
  "Köpekler de doğuruyor",
  "Kötü yola düşesin",
  "Kullanıcam seni",
  "Kuş beyinli",
  "Mezarına tükürmem",
  "Öl geber",
  "Pavyon karısı",
  "Piç",
  "Piçlerinizle dönüp gelesiniz",
  "Sapık",
  "Sen bi b.. değilsin",
  "Sen de kadın mısın",
  "Seni ahıra dahi sokmam",
  "Seni çizerim",
  "Seni döverim",
  "Seni kim naapsın",
  "Seni kötü yola düşürecem",
  "Seni öldürecem",
  "Seni öyle bir döverim ki annen bile tanımaz",
  "Seni takip ettirecem",
  "Seni Türkiye’ye rezil edeceğim",
  "Seni vuracam",
  "Sokak sürtüğü",
  "Süprüntü",
  "Sütü bozuk",
  "Şerefsiz",
  "Şeyin başına vurdu",
  "Şirret",
  "Ulan karı",
  "Uyuz",
  "Vasat karı",
  "Ya çık git ya intihar et",
  "Yakalarsam seni satacam",
  "Yamuk kadın",
  "Yer cücesi",
  "Yeteneksiz",
  "Yüzüne kezzap atarım",
  "Yüzünü keserim",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "şerefsiz",
  "serefsiz",
  "kaşar",
  "kaltak",
  "amcık",
  "amcik",
  "gavat",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "got",
  "pic",
  "yarak",
  "aminakoyayim",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktigimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarragim",
  "anani",
  "anani sikeyim",
  "ananiskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "serefsiz",
  "kasar",
  "kaltak",
  "amcik",
  "gavat",
  "yavsak",
  "anan",
  "amına",
  "amkç",
  "amk q",
  "amkq",
  "amına koyim",
  "aminakoyim",
  "yarrağımın",
  "yarrağın",
  "sikik",
  "siktirgit",
  "sikik",
  "gavat",
  "yavşak",
  "yavşak orospu çocuğu",
  "dalyar",
  "dalyarak",
  "şırfıntı",
  "şıllık",
  "çük",
  "sikiş",
  "sikiştir",
  "inek",
  "dangoz",
  "kalas",
  "yavşama",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babaninamkgoyum",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "şerefsiz",
  "serefsiz",
  "kaşar",
  "amcık",
  "amcik",
  "gavat",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "kasar",
  "amcik",
];
