part of 'blocked_texts.dart';

final List<String> _kufurlerPart2 = <String>[
  "yaraksız",
  "yaraktr",
  "yaram",
  "yaraminbasi",
  "yaramn",
  "yararmorospunun",
  "yarra",
  "yarraaaa",
  "yarraak",
  "yarraam",
  "yarraamı",
  "yarragi",
  "yarragimi",
  "yarragina",
  "yarragindan",
  "yarragm",
  "yarrağ",
  "yarrağım",
  "yarrağımı",
  "yarraimin",
  "yarrak",
  "yarram",
  "yarramin",
  "yarraminbaşı",
  "yarramn",
  "yarran",
  "yarrana",
  "yarrrak",
  "yavak",
  "yavş",
  "yavşak",
  "yavşaktır",
  "yavuşak",
  "yılışık",
  "yilisik",
  "yogurtlayam",
  "yoğurtlayam",
  "yrrak",
  "zıkkımım",
  "zibidi",
  "zigsin",
  "zikeyim",
  "zikiiim",
  "zikiim",
  "zikik",
  "zikim",
  "ziksiiin",
  "ziksiin",
  "zulliyetini",
  "zviyetini",
  "ambiti",
  "amcık",
  "amck",
  "amık",
  "amını",
  "amına",
  "amında",
  "amsalak",
  "dalyarak",
  "daşak",
  "daşağı",
  "daşşak",
  "daşşağı",
  "domal",
  "folloş",
  "fuck",
  "fucker",
  "fucking",
  "godoş",
  "göt",
  "hasiktir",
  "hassiktir",
  "ipne",
  "kahbe",
  "kaltağ",
  "kancığ",
  "kavat",
  "kerane",
  "kerhane",
  "kevaşe",
  "mastırbasyon",
  "masturbasyon",
  "mastürbasyon",
  "orosbu",
  "orospu",
  "orusbu",
  "oruspu",
  "orsp",
  "motherfucker",
  "pezevenk",
  "pzvnk",
  "qavat",
  "scheiße",
  "scheisse",
  "sakso",
  "shit",
  "shitty",
  "sıçar",
  "sıçayım",
  "sıçmak",
  "sıçsın",
  "sikem",
  "siker",
  "sikeyim",
  "sikici",
  "sikik",
  "sikim",
  "sikiş",
  "sikle",
  "sikme",
  "siktir",
  "sktr",
  "siktiği",
  "sokarım",
  "sokayım",
  "taşak",
  "taşağa",
  "taşağı",
  "taşşak",
  "taşşağa",
  "taşşağı",
  "yarağ",
  "yarra",
  "yrrk",
  "arschloch",
  "asshole",
  "cunt",
  "fotze",
  "hurensohn",
  "verfickt",
  "wichser",
  "Ağzını burnunu dağıtırım",
  "Ağzını yırtarım",
  "Aklını alırım",
  "Allah belanı versin",
  "Ameliyat ederim",
  "Anan kötü",
  "Anasına bak kızını al",
  "Arkana adam takarım",
  "Asarım keserim",
  "Aşağılık kadın",
  "Ateşin başına vurdu",
  "Ayağa düşürürüm",
  "Baban uyuz",
  "Babasının piçi",
  "Bacaklarını kırarım",
  "Bıçağı al karnına sok",
  "Boğazını kesecem",
  "Çerçeveni dağıtırım",
  "Çürük kadın",
  "Çürümüşsün",
  "Dağa kaldırırım",
  "Davul olasın",
  "Dayaktan öldürürüm",
  "Dünyanın o...su",
  "Elimde kalırsın",
  "Eteğine ettiğimin karısı",
  "Façanı aşağı alırım",
  "Git o..luk yap getir",
  "Gittiğim kadınlar sana ayna olurlar",
  "Gözünü keserim",
  "Kafanı gözünü kıracam",
  "Kanı bozuk",
  "Karnını deşerim",
  "Kimden peydahladın",
  "Komaya sokarım",
  "Kopartacam",
  "Kötü yola düşesin",
  "Kullanıcam seni",
  "Mezarına tükürmem",
  "Öl geber",
  "Piç",
  "Piçlerinizle dönüp gelesiniz",
  "Seni çizerim",
  "Seni döverim",
  "Seni kim naapsın",
  "Seni kötü yola düşürecem",
  "Seni öldürecem",
  "Seni öyle bir döverim ki annen bile tanımaz",
  "Seni takip ettirecem",
  "Seni Türkiye’ye rezil edeceğim",
  "Seni vuracam",
  "Süprüntü",
  "Şeyin başına vurdu",
  "Ulan karı",
  "Uyuz",
  "Vasat karı",
  "Yakalarsam seni satacam",
  "Yer cücesi",
  "Yeteneksiz",
  "Yüzüne kezzap atarım",
  "Yüzünü keserim",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "amcık",
  "amcik",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "got",
  "pic",
  "yarak",
  "aminakoyayim",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktigimin",
  "siktimin",
  "sikimsonik",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarragim",
  "anani",
  "anani sikeyim",
  "ananiskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "amcik",
  "yavsak",
  "anan",
  "amına",
  "amkç",
  "amk q",
  "amkq",
  "amına koyim",
  "aminakoyim",
  "yarrağımın",
  "yarrağın",
  "sikik",
  "siktirgit",
  "sikik",
  "yavşak",
  "yavşak orospu çocuğu",
  "dalyar",
  "dalyarak",
  "şırfıntı",
  "şıllık",
  "çük",
  "sikiş",
  "sikiştir",
  "yavşama",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babaninamkgoyum",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "amcık",
  "amcik",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "kasar",
  "amcik",
];
