part of 'blocked_texts.dart';

final List<String> _kufurlerPart2 = <String>[
  "yaraksız",
  "yaraktr",
  "yaram",
  "yaraminbasi",
  "yaramn",
  "yararmorospunun",
  "yarra",
  "yarraaaa",
  "yarraak",
  "yarraam",
  "yarraamı",
  "yarragi",
  "yarragimi",
  "yarragina",
  "yarragindan",
  "yarragm",
  "yarrağ",
  "yarrağım",
  "yarrağımı",
  "yarraimin",
  "yarrak",
  "yarram",
  "yarramin",
  "yarraminbaşı",
  "yarramn",
  "yarran",
  "yarrana",
  "yarrrak",
  "yavak",
  "yavş",
  "yavşak",
  "yavşaktır",
  "yavuşak",
  "yılışık",
  "yilisik",
  "yogurtlayam",
  "yoğurtlayam",
  "yrrak",
  "zıkkımım",
  "zibidi",
  "zigsin",
  "zikeyim",
  "zikiiim",
  "zikiim",
  "zikik",
  "zikim",
  "ziksiiin",
  "ziksiin",
  "zulliyetini",
  "zviyetini",
  "ambiti",
  "amcık",
  "amck",
  "amık",
  "amını",
  "amına",
  "amında",
  "amsalak",
  "dalyarak",
  "daşak",
  "daşağı",
  "daşşak",
  "daşşağı",
  "domal",
  "fahişe",
  "folloş",
  "fuck",
  "fucker",
  "fucking",
  "gavat",
  "godoş",
  "göt",
  "hasiktir",
  "hassiktir",
  "idiot",
  "ibne",
  "ipne",
  "kahpe",
  "kahbe",
  "kaltak",
  "kaltağ",
  "kancık",
  "kancığ",
  "kavat",
  "kerane",
  "kerhane",
  "kevaşe",
  "mastırbasyon",
  "masturbasyon",
  "mastürbasyon",
  "orosbu",
  "orospu",
  "orusbu",
  "oruspu",
  "orsp",
  "motherfucker",
  "pezevenk",
  "pzvnk",
  "puşt",
  "qavat",
  "scheiße",
  "scheisse",
  "sakso",
  "shit",
  "shitty",
  "sıçar",
  "sıçayım",
  "sıçmak",
  "sıçsın",
  "sikem",
  "siker",
  "sikeyim",
  "sikici",
  "sikik",
  "sikim",
  "sikiş",
  "sikle",
  "sikme",
  "siktir",
  "sktr",
  "siktiği",
  "sokarım",
  "sokayım",
  "sürtük",
  "sperm",
  "taşak",
  "taşağa",
  "taşağı",
  "taşşak",
  "taşşağa",
  "taşşağı",
  "vajina",
  "yalaka",
  "yarağ",
  "yarra",
  "yrrk",
  "arschloch",
  "fotze",
  "hure",
  "hurensohn",
  "verdammt",
  "verfickt",
  "wichser",
  "Ağzını burnunu dağıtırım",
  "Ağzını yırtarım",
  "Aklını alırım",
  "Allah belanı versin",
  "Ameliyat ederim",
  "Anan kötü",
  "Anasına bak kızını al",
  "Angut",
  "Aptal",
  "Arkana adam takarım",
  "Artist",
  "Asarım keserim",
  "Aşağılık kadın",
  "Ateşin başına vurdu",
  "Ayağa düşürürüm",
  "Ayı",
  "Azgın",
  "Baban uyuz",
  "Babasının piçi",
  "Bacaklarını kırarım",
  "Benim kölemsin",
  "Beyinsiz",
  "Bıçağı al karnına sok",
  "Bilgisiz",
  "Boğazını kesecem",
  "Cahil",
  "Çerçeveni dağıtırım",
  "Çirkin",
  "Çürük kadın",
  "Çürümüşsün",
  "Dadı",
  "Dağa kaldırırım",
  "Davul olasın",
  "Dayaktan öldürürüm",
  "Deli",
  "Dinsiz",
  "Domuz",
  "Dostundan geliyorsun",
  "Dümbüğün kızı",
  "Dümbük",
  "Dünyanın o...su",
  "Eksik etek",
  "Elimde kalırsın",
  "Eşek",
  "Eşek çobanı",
  "Eşeklik yaptım evlendim",
  "Eşyasın",
  "Eteğine ettiğimin karısı",
  "Façanı aşağı alırım",
  "Fahişe",
  "Fettan",
  "Gavurun dölü",
  "Genelev kadını",
  "Genelevlere düşesin",
  "Geri zekalı",
  "Git o..luk yap getir",
  "Gittiğim kadınlar sana ayna olurlar",
  "Görgüsüz",
  "Gözünü keserim",
  "Hayvan",
  "Hoşt",
  "İmansız",
  "Kadın erkeğin elinin kiridir",
  "Kadın olsaydın da elinde tutsaydın",
  "Kafanı gözünü kıracam",
  "Kahpe",
  "Kahpe yapacam sizi",
  "Kaltak",
  "Kancık",
  "Kanı bozuk",
  "Karnını deşerim",
  "Kavatın kızı",
  "Kepaze",
  "Kızışmış",
  "Kimden peydahladın",
  "Kime veriyorsun",
  "Komaya sokarım",
  "Kopartacam",
  "Kölemsin",
  "Köpekler de doğuruyor",
  "Kötü kadın",
  "Kötü yola düşesin",
  "Kullanıcam seni",
  "Kuru",
  "Kuş beyinli",
  "Mezarına tükürmem",
  "Mikrop",
  "Öl geber",
  "Pasaklı",
  "Pavyon karısı",
  "Pısırık",
  "Piç",
  "Piçlerinizle dönüp gelesiniz",
  "Psikopat",
  "Puşt",
  "Saçaklı",
  "Salak",
  "Salaklaşma",
  "Sapık",
  "Sen bi b.. değilsin",
  "Sen de kadın mısın",
  "Seni ahıra dahi sokmam",
  "Seni çizerim",
  "Seni döverim",
  "Seni kim naapsın",
  "Seni kötü yola düşürecem",
  "Seni öldürecem",
  "Seni öyle bir döverim ki annen bile tanımaz",
  "Seni takip ettirecem",
  "Seni Türkiye’ye rezil edeceğim",
  "Seni vuracam",
  "Sokak sürtüğü",
  "Süprüntü",
  "Sürtük",
  "Sütü bozuk",
  "Şerefsiz",
  "Şeyin başına vurdu",
  "Şırfıntı",
  "Şirret",
  "Ulan karı",
  "Uyuz",
  "Vasat karı",
  "Ya çık git ya intihar et",
  "Yakalarsam seni satacam",
  "Yamuk kadın",
  "Yer cücesi",
  "Yeteneksiz",
  "Yüzüne kezzap atarım",
  "Yüzünü keserim",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "ahmak",
  "allahsız",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "salak",
  "gerizekalı",
  "mal",
  "aptal",
  "sürtük",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "şerefsiz",
  "serefsiz",
  "kaşar",
  "kaltak",
  "amcık",
  "amcik",
  "gavat",
  "gavur",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "surtuk",
  "got",
  "pic",
  "yarak",
  "aminakoyayim",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktigimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarragim",
  "anani",
  "anani sikeyim",
  "ananiskm",
  "babani",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "serefsiz",
  "kasar",
  "kaltak",
  "amcik",
  "gavat",
  "gavur",
  "yavsak",
  "anan",
  "amına",
  "amkç",
  "amk q",
  "amkq",
  "amına koyim",
  "aminakoyim",
  "yarrağımın",
  "yarrağın",
  "sikik",
  "siktirgit",
  "sikik",
  "gavat",
  "yavşak",
  "yavşak orospu çocuğu",
  "dalyar",
  "dalyarak",
  "şırfıntı",
  "şıllık",
  "çük",
  "sikiş",
  "sikiştir",
  "öküz",
  "inek",
  "beyinsiz",
  "dangoz",
  "kalas",
  "geri zekalı",
  "yavşama",
  "abaza",
  "abazan",
  "ağzına sıçayım",
  "ahmak",
  "allahsız",
  "orospu",
  "o.ç",
  "oc",
  "amk",
  "aq",
  "mk",
  "sikik",
  "salak",
  "gerizekalı",
  "mal",
  "aptal",
  "sürtük",
  "sokuk",
  "göt",
  "got",
  "piç",
  "pic",
  "yarrak",
  "yarak",
  "amına koyayım",
  "aminakoyayım",
  "amina koyayim",
  "amq",
  "sikeyim",
  "skeyim",
  "sikem",
  "siken",
  "siktiğimin",
  "siktimin",
  "sikimsonik",
  "kaltak",
  "pezevenk",
  "pezo",
  "dalyarak",
  "yarrağım",
  "yarragım",
  "yarragim",
  "ananı",
  "ananı sikeyim",
  "ananıskm",
  "babaninamkgoyum",
  "babani skm",
  "hassiktir",
  "hasiktir",
  "ha sik tir",
  "haysiyetsiz",
  "karaktersiz",
  "şerefsiz",
  "serefsiz",
  "kaşar",
  "amcık",
  "amcik",
  "gavat",
  "gavur",
  "yavşak",
  "yavsak",
  "agzina sicayim",
  "gerizekali",
  "surtuk",
  "kasar",
  "amcik",
];
