List<String> interestList = [
  "Bilim, Eğitim, Teknoloji",
  "Yapay Zeka, Mühendislik",
  "Dijital Pazarlama, Finans",
  "İş, Kariyer, Girişimcilik",
  "Ekonomi, Hukuk, Tavsiye",
  "Motivasyon, Kişisel Gelişim",
  "Spor, Fitness, Sağlık",
  "Beslenme, Yaşam Tarzı",
  "Gezi, Seyahat, Doğa",
  "Çevre, Hayvanlar, Bitkiler",
  "Dekorasyon, Ev, Bahçe, Hobi",
  "Otomobil, Araçlar, Oyun",
  "Makine, İnşaat, Yapılar",
  "Eğlence, Ünlüler, Komedi",
  "Müzik, Sinema",
  "Haber, Siyaset, Tarih",
  "Psikoloji, Felsefe",
  "İnanç, Aile, İlişki, İpuçları",
  "Fotoğraf, Moda",
  "Sanat, Kitap, Kültür",
  "Yemek, İçecek, Tüketim",
  "Günlük Yaşam, Alışveriş",
];
