part of 'job_categories.dart';

final List<String> _allJobsPart2 = <String>[
  "Kişisel Gelişim Koçluğu Firması",
  "Kitapçı",
  "Klarnetçi",
  "Kodlama ve Yazılım Eğitimleri",
  "Koleksiyoncu",
  "Komedi Kulübü",
  "Komedyen",
  "Komisyoncu",
  "Konaklama ve Yeme-İçme",
  "Konser Alanı",
  "Konser Organizasyon Firması",
  "Konservatuvarlar",
  "Konserveci",
  "Konsolos",
  "Konsolosluk",
  "Kontrolör",
  "Konveyör Operatörü",
  "Kooperatifler",
  "Koreograf",
  "Koruma Görevlisi",
  "Kozmetik Ürün Mağazası",
  "Kozmolog",
  "Köfteci",
  "Kömürcü",
  "Köşe Yazarı",
  "Kreş",
  "Kriz İletişim Danışmanlıkları",
  "Kriz Yönetimi ve Afet Hazırlığı",
  "Kuaför",
  "Kumaş Üreticisi",
  "Kumaşçı",
  "Kumcu",
  "Kuru Temizleme",
  "Kuru Temizlemeci",
  "Kuruyemişçi",
  "Kurye",
  "Kuşbilimci",
  "Kuşçu",
  "Kuyumcu",
  "Küçük İşletme",
  "Küçük Perakendeci",
  "Kültür Merkezi",
  "Kültür Turları Organizasyonları",
  "Kültür ve Miras",
  "Kültür ve Sanat",
  "Kültürel Miras Koruma Merkezi",
  "Kürkçü",
  "Kütüphane",
  "Kütüphaneci",
  "Laborant",
  "Laboratuvar İşçisi",
  "Lahmacuncu",
  "Lastik Satıcısı",
  "Lehimci",
  "Levazımcı",
  "Liman İşletmesi",
  "Lise",
  "Lobici",
  "Lokanta",
  "Lokman",
  "Lokomotifçi",
  "Lunapark",
  "Lüks Araç Kiralama Hizmeti",
  "Lüks Tatil Köyleri",
  "Madenci",
  "Madencilik Şirketi",
  "Makasçı",
  "Makastar",
  "Maketçi",
  "Makine Mühendisi",
  "Makine Zabiti",
  "Makinist",
  "Mali Hizmetler Uzmanı",
  "Manav",
  "Manifaturacı",
  "Marangoz",
  "Marka Yönetim Danışmanlıkları",
  "Market Zinciri",
  "Market",
  "Masör",
  "Matbaacı",
  "Matematikçi",
  "Matkapçı",
  "Medikal Ekipman Üreticisi",
  "Medikal Teknoloji",
  "Medya Planlama Uzmanı",
  "Medya ve Yayın Teknolojisi",
  "Medya ve Yayıncılık",
  "Memur",
  "Menajer",
  "Mercan Resifi Koruma Organizasyonları",
  "Mermerci",
  "Meslek Edindirme Kursları",
  "Metal İşleme Atolyesi",
  "Metalurji Mühendisi",
  "Meteoroloji Uzmanı",
  "Metin Yazarı",
  "Metro ve Tramvay İstasyonu",
  "Mevsimlik İşçi",
  "Meydancı",
  "Meyve ve Sebze Tezgahları",
  "Meze Dükkanları",
  "Mikro Finans Kuruluşu",
  "Mikrobiyolog",
  "Milletvekili",
  "Milli Parklar",
  "Mimar ve Mühendislik",
  "Mimar",
  "Mimari ve Dekorasyon",
  "Mimarlık Ofisi",
  "Mimarlık Proje Ofisi",
  "Mobil Oyun Geliştiricisi",
  "Mobilya Mağazası",
  "Mobilya Montaj Hizmeti",
  "Mobilyacı",
  "Moda Markalarının Showroomları",
  "Moda Tasarım Akademisi",
  "Moda Tasarım Stüdyosu",
  "Moda ve Giyim",
  "Moda ve Tekstil",
  "Modacı",
  "Modelist",
  "Montajcı",
  "Montör",
  "Moteller",
  "Motor Tamircisi",
  "Motosiklet Servisi",
  "Muhabbet Tellalı",
  "Muhabir",
  "Muhafız",
  "Muhasebeci",
  "Muhtar",
  "Mutfak ve Banyo Dekorasyon Mağazası",
  "Mübaşir",
  "Müdür",
  "Müezzin",
  "Müfettiş",
  "Mühendis",
  "Mürebbiye",
  "Müsteşar",
  "Müşavir",
  "Müteahhit",
  "Müteahhitlik Hizmeti",
  "Mütercim",
  "Müze Müdürü",
  "Müze ve Sergi Salonu",
  "Müzeler",
  "Müzik Enstrümanları Satıcısı",
  "Müzik Kursları",
  "Müzik Okulu",
  "Müzik Stüdyosu",
  "Müzik ve Performans Sanatları",
  "Müzik Yönetmeni",
  "Müzisyen",
  "Nakışçı",
  "Nakliyat Firması",
  "Nakliye ve Lojistik Firması",
  "Nakliyeci",
  "Nalbant",
  "Nalbur",
  "Noter",
  "Ocakçı",
  "Odacı",
  "Oduncu",
  "Okçu",
  "Okul Müdürü",
  "Okul Öncesi Öğretmeni",
  "Okul",
  "Okutman",
  "Online Eğitim Platformu",
  "Online Eğitim Uygulamaları",
  "Online Haber Ajansı",
  "Online Pazarlama Şirketi",
  "Online Terapi Hizmeti",
  "Sanatçı",
  "Operatör",
  "Optik Mağazası",
  "Optik ve Gözlükçüler",
  "Organik Gıda ",
  "Organik Hayvancılık İşletmesi",
  "Organik Tarım Çiftlikleri",
  "Organik Ürün Marketi",
  "Organizasyon Firması",
  "Orgcu",
  "Orman Mühendisi",
  "Ornitolog (Veya Kuşbilimci)",
  "Ortaokul",
  "Otel",
  "Otelci",
  "Oto Elektrikçisi",
  "Oto Galeri",
  "Oto Lastik Tamircisi",
  "Oto Servis ve Tamirciler",
  "Oto Tamircisi",
  "Oto Yedek Parçacı",
  "Oto Yıkama ve Bakım Merkezi",
  "Oto Yıkama",
  "Otobüs Firması",
  "Otobüs Terminalleri",
  "Otomotiv Fabrikası",
  "Otomotiv ve Araç Hizmeti",
  "Otomotiv ve Ulaşım",
  "Otomotiv Yedek Parça Satıcısı",
  "Otomotiv",
  "Otoparklar",
  "Overlokçu",
  "Oyun Hostesi",
  "Oyun Konsolu ve Aksesuar Mağazası",
  "Oyun Salonu",
  "Oyun ve Eğlence Hizmeti",
  "Oyun ve Eğlence Teknolojileri",
  "Oyun Yazarı",
  "Oyun Yazılım Şirketi",
  "Oyuncak Mağazası",
  "Oyuncakçı",
  "Oyuncu",
  "Öğretim Elemanı",
  "Öğretim Görevlisi",
  "Öğretim Teknolojileri Geliştiren Firma",
  "Öğretim Üyesi",
  "Öğretmen",
  "Ön Büro Elemanı",
  "Ön Muhasebe Sorumlusu",
  "Ön Muhasebe Yardımcı Elemanı",
  "Ön Muhasebeci",
  "Örmeci",
  "Özel Dedektiflik Ofisi",
  "Özel Dikim Atolyesi",
  "Özel Eğitim Kurumu",
  "Özel Güvenlik Şirketi",
  "Özel Güvenlik ve Savunma",
  "Özel Jet Kiralama Şirketi",
  "Özel Koruma Hizmeti",
  "Özel Okullar",
  "Özel Parti ve Düğün Organizasyon Firması",
  "Özel Poliklinik",
  "Özel Şoför",
  "Paketleyici",
  "Palyaço",
  "Panayır ve Kermes Alanı",
  "Pandomimci",
  "Pansiyon",
  "Pansiyoncu",
  "Pansumancı",
  "Paramedik",
  "Park Bekçisi",
  "Pastane",
  "Pastörizör",
  "Patolog",
  "Paylaşımlı Çalışma Alanı (Co-working Spaces)",
  "Pencereci",
  "Perukçu",
  "Pet Kuaförleri",
  "Pet Shoplar",
  "Peynir Üreticisi",
  "Peyzaj Mimarı",
  "Peyzaj Mimarlık Ofisi",
  "Peyzaj Tasarım Firması",
  "Peyzaj Teknikeri",
  "Pideci",
  "Pideciler",
  "Pilates Stüdyosu",
  "Pilavcı",
  "Pilot",
  "Piyade",
  "Piyanist",
  "Podcast Stüdyosu",
  "Polis Karakolu",
  "Polisajcı",
  "Postacı",
  "Profesör",
  "Profesyonel Eğitim Akademisi",
  "Proktolog",
  "Protokol Görevlisi",
  "Prototip Üretim Atolyesi",
  "Psikiyatr",
  "Psikolog",
  "Psikolojik Danışmanlık Ve Rehberlik",
  "Radyo İstasyonu",
  "Radyolog",
  "Radyoloji Teknisyeni/Teknikeri",
  "Redaktör",
  "Rehabilitasyon Merkezi",
  "Rehber",
  "Rejisör",
  "Reklam Ajansı",
  "Reklamcı",
  "Rektör Yardımcısı",
  "Rektör",
  "Remayözcü",
  "Rent a Car Şirketi",
  "Resepsiyon Memuru",
  "Resim ve Sanat Atolyesi",
  "Ressam",
  "Restoran",
  "Restorasyon ve Tarihi Koruma",
  "Robotik ve Kodlama Atolyesi",
  "Robotik ve Kodlama Ürün Mağazası",
  "Rot Balansçı",
  "Saat Tamircisi",
  "Saat ve Mücevher Satıcısı",
  "Saatçi",
  "Sağlık Merkezi",
  "Sağlık Teknisyeni",
  "Sağlık Teknolojisi Geliştiren Şirket",
  "Sağlık ve Güzellik",
  "Sağlık",
  "Sağlıklı Yaşam ve Detoks Merkezi",
  "Sahil Koruma",
  "Sahne Tasarım ve Işıklandırma Şirketi",
  "Salepçi",
  "Sanal Gerçeklik Deneyim Merkezi",
  "Sanal Gerçeklik Deneyim Şirketi",
  "Sanal Sınıf Teknolojileri Geliştiricisi",
  "Sanal ve Dijital Hizmetler",
  "Sanat Atölyesi",
  "Sanat Galerileri",
  "Sanat Malzemeleri Satış Noktası",
  "Sanat Yönetmeni",
  "Sanayi ve Lojistik",
  "Sanayi ve Ticaret",
  "Sanayi ve Üretim",
  "Sanayici",
  "Sansürcü",
  "Santral Memuru",
  "Saraç",
  "Sarraf",
  "Satış Elemanı",
  "Satranç Kursları",
  "Savunma Sanayi Şirketi",
  "Savunma ve Güvenlik",
  "Saz Şairi",
  "Scooter ve Bisiklet Kiralama Noktası",
  "Sekreter",
  "Senarist",
  "Sendika",
  "Sepetçi",
  "Seracılar",
  "Seramik ve Çömlekçilik Atolyesi",
  "Serbest Muhasebeci Mali Müşavir",
  "Serbest Ticaret Bölgeleri",
  "Sergi Salonu",
  "Servis ve Teknik Destek Merkezi",
  "Ses Kayıt Stüdyosu",
  "Ses Teknisyeni",
  "Ses ve Işık Sistemleri Kiralama Firması",
  "Seyahat Acentesi",
  "Seyahat ve Ulaşım Hizmeti",
  "Seyis",
  "Seyyar Satıcı",
  "Sıfır Atık Proje Ofisi",
  "Sıfır Atık Üretim Tesisi",
  "Sicil Memuru",
  "Sigorta Şirketi",
  "Sigortacı",
  "Sihirbaz",
  "Silindir Operatörü",
  "Simitçi",
  "Simülasyon Teknolojileri Firması",
  "Simyacı",
  "Sinema Salonu",
  "Sinemalar",
  "Sistem Mühendisi",
  "Sistem Yöneticisi",
  "Sivil İnisiyatif Platformu",
  "Sivil Toplum ve İnsan Hakları",
  "Siyasetçi",
  "Soğuk Demirci",
  "Sokak Çalgıcısı",
  "Sokak Hayvanları Besleme Grupları",
  "Sokak Lezzetleri Noktası",
  "Sokak İşletme",
  "Solaryum Merkezi",
  "Son Ütücü",
  "Sosyal Etki ve Topluluk Gelişimi",
  "Sosyal Etkinlikler ve Organizasyon",
  "Sosyal Girişimcilik Organizasyonları",
  "Sosyal Güvenlik Merkezi",
  "Sosyal Hizmet Uzmanı",
  "Sosyal Hizmetler",
  "Sosyal Medya Yönetim Şirketi",
  "Sosyal Yardım Kuruluşu",
  "Sosyolog",
  "Spa Merkezi",
  "Spa ve Wellness Merkezi",
  "Spiker",
  "Spor Kamp Alanı",
  "Spor Kulübü",
  "Spor Mağazası",
  "Spor Malzemeleri ve Hizmeti",
  "Spor Salonu",
  "Spor ve Eğlence",
  "Spor ve Fitness",
  "Sporcu Beslenme ve Takviyeleri Üreticisi",
  "Sporcu",
  "Stadyum",
  "Start-up Kuluçka Merkezi",
  "STEM Eğitim Programları",
  "Stenograf",
  "Stilist",
  "Su Altı Fotoğrafçılığı Atolyesi",
  "Su Kayağı ve Jet Ski Merkezi",
  "Su Sporları Merkezi",
  "Su Tesisatçısı",
  "Su Ürünleri Yetiştiriciliği Kooperatifi",
  "Su ve Doğalgaz Dağıtım Şirketi",
  "Sucu",
  "Suflör",
  "Sulama Sistemleri Mağazası",
  "Sulama Sistemleri Üreticisi",
  "Sunucu",
  "Susuz Araç Yıkama",
  "Sünnetçi",
  "Süpermarket",
  "Sürdürülebilir Moda Atolyesi",
  "Sürdürülebilirlik ve Yenilik",
  "Süt Ürünleri İşleme Tesisi",
  "Sütçü",
  "Şair",
  "Şapkacı",
  "Şarkı Sözü Yazarı",
  "Şarkıcı",
  "Şarküter",
  "Şarküteri, Gıda Pazarları Ve Bakkal Satış Elemanı",
  "Şehir İçi Taşımacılık Firması",
  "Şehir Plancısı",
  "Şehir Turları Rehberlik Hizmeti",
  "Şehir Turu Otobüsleri",
  "Şekerci",
  "Şemsiyeci",
  "Şıracı",
  "Şifre Çözümleyici",
  "Şirket",
  "Şoför",
  "Tabakçı",
  "Tabelacı",
  "Tahsildar",
  "Takı Tasarım Atolyesi",
  "Takı ve Aksesuar Dükkanı",
  "Takı ve Kuyumcu",
  "Taksi Durakları",
  "Taksici",
  "Tarım Aletleri Satıcısı",
  "Tarım Drone Hizmeti",
  "Tarım İşçisi",
  "Tarım Makinesi Satıcısı",
  "Tarım Malzemesi Satıcısı",
  "Tarım Teknolojileri",
  "Tarım ve Bahçe",
  "Tarım ve Hayvancılık İşletmesi",
  "Tarım ve Hayvancılık",
  "Tarihçi",
  "Tarihi Eser Restorasyon Firması",
  "Tarihi Yapı Rehberlik Hizmeti",
  "Tasarımcı",
  "Taşçı",
  "Taşımacılık Firması",
  "Taşımacılık ve Araç Hizmeti",
  "Taşımacılık ve Lojistik",
  "Taşlayıcı",
  "Tatil Köyü",
  "Tatlıcı",
  "Tatlıcılar (Baklavacılar, Lokmacılar)",
  "Tavuk Çiftliği",
  "Tavukçu",
  "Tayfa",
  "Teknik Eğitim Merkezi",
  "Tekniker",
  "Teknisyen",
  "Teknoloji Danışmanlık Firması",
  "Teknoloji Geliştirme Bölgeleri (Teknoparklar)",
  "Teknoloji Geliştirme ve İnovasyon",
  "Teknoloji Mağazası",
  "Teknoloji Perakendeciliği",
  "Teknoloji Transfer Ofisi",
  "Teknoloji Uzmani",
  "Teknoloji ve İletişim",
  "Tekstil Fabrikası",
  "Tekstil İhracatçısı Firmalar",
  "Tekstil Üretim Tesisi",
  "Telefon Operatörü",
  "Telekomünikasyon Şirketi",
  "Tele-tıp Hizmeti",
  "Televizyon Tamircisi",
  "Tellal",
  "Temizlik Firması",
  "Temizlik Şirketi",
  "Temizlikçi",
  "Temsilci",
  "Tenis Kortu",
  "Terapist",
  "Tercüman",
  "Termal Otel",
  "Terzi",
  "Tesisatçı",
  "Test Mühendisi",
  "Test Pilotu",
  "Tesviyeci",
  "Teşrifatçı",
  "Tezgahtar",
  "Tıp Doktoru",
  "Tıp Merkezi",
  "Ticaret Odası",
  "Ticaret ve Pazarlama",
  "Tiyatro Eğitim Merkezi",
  "Tiyatro Salonu",
  "Tiyatro Yönetmeni",
  "Tiyatrolar",
  "Tohum ve Fide Üreticisi",
  "Topçu",
  "Toplum Destekli Tarım (CSA)",
  "Toplum Merkezi",
  "Toplumsal Eşitlik Platformu",
  "Toptan ve Dağıtım",
  "Toptancılar",
  "Tornacı",
  "Tren İstasyonu",
  "Tuhafiyeci",
  "Tur Operatörleri",
  "Turizm ve Eğlence",
  "Turizm ve Konaklama",
  "Turizm ve Tatil Hizmeti",
  "Turizm",
  "Turizmci",
  "Turşucu",
  "Tuzcu",
  "TV Kanalları",
  "Uçak Bakım Mühendisi",
  "Uçuş Teknisyeni",
  "Ulaşım Sorumlusu",
  "Ulaşım ve Seyahat",
  "Ulaşım",
  "Ulaştırma",
  "Uluslararası Fuar Alanı",
  "Uluslararası İş ve Ticaret",
  "Uluslararası İşletme",
  "Uluslararası Kurum",
  "Uluslararası Nakliye Firması",
  "Uluslararası Okul",
  "Uluslararası STK'lar",
  "Uluslararası Ticaret Danışmanlığı",
  "Ustabaşı",
  "Uydu Antenci",
  "Uydu Teknolojileri Şirketi",
  "Uzaktan Çalışma Platformu",
  "Uzaktan Çalışma ve Freelance",
  "Uzaktan Eğitim Platformu",
  "Uzaktan İşletme Eğitimleri",
  "Uzay Araştırma Merkezi",
  "Uzay Bilimcisi",
  "Uzay Mühendisi",
  "Uzay ve Havacılık",
  "Uzman Çavuş",
  "Üniversite",
  "Üretici",
  "Üretim Fabrikası",
  "Ürolog",
  "Üst Düzey Yönetici",
  "Ütücü",
  "Üzümcü",
  "Vaiz",
  "Vakıf",
  "Vatman",
  "Vergi Daireleri",
  "Vergi Denetmeni",
  "Vergi Müfettişi",
  "Vergi Tahakkuk Memuru",
  "Veri Hazırlama Ve Kontrol İşletmeni",
  "Veritabanı Yöneticisi",
  "Vestiyerci",
  "Veteriner Hekim",
  "Veteriner Kliniği",
  "Veteriner Sağlık Teknikeri",
  "Veteriner Sağlık Teknisyeni",
  "Veznedar",
  "Video Editörü",
  "Video İçerik Üretim Ajansı",
  "Video Prodüksiyon Şirketi",
  "Vinç Operatörü",
  "Vitrinci",
  "VR/AR Cihazları Satıcısı",
  "VR/AR Video Üreticisi",
  "Yabancı Dil Eğitim Merkezi",
  "Yabancı Yatırım Danışmanlık Firması",
  "Yangın Güvenliği Ekipmanları Satan Firmalar",
  "Yapay Zeka Geliştirme Şirketi",
  "Yapay Zeka Laboratuvarları",
  "Yapı Marketler",
  "Yaratıcı Sanatlar",
  "Yardım ve Destek Kurumu",
  "Yardımcı Hakem",
  "Yardımcı Hizmetli",
  "Yardımcı Pilot",
  "Yaşam Tarzı ve Hobi",
  "Yat Limanları",
  "Yat Üreticisi",
  "Yatırım Danışmanlık Şirketi",
  "Yatırım Uzmanı",
  "Yatırım ve Finans",
  "Yayıncı",
  "Yaz Kampları",
  "Yazar",
  "Yazı İşleri Müdürü",
  "Yazılım Firması",
  "Yazılım Mühendisi",
  "Yelkenci",
  "Yeme-İçme ve Gıda Satışı",
  "Yeminli Mali Müşavir",
  "Yeminli Tercüman",
  "Yeniden Ağaçlandırma Projeleri",
  "Yenilenebilir Enerji Kaynakları Geliştiricisi",
  "Yenilenebilir Enerji Şirketi",
  "Yer Gösterici",
  "Yer Teknisyeni",
  "Yerel Halk Dansı Grupları",
  "Yerel Üretici Pazarı",
  "Yerel ve Geleneksel İşletme",
  "Yerölçmeci",
  "Yeşil Enerji Şirketi",
  "Yetişkin Eğitim Merkezi",
  "Yetiştiricilik",
  "Yiyecek Üretimi ve Dağıtımı",
  "Yiyecek ve İçecek Üretimi",
  "Yoga Stüdyosu",
  "Yoga ve Meditasyon Merkezi",
  "Yol Bekçisi",
  "Yol ve Köprü İnşaat Şirketi",
  "Yorgancı",
  "Yorumcu",
  "Yönetici",
  "Yönetmen",
  "Yöresel Ürün Satıcısı",
  "Yumurtacı",
  "Yurt Dışı Eğitim ve Dil Kampı Organizasyonları",
  "Yurt",
  "Yüksek Kalite Mücevher Mağazası",
  "Yüzme Havuzu",
  "Yüzücü",
  "Zabıt Katibi",
  "Zabıta",
  "Zanaat ve El İşi",
  "Zayıflama Merkezi",
  "Zeytin ve Zeytinyağı İşletmesi",
  "Zeytinyağı Üreticisi",
  "Ziraat Mühendisi",
  "Zirai Ürün Satıcısı",
  "Zoolog",
  "Hizmet Sektörü",
  "Kahvaltı Salonu",
  "Paket Servis Restoranları",
  "Otomat Satış Hizmeti",
  "Yemek Dağıtım Şirketi",
  "Kentsel Ulaşım ve Taşımacılık",
  "Minibüs Durağı",
  "Dolmuş Hattı",
  "Şehir İçi Otobüs Durağı",
  "Bisiklet Kiralama Hizmeti",
  "Scooter Paylaşım Hizmeti",
  "Reklam ve Pazarlama",
  "Grafik Tasarım Ofisi",
  "Sosyal Medya Yönetim Firması",
  "Dijital Pazarlama Şirketi",
  "Basılı Reklam Ürünleri Satan Firmalar",
  "Arabuluculuk Hizmeti",
  "Vergi Danışmanlık Ofisi",
  "Göçmenlik Danışmanlık Firması",
  "Patent ve Marka Danışmanlık Şirketi",
  "Robotik ve Kodlama Eğitim Merkezi",
  "Özel Ders Veren Kurum",
  "Eğitim Materyali Satıcısı",
  "Sertifikalı Eğitim Programları",
  "Giyim Butikleri",
  "Moda Tasarım Atolyesi",
  "Kumaş Mağazası",
  "Ünlü Markaların Mağazası",
  "Doğa ve Outdoor Aktiviteler",
  "Dağcılık ve Kamp Malzemeleri Satan Mağaza",
  "Trekking ve Doğa Rehberleri",
  "Outdoor Sporlar Eğitim Merkezi",
  "Doğa Fotoğrafçılığı Kulübü",
  "Eğlence Teknolojisi",
  "Konsol Oyun Mağazası",
  "VR (Sanal Gerçeklik) Oyun Salonu",
  "E-spor Turnuva Organizasyonları",
  "Sanat ve Tasarım",
  "Sanat Atolyesi",
  "Çerçeveleme Hizmeti",
  "Heykel Stüdyosu",
  "El Sanatları Mağazası",
  "Dijital Sanat Üretim Ofisi",
  "Toplum ve Yardımlaşma",
  "Sosyal Yardım Vakıfları",
  "Gıda Bankaları",
  "Kadın Dayanışma Merkezi",
  "Hayvan Hakları Derneği",
  "Hayvan Yem ve Ekipman Satıcısı",
  "Süt ve Süt Ürünleri İşletmesi",
  "Ziraat Mühendislik Hizmeti",
  "Denizcilik ve Balıkçılık",
  "Liman Hizmeti",
];
