part of 'jobs.dart';

final List<String> _jobsPart3 = <String>[
  "Tekne Kiralama Firması",
  "Deniz Malzemeleri Satıcısı",
  "Balıkçılık Teknolojisi Firması",
  "Su Sporları Kulübü",
  "Kültür ve Eğlence",
  "Kitap ve Kütüphane Hizmeti",
  "Müzik ve Enstrüman Mağazası",
  "Tiyatro ve Performans Grupları",
  "Film ve Dizi Çekim Ajansı",
  "Finansal Hizmetler",
  "Finans Teknolojisi (FinTech) Şirketi",
  "Altın Alım-Satım Firması",
  "Kredi Danışmanlık Şirketi",
  "Leasing Şirketi",
  "İklim ve Çevre",
  "Geri Dönüşüm Tesisi",
  "Atık Yönetimi Şirketi",
  "Çevre Dostu Ürün Satıcısı",
  "Ekolojik Eğitim Merkezi",
  "Uluslararası Hizmetler",
  "Yurt Dışı Eğitim Danışmanlık Firması",
  "Çeviri ve Tercüme Bürosu",
  "Uluslararası Taşımacılık Firması",
  "Kültürel Etkinlik Organizatörleri",
  "Ticaret ve Perakende",
  "Outlet Mağazası",
  "Züccaciye ve Ev Eşyası Mağazası",
  "İkinci El Mağazası",
  "Saat ve Takı Mağazası",
  "Tuhafiyeler",
  "Eğlence ve Hobi",
  "Hobi Mağazası (Model Yapımı, El İşi, vb.)",
  "Kitap Kulübü",
  "Video Oyun Kiralama ve Satış Noktası",
  "Paintball Alanı",
  "Sanal Gerçeklik Merkezi",
  "Dans ve Tiyatro Grupları",
  "Özel Hizmetler",
  "Organizasyon Şirketi (Düğün, Davet, vb.)",
  "Kına ve Nişan Hazırlık Hizmeti",
  "Fotoğraf ve Video Çekim Hizmeti",
  "Mezarlık Bakım ve Çiçek Hizmeti",
  "Özel Şoför Hizmeti",
  "Teknoloji ve Elektronik",
  "Drone Satıcısı ve Eğitim Merkezi",
  "Bilgisayar ve Laptop Satıcısı",
  "Yazılım Geliştirme Firması",
  "İnternet ve Ağ Hizmeti Sağlayıcısı",
  "Akıllı Ev Sistemleri Firması",
  "Eğitim ve Araştırma",
  "Araştırma ve Geliştirme (AR-GE) Merkezi",
  "Öğrenci Etüt Merkezi",
  "Öğrenci",
  "Bilim ve Teknoloji Müzesi",
  "Deney Atolyesi",
  "Eğitim Yayıncılık Şirketi",
  "Spor ve Aktivite",
  "Spor Ekipmanları Satıcısı",
  "Profesyonel Spor Akademisi",
  "Kayak ve Kış Sporları Merkezi",
  "Atletizm ve Koşu Parkurları",
  "Evcil Hayvan ve Hayvan Sağlığı",
  "Veteriner Klinikleri",
  "Köpek Eğitim Merkezi",
  "Akvaryum Malzemeleri Satıcısı",
  "Tarım ve Kırsal Hizmetler",
  "Zirai İlaç ve Gübre Satıcısı",
  "Kümes Hayvancılığı Malzemeleri Satıcısı",
  "Tarım Makineleri Bayisi",
  "Organik Pazarlar",
  "Kooperatifler ve Tarımsal Üretim Tesisi",
  "Ulaşım ve Taşımacılık",
  "Nakliyat ve Lojistik Firması",
  "Yüksek Hızlı Tren İstasyonu",
  "Şehirler Arası Taşımacılık Firması",
  "Araç Muayene İstasyonu",
  "Kamu ve Resmi Hizmetler",
  "Tapu Kadastro Müdürlüğü",
  "Adliye",
  "Sosyal Hizmet Merkezi",
  "Askerlik Şubesi",
  "Moda ve Stil",
  "Moda Evleri",
  "Haute Couture Tasarım Stüdyosu",
  "Kiralık Kıyafet Hizmeti",
  "Aksesuar Tasarım Mağazası",
  "Saç ve Makyaj Stüdyosu",
  "Hurdacılar ve Geri Dönüşümcüler",
  "Hurda Araç Alım Satım Noktası",
  "Antikacılar",
  "Nostalji Ürünleri Mağazası",
  "Geçici Depolama Hizmeti",
  "İnşaat ve Dekorasyon",
  "Prefabrik Yapı Üreticisi",
  "Mermer ve Granit Satıcısı",
  "İnşaat Proje Danışmanlık Firması",
  "Parke ve Zemin Kaplama Mağazası",
  "Dekoratif Aydınlatma Mağazası",
  "Gıda Üretimi ve İşleme",
  "Süt ve Süt Ürünleri Üreticisi",
  "Unlu Mamul Fabrikası",
  "Meşrubat ve İçecek Üreticisi",
  "Konserve ve Hazır Yemek Üreticisi",
  "Şekerleme ve Çikolata Fabrikası",
  "Baharat İşleme Tesisi",
  "Doğa ve Çevre Hizmeti",
  "Peyzaj ve Bahçe Düzenleme Şirketi",
  "Çevre Danışmanlık Hizmeti",
  "Doğa Rehberliği Firması",
  "Ekolojik Ürün Mağazası",
  "Bitki ve Çiçek Yetiştiricileri",
  "Doğalgaz Şirketi",
  "Akaryakıt İstasyonu",
  "Yenilenebilir Enerji Danışmanlık Firması",
  "Enerji Depolama Sistemleri Tedarikçileri",
  "Isı Yalıtım ve Enerji Verimliliği Uzmanları",
  "Emlak ve Gayrimenkul",
  "Konut ve İş Yeri Kiralama Firması",
  "Toplu Konut Projeleri Üreticisi",
  "Arsa ve Tarla Satış Ofisi",
  "Kentsel Dönüşüm Proje Danışmanlık Firması",
  "Televizyon Kanalı",
  "Gazete ve Dergi Ofisi",
  "Çevrim İçi İçerik Üretim Platformu",
  "Reklam Film Çekim Stüdyosu",
  "Spor ve Rekreasyon",
  "Fitness ve Wellness Merkezi",
  "Açık Hava Spor Tesisi",
  "Golf Kulübü",
  "Yüzme Havuzu ve Aquapark",
  "Binicilik Merkezi",
  "Kültürel Etkinlikler ve Sanat",
  "Sergi ve Galeri Mekanı",
  "Halk Eğitim Merkezi",
  "Geleneksel El Sanatları Atolyesi",
  "Uluslararası Film ve Sanat Festivalleri",
  "Yat Üretim ve Satış Firması",
  "Dalış Kursları ve Merkezi",
  "Rüzgar Sörfü Eğitim Alanı",
  "Balıkçılık Malzemeleri Satıcısı",
  "Çocuk ve Eğitim",
  "Kreş ve Gündüz Bakım Evleri",
  "Çocuk Etkinlik Merkezi",
  "Zekâ Geliştirme Oyuncakları Mağazası",
  "Özel Eğitim ve Rehabilitasyon Merkezi",
  "Çocuk Festivalleri Organizasyonları",
  "Gelinlik ve Abiye Mağazası",
  "Damatlık ve Erkek Giyim Butikleri",
  "Çocuk Giyim Mağazası",
  "Spor Giyim Mağazası",
  "Kışlık Giysi ve Ayakkabı Satıcısı",
  "Güvenlik ve Koruma",
  "CCTV Kamera ve Alarm Sistemleri Satıcısı",
  "Yangın Söndürme Ekipmanları Mağazası",
  "Risk Yönetimi ve Güvenlik Danışmanlıkları",
  "Çelik Kapı ve Güvenlik Sistemleri Üreticisi",
  "Lojistik ve Depolama",
  "Uluslararası Kargo Firması",
  "Soğuk Hava Depoları",
  "Depolama ve Stoklama Hizmeti",
  "Taşımacılık ve Nakliyat Şirketi",
  "Kargo Dağıtım Şubesi",
  "Lojistik Danışmanlık Firması",
  "Zanaat ve El Sanatları",
  "Deri İşleme Atolyesi",
  "Halı Dokuma Atolyesi",
  "Marangozlar ve Ahşap İşleme Atolyesi",
  "Takı ve Mücevher Tasarım Atolyesi",
  "Teknoloji ve Yazılım",
  "Web Tasarım ve SEO Hizmeti",
  "Veri Analitik ve Bulut Bilişim Şirketi",
  "Oyun Geliştirme Stüdyosu",
  "Yapay Zeka ve Robotik Çalışma Merkezi",
  "Tohum ve Fide Satıcısı",
  "Büyükbaş ve Küçükbaş Hayvan Çiftlikleri",
  "Organik Yumurta ve Süt Üreticisi",
  "Modern Sera Sistemleri Üreticisi",
  "Hayvan Bakım Ürünleri Tedarikçileri",
  "Toptan ve Ticaret",
  "Toptancı Hal ve Depolar",
  "Gıda Toptancısı",
  "Elektrik ve Elektronik Ürün Toptancısı",
  "İnşaat Malzemesi Toptancısı",
  "Kimyasal Ürün Toptancısı",
  "Yol ve Köprü İnşaat Firması",
  "Baraj ve HES Proje Yapan Şirket",
  "İleri Teknoloji Altyapı Firması",
  "Kentsel Yenileme ve Restorasyon Şirketi",
  "İnşaat Mühendislik Danışmanlık Hizmeti",
  "Sağlık ve Medikal",
  "Tıbbi Cihaz Satıcısı",
  "Medikal Sarf Malzeme Tedarikçileri",
  "Ambulans Hizmeti",
  "Sağlık Turizmi Acentesi",
  "Yaşlı ve Hasta Bakım Evleri",
  "Plastik Geri Dönüşüm Tesisi",
  "Elektronik Atık İşleme Merkezi",
  "Kağıt ve Karton Geri Dönüşümcüler",
  "Doğal Enerji Kaynakları Araştırma Firması",
  "Çevre Eğitim ve Bilinçlendirme Programları",
  "İletişim ve Telekomünikasyon",
  "Uydu ve Anten Hizmeti",
  "Çağrı Merkezi Hizmeti",
  "Telefon Tamir ve Teknik Destek Noktası",
  "Fiber Optik Altyapı Hizmeti",
  "Eğitim ve Akademik",
  "STEM Eğitim Merkezi",
  "Özel Akademik Araştırma Enstitüleri",
  "Eğitim Materyali ve Teknolojisi Sağlayıcısı",
  "Üniversite ve Mezun Derneği",
  "Eğlence ve Organizasyon",
  "Ses ve Işık Sistemleri Kiralama Hizmeti",
  "Parti Malzemeleri Mağazası",
  "Konser ve Etkinlik Mekanı",
  "Organizasyon Danışmanlık Firması",
  "Turizm ve Seyahat",
  "Doğa ve Macera Turları Düzenleyen Firmalar",
  "Kültür Turları Organizatörleri",
  "Kaplıca ve Termal Tesisler",
  "Kamp ve Karavan Hizmeti Sağlayan Şirket",
  "Zeytinyağı ve Zeytin İşleme Tesisi",
  "Dondurma ve Tatlı Üreticisi",
  "Kurutulmuş Meyve ve Ceviz İşleme Tesisi",
  "Alkollü ve Alkolsüz İçecek Üreticisi",
  "Baharat ve Bitki Çayı Paketleme Firması",
  "El Sanatları ve Zanaat",
  "Seramik ve Porselen Atolyesi",
  "Ahşap Oyma ve Mobilya Üreticisi",
  "Dokuma ve İplik Üreticisi",
  "Geleneksel Takı Tasarımı ve Üretimi",
  "Minyatür ve Hat Sanatı Atolyesi",
  "Satış Ofisi",
  "Arsa ve Tarla Danışmanlık Firması",
  "Emlak Yönetim Şirketi",
  "Kiralama ve Taahhüt Firması",
  "Kat Mülkiyeti ve Site Yönetim Hizmeti",
  "Güneş Paneli Üreticisi ve Montaj Firması",
  "Elektrik Dağıtım ve Üretim Firması",
  "Rüzgar Türbini Üreticisi",
  "Biyogaz ve Atık Yönetimi Tesisi",
  "Hidroelektrik Santral (HES) İşletmesi",
  "İmalat ve Üretim",
  "Metal İşleme ve Kaynak Atolyesi",
  "Otomotiv Parça Üreticisi",
  "Plastik Kalıp ve Enjeksiyon Fabrikası",
  "Kimyasal Ürün Üreticisi",
  "Ambalaj ve Paketleme Tesisi",
  "Dijital Hizmetler",
  "Çevrim İçi Eğitim Portalları",
  "E-ticaret Danışmanlık Firması",
  "SEO ve Dijital Reklam Ajansı",
  "Mobil Uygulama Geliştirme Şirketi",
  "Video Üretim ve Yayın Hizmeti",
  "Sanayi ve Altyapı",
  "Ağır Makine Üreticisi",
  "Endüstriyel Bakım ve Onarım Firması",
  "Boru ve Çelik İşleme Fabrikası",
  "Fabrika ve Depo İnşaat Şirketi",
  "Endüstriyel Yedek Parça Tedarikçileri",
  "Tarım ve Gıda İşletmesi",
  "Fidanlıklar ve Bahçe Malzemeleri Satıcısı",
  "Büyükbaş Hayvancılık Çiftlikleri",
  "Organik Ürün Kooperatifi",
  "Balık Üretme ve İşleme Tesisi",
  "Modern Seracılık Teknolojisi Sağlayıcısı",
  "Eğitim ve Akademik Hizmetler",
  "Dil Eğitim Merkezi",
  "Burs Veren Vakıf ve Kurum",
  "Akademik Yayın ve Kitapçılar",
  "Sınav Hazırlık Kursları",
  "Online Ders ve Ödev Platformu",
  "Sosyal ve Toplum Hizmeti",
  "Yaşlı Bakım ve Rehabilitasyon Merkezi",
  "Psikolojik Danışmanlık Hizmeti",
  "Kadın Sığınma Evleri",
  "Çocuk Esirgeme ve Koruma Kuruluşu",
  "Engelli Destek ve Eğitim Merkezi",
  "Spor ve Fiziksel Aktivite",
  "Kapalı Spor Salonu",
  "Bireysel Antrenör Hizmeti",
  "Doğa Sporları Organizasyonları",
  "Su Sporları Eğitmenleri",
  "Esneklik ve Yoga Stüdyosu",
  "Spor Ayakkabı Mağazası",
  "Vintage ve İkinci El Giyim Butikleri",
  "Çanta ve Aksesuar Satıcısı",
  "Özel Sipariş Giyim Tasarımcıları",
  "Tekstil Boyama ve Tamir Atolyesi",
  "Medya ve Sanat",
  "İnfluencer ve İçerik Üretim Ajansı",
  "Belgesel ve Film Prodüksiyon Şirketi",
  "Grafik Tasarım ve Animasyon Atolyesi",
  "Dijital Sanat Üretim Stüdyosu",
  "Kamu Hizmeti",
  "Belediye Hizmeti (Parklar, Temizlik, vb.)",
  "Postaneler",
  "Elektrik ve Su İdaresi Şubesi",
  "Tapu ve Kadastro Müdürlüğü",
  "Sosyal Güvenlik Kurumu",
  "Bungalov ve Dağ Evleri",
  "Şehir Turları Düzenleyen Firmalar",
  "Tarihi Mekanlar ve Rehberlik Hizmeti",
  "Butik Oteller ve Misafirhaneler",
  "Kamp ve Karavan Kiralama Hizmeti",
  "Şehir İçi Minibüs ve Otobüs Kooperatifi",
  "Özel Limuzin ve VIP Araç Kiralama Hizmeti",
  "Helikopter ve Özel Jet Kiralama Şirketi",
  "Otobüs Terminalleri ve Seyahat Acentesi",
  "Finans ve Sigorta",
  "Sigorta Brokerleri ve Acentesi",
  "Finansal Danışmanlık Hizmeti",
  "Yatırım Şirketi",
  "Leasing ve Finansal Kiralama Firması",
  "Kredi Kartı Hizmeti Sunan Kurum",
  "Sağlık ve Alternatif Tıp",
  "Diş Sağlığı ve Estetik Merkezi",
  "Akupunktur ve Refleksoloji Merkezi",
  "Estetik ve Plastik Cerrahi Klinikleri",
  "Spa ve Termal Tedavi Merkezi",
  "Beslenme ve Diyet Danışmanlık Merkezi",
  "Eğitim ve Öğretim",
  "Kodlama ve Yazılım Kursları",
  "Robotik ve STEM Atolyesi",
  "Online Sınav ve Sertifika Platformu",
  "Resim ve Müzik Kursları",
  "Çocuk Gelişim Atolyesi",
  "Doğa ve Çevre",
  "Doğa Koruma ve Araştırma Derneği",
  "Milli Parklar ve Koruma Alanı",
  "Çevre ve Atık Yönetimi Danışmanlık Firması",
  "Topluluk Bahçeciliği Girişimleri",
  "Enerji Verimliliği Eğitim ve Denetim Hizmeti",
  "Kültürel Hizmetler",
  "Dil ve Kültür Merkezi",
  "Ulusal ve Uluslararası Fuar Organizatörleri",
  "Kültürel Miras Restorasyon Şirketi",
  "Geleneksel Müzik ve Dans Grupları",
  "Şehir Tiyatroları ve Opera Binaları",
  "Hobi ve Eğlence",
  "Drone Uçuş Alanı ve Eğitmenleri",
  "Hobi Bahçeleri Kiralama Hizmeti",
  "Elektrikli Scooter ve Bisiklet Kiralama Şirketi",
  "Koleksiyon ve Antika Satış Mağazası",
  "Hobi Malzemeleri ve Kit Mağazası",
  "Hukuk Bürosu ve Avukatlar",
  "Arabuluculuk ve Alternatif Çözüm Merkezi",
  "İş ve Ticaret Hukuku Danışmanlık Hizmeti",
  "Fikri Mülkiyet ve Patent Hizmeti",
  "Göçmenlik ve Vize Danışmanlık Ofisi",
  "Arıcılık ve Bal Üretim Çiftlikleri",
  "Tavuk Çiftlikleri ve Yumurta Üretim Tesisi",
  "Zirai Danışmanlık Hizmeti",
  "Hayvan Yem Üreticisi",
  "Sulama Sistemleri Üreten Firmalar",
  "Elektronik ve Teknoloji",
  "Cep Telefonu Tamir ve Teknik Servis Noktası",
  "Oyun Konsolu ve Aksesuar Satıcısı",
  "Güvenlik Yazılımı Geliştiren Firmalar",
  "Akıllı Teknolojiler ve IoT Sistemleri Sağlayıcısı",
  "Güzellik ve Bakım",
  "Kozmetik ve Kişisel Bakım Mağazası",
  "Lazer Epilasyon ve Cilt Bakım Merkezi",
  "Saç Ekimi ve Tedavi Klinikleri",
  "Güzellik Yarışmaları ve Organizasyon Firması",
  "Profesyonel Temizlik Şirketi",
  "Haşere Kontrol ve İlaçlama Hizmeti",
  "Kombi ve Klima Bakım Servisi",
  "Ev Eşyası Kiralama Hizmeti",
  "Eğlence ve Etkinlik Organizasyonu",
  "Düğün ve Nişan Organizasyon Şirketi",
  "Çocuk Doğum Günü ve Animasyon Hizmeti",
  "Kına Gecesi ve Geleneksel Etkinlik Organizasyonları",
  "Festival ve Konser Bilet Satış Noktası",
  "İnşaat ve Taşımacılık",
  "Vinç Kiralama Hizmeti",
  "Tünel ve Metro İnşaat Firması",
  "Yalıtım ve Mantolama Şirketi",
  "Prefabrik Yapı İnşa Eden Şirket",
  "Yol ve Otoyol İnşaat Şirketi",
  "Denizcilik ve Lojistik",
  "Gemi ve Tekne Kiralama Hizmeti",
  "Marina ve Yat Limanları",
  "Deniz Taşımacılığı Firması",
  "Balıkçılık ve Deniz Ürünleri İşleme Merkezi",
  "Yat Yapımı ve Bakımı Hizmeti",
  "Evcil Hayvan ve Veterinerlik",
  "Pet Shop ve Hayvan Malzemeleri Satıcısı",
  "Evcil Hayvan Oteli",
  "Veteriner Klinik ve Hastaneleri",
  "Hayvan Eğitimi ve Davranış Danışmanlıkları",
  "Sokak Hayvanları Koruma ve Tedavi Merkezi",
  "Oto Yıkama ve Detaylı Temizlik Servisi",
  "Araç Kaplama ve Modifiye Atolyesi",
  "İkinci El Araç Galerileri",
  "Oto Kiralama Hizmeti",
  "Lastik Değişimi ve Tamir Servisi",
  "Ambalaj ve Etiketleme Firması",
  "Gıda İşleme Makinaları Üreticisi",
  "Çelik Konstrüksiyon ve Fabrika Binaları Üretimi",
  "Endüstriyel Ekipman ve Makine Tedarikçileri",
  "Cam ve Plastik Ürün Üretim Fabrikası",
  "Turizm ve Rekreasyon",
  "Kayak Merkezi ve Tesisi",
  "Tarihi Yerler ve Rehberlik Hizmeti",
  "Macera Parkları ve Zipline Alanı",
  "Eko Turizm ve Doğa Yürüyüşleri Organizasyonları",
  "Tekne Turları ve Su Sporları Hizmeti",
  "Finans ve Ekonomi",
  "Kripto Para Danışmanlık Hizmeti",
  "Bankacılık ve Finans Teknolojileri Firması",
  "Mikro Kredi Sağlayan Kurum",
  "Risk Yönetimi ve Portföy Danışmanlık Şirketi",
  "Özel Dikim Moda Evleri",
  "Tişört ve Promosyon Ürünleri Üreticisi",
  "Kumaş ve Tekstil Ürünleri Mağazası",
  "Ayakkabı ve Deri Ürünleri Atolyesi",
  "Ünlü Tasarımcı Mağazası",
  "Gıda ve Restoranlar",
  "Vegan ve Vejetaryen Restoranlar",
  "Gurme Yemek Lokantası",
  "Pastane ve Tatlıcılar",
  "Kahve Dükkanları ve Kafeler",
  "Eğlence ve Medya",
  "Sinema ve Film Prodüksiyon Stüdyosu",
  "İnfluencer ve Sosyal Medya Ajansı",
  "Online Yayın ve Video Platformu",
  "Video Kurgu ve Animasyon Hizmeti",
  "Dijital İçerik Üretim Atolyesi",
  "Bahçe ve Peyzaj",
  "Bahçe Düzenleme ve Çim Alan Hizmeti",
  "Bitki ve Çiçek Satış Mağazası",
  "Peyzaj Mimarlığı Danışmanlık Hizmeti",
  "Bahçe Mobilyaları ve Dekorasyon Ürünleri",
  "Sulama Sistemleri Montaj Hizmeti",
  "Bilgi Teknolojileri",
  "Siber Güvenlik Danışmanlık Şirketi",
  "Blockchain ve Kripto Yazılım Firması",
  "E-Ticaret Platform Sağlayıcısı",
  "Veri Merkezi ve Hosting Hizmeti",
  "IT ve Teknoloji Eğitim Firması",
  "Ziraat ve Gıda Teknolojileri",
  "Modern Sulama Teknolojisi Sağlayıcısı",
  "Tarım Makineleri Üreticisi",
  "Gıda Kalite ve Güvenlik Kontrol Laboratuvarları",
  "Tarımsal İlaç ve Gübre Satıcısı",
  "Organik Tarım Ürünleri Marketi",
  "Kişisel Gelişim ve Danışmanlık",
  "Hayat Koçluğu ve Kişisel Gelişim Merkezi",
  "Aile ve Evlilik Danışmanlık Hizmeti",
  "Stres Yönetimi ve Zihin Haritalama Atolyesi",
  "NLP (Neuro-Linguistic Programming) Eğitim Merkezi",
  "Çocuk ve Gençlik Gelişim Merkezi",
  "Yüzme Havuzları ve Kulübü",
  "Profesyonel Antrenörler ve Spor Eğitimcileri",
  "Spor Takımları için Tesisler ve Akademiler",
  "Açık Hava Fitness Parkurları",
  "Tenis ve Golf Sahaları",
  "Dayanıklı Tüketim ve Elektrikli Aletler",
  "Elektronik Ürün Servis ve Satış Noktası",
  "Beyaz Eşya Bayisi ve Servisi",
  "Akıllı Ev Sistemleri Satış Noktası",
  "Ev Sinema ve Ses Sistemleri Üreticisi",
  "Küçük Ev Aletleri Tamir Hizmeti",
  "Mühendislik ve Proje Hizmeti",
  "Mekanik Tesisat ve HVAC Danışmanlık Firması",
  "Jeolojik ve Topografik Araştırma Şirketi",
  "Mimarlık ve Tasarım Ofisi",
  "Bina Enerji Verimliliği Danışmanlık Firması",
  "İnşaat Malzemesi Test ve Denetim Laboratuvarları",
  "CCTV Kamera ve Güvenlik Sistemleri Sağlayıcısı",
  "Alarm ve Yangın Güvenliği Firması",
  "Güvenlik Eğitim ve Sertifikasyon Merkezi",
  "Kasa ve Güvenlik Ekipmanları Üreticisi",
  "Hukuk ve Adalet",
  "Tercüme ve Hukuki Çeviri Ofisi",
  "Uluslararası Hukuk Danışmanları",
  "Adli Bilişim ve Dijital Delil Analiz Merkezi",
  "Vergi ve Ticaret Hukuku Uzmanları",
  "Sözleşme Hazırlama ve Danışmanlık Hizmeti",
  "Akıllı Tahta ve Eğitim Cihazı Üreticisi",
  "Dijital Eğitim İçeriği Sağlayıcısı",
  "Online Eğitim ve Webinar Platformu",
  "Simülasyon Eğitim ve VR Teknolojisi Üreticisi",
  "Üniversite ve Okul Laboratuvar Sistemleri Sağlayıcısı",
  "Taşımacılık ve Ulaştırma",
  "Hızlı Tren ve Metro Proje Şirketi",
  "Kargo İzleme ve Yönetim Sistemleri",
  "Lojistik Depo ve Nakliye Şirketi",
  "Özel Yolcu Taşımacılığı Hizmeti",
  "Uluslararası Deniz ve Hava Taşımacılığı Firması",
  "Kozmetik ve Moda",
  "Profesyonel Kuaför ve Makyaj Sanatçıları",
  "Kozmetik Ürün Test ve Üretim Firması",
  "Kişisel Stil ve Moda Danışmanları",
  "Parfüm ve Koku Ürünleri Üreticisi",
  "Özel Dikim Gelinlik ve Abiye Atolyesi",
  "Eğlence ve Oyun",
  "Çevrim İçi ve Masaüstü Oyun Mağazası",
  "Escape Room ve Macera Evleri",
  "Sanal Gerçeklik Oyun Merkezi",
  "Çocuk Eğlence Parkları ve Trambolin Alanı",
  "Turnuva ve Espor Organizasyonları",
  "Rüzgar ve Güneş Enerjisi Danışmanlık Firması",
  "Yeşil Bina Sertifikasyon Hizmeti",
  "İklim Değişikliği Araştırma Merkezi",
  "Atık Su Yönetimi ve Arıtma Sistemleri",
  "Karbon Ayak İzi Azaltma Proje Danışmanlıkları",
  "Mobilya ve Dekorasyon",
  "Özel Mobilya Tasarım Atolyesi",
  "Ofis Mobilyası Üreticisi",
  "Perde ve Döşemelik Kumaş Satıcısı",
  "Ev Dekorasyon Aksesuar Mağazası",
  "Ahşap ve Metal Dekor Ürünleri Üreticisi",
  "İletişim ve Medya",
  "Halkla İlişkiler ve İletişim Danışmanlık Şirketi",
  "Radyo ve Podcast Yayıncıları",
  "Dijital İçerik Platformu",
  "Gazete ve Dergi Yayıncıları",
  "Robotik Kodlama ve STEM Eğitim Merkezi",
  "Satranç ve Zeka Oyunları Kursları",
  "Çocuk Tiyatrosu ve Sanat Atolyesi",
  "Sertifika Programı Sunan Eğitim Kurumu",
  "Özel Depolama Alanı Kiralama Şirketi",
  "Paketleme ve Lojistik Firması",
  "Ağır Yük ve Proje Lojistik Şirketi",
  "Liman Hizmeti ve Nakliye Firması",
  "Asansör ve Yürüyen Merdiven Üreticisi",
  "Çatı ve İzolasyon Malzemeleri Tedarikçileri",
  "Prefabrik ve Modüler Yapı Firması",
  "Beton ve İnşaat Malzemeleri Satıcısı",
  "Yapı Denetim ve Proje Yönetim Firması",
  "Gıda ve Tarım Ürünleri",
  "Yerel Üretici Pazarları",
  "Zeytinyağı ve Doğal Ürün Satış Noktası",
  "Hububat ve Bakliyat Üreticisi",
  "Tarım Ekipmanları Satış ve Tamir Hizmeti",
  "Tohum ve Fidan Üreticisi",
  "Rehabilitasyon Cihazları Üreticisi",
  "Medikal Ekipman ve Malzeme Tedarikçileri",
  "Psikoterapi ve Grup Terapi Hizmeti",
  "Sağlık Teknolojileri Geliştiren Şirket",
  "Diyabet ve Kronik Hastalık Yönetim Hizmeti",
  "Açık Hava Spor Ekipmanları Satıcısı",
  "Sporcu Besin ve Takviye Ürünleri Mağazası",
  "Yoga ve Meditasyon Eğitim Merkezi",
  "Koşu ve Bisiklet Kulübü",
  "Spor Kompleksleri ve Çok Amaçlı Salonlar",
  "Konaklama ve Tatil",
  "Glamping (Lüks Kamp) Tesisi",
  "Tatil Köyleri ve Yazlık Ev Kiralama Hizmeti",
  "Aileye Yönelik Tatil Alanı",
  "Deniz ve Dağ Tatil Organizatörleri",
  "Kültür Turu ve Gezi Firması",
  "Sanayi ve Teknoloji",
  "3D Yazıcı Üreticisi ve Hizmeti",
  "Endüstriyel Robot Üreticisi",
  "İleri Malzeme ve Nanoteknoloji Şirketi",
  "Veri Analizi ve Büyük Veri Çözümleri Sağlayıcısı",
  "Elektronik Devre ve Çip Üreticisi",
  "Toplum Hizmeti",
  "Kan Bağışı ve Organ Nakli Merkezi",
  "Kriz Merkezi ve Acil Yardım Hatları",
  "Gönüllü ve Sivil Toplum Kuruluşu",
  "Toplum Merkezi ve Gençlik Programları",
  "Bağımlılık Tedavi ve Rehabilitasyon Merkezi",
  "Moda ve Tasarım",
  "Tekstil Baskı ve Desen Tasarım Atolyesi",
  "Moda Fotoğrafçılığı Stüdyosu",
  "Özel Ayakkabı ve Çanta Tasarımcıları",
  "Takı Tasarım ve Üretim Firması",
  "Moda Show ve Defile Organizasyonları",
  "Eğlence ve Teknoloji",
  "Sanal Gerçeklik Oyun Salonu",
  "Oyun Konsolu ve VR Cihaz Satış Noktası",
  "İnteraktif Sergi ve Etkinlik Organizatörleri",
  "Çevrim İçi Film ve Dizi Platformu",
  "Mobil Oyun Geliştirme Şirketi",
  "Sosyal ve Toplumsal Hizmetler",
  "Yaşlı Bakım ve Huzurevi Hizmeti",
  "Kadın Sığınma ve Destek Merkezi",
  "Çocuk Esirgeme ve Rehabilitasyon Kurumu",
  "Engelli Destek ve Danışmanlık Merkezi",
  "Sosyal Yardım ve Gıda Bankaları",
  "Yeme-İçme ve Konaklama Hizmeti",
  "Gurme Restoran ve Şarap Evleri",
  "Sokak Lezzetleri ve Mobil Yemek Araçları",
  "Çiftlikte Kahvaltı ve Yerel Lezzet Deneyimleri",
  "Butik Oteller ve Konuk Evleri",
  "Sanat ve Zanaat",
  "Seramik ve Cam Atolyesi",
  "Ahşap Oyma ve Marangoz Atolyesi",
  "Ebru Sanatı ve Kaligrafi Kursları",
  "Geleneksel El Sanatları ve Hediyelik Ürün Satıcısı",
  "Modern Sanat Galerileri ve Sergi Salonu",
  "Çevre ve Yenilenebilir Enerji",
  "Elektrikli Araç Şarj İstasyonu İşletmesi",
  "Atık Geri Dönüşüm ve Yeniden Kullanım Merkezi",
  "Güneş Paneli Üretim ve Montaj Şirketi",
  "Biyogaz ve Yeşil Enerji Üretim Firması",
  "Çevre Eğitim ve Bilinçlendirme Kuruluşu",
  "Bilişim ve Dijital Hizmetler",
  "Web Tasarım ve SEO Ajansı",
  "Dijital Pazarlama ve Sosyal Medya Danışmanlıkları",
  "Bulut Bilişim ve Veri Yedekleme Hizmeti",
  "Yapay Zeka ve Makine Öğrenimi Çözümleri",
  "Arsa ve Tarla Danışmanlık Hizmeti",
  "Lüks ve Premium Gayrimenkul Ajansı",
  "İnşaat Projesi Satış Ofisi",
  "Emlak Değerleme ve Danışmanlık Firması",
  "Konut ve Ticari Kiralama Ofisi",
  "Büyük Zincir Marketler",
  "Yerel Pazarlar ve Organik Ürün Satıcısı",
  "Kıyafet ve Aksesuar Mağazası",
  "Elektronik Cihaz Mağazası",
  "Oyuncak ve Çocuk Ürünleri Satıcısı",
  "Taşımacılık ve Dağıtım",
  "Uluslararası Nakliye ve Lojistik Firması",
  "Kurye ve Paket Teslim Hizmeti",
  "Özel Şoför Hizmeti Sağlayan Firmalar",
  "Hızlı Teslimat ve E-Ticaret Dağıtım Acentesi",
  "Demiryolu ve Hava Kargo Taşımacılığı",
  "Bilim ve Araştırma",
  "Teknoloji Geliştirme ve Araştırma Merkezi",
  "Bilim Müzesi ve Eğitim Atolyesi",
  "Laboratuvar Test ve Analiz Hizmeti",
  "Uzay Araştırmaları ve Teknoloji Şirketi",
  "Genetik ve Biyoteknoloji Geliştirme Firması",
  "Çocuk Eğlence Parkları ve Lunaparklar",
  "Su Parkları ve Akvaryumlar",
  "Açık Hava Sinemaları ve Tiyatrolar",
  "Kamp ve Doğa Yürüyüşü Organizasyonları",
  "Balon Turları ve Hava Sporları Merkezi",
  "Sağlık ve Wellness",
  "Alternatif Tıp ve Akupunktur Merkezi",
  "Spa ve Wellness Retreat Merkezi",
  "Sağlık Koçluğu ve Beslenme Danışmanlığı",
  "Hamam ve Geleneksel Banyo Hizmeti",
  "Fitness Stüdyosu ve Pilates Salonu",
  "Elektrik ve Doğalgaz Dağıtım Şirketi",
  "Biyodizel ve Yenilenebilir Yakıt Üreticisi",
  "Petrol ve Akaryakıt İstasyonu",
  "Enerji Tasarrufu Danışmanlık Firması",
  "Elektrik Üretim ve Dağıtım Tesisi",
];
