List<String> jobs = [
  "Sanatçı",
  "Müzisyen",
  "Avukat",
  "Ürün Hizmet",
  "Esnaf",
  "Giyim",
  "Dijital İçerik Üreticisi",
  "Video İçeriği Üreticisi",
  "Dijital Pazarlama Uzmanı",
  "Yazılım Mühendisi",
  "Eğitim",
  "Girişimci",
  "Sağlık/Güzellik",
  "Editör",
  "Yazar",
  "Kişisel",
  "Mühendis",
  "Doktor",
  "Yönetici",
  "Öğretmen",
  "Öğrenci",
  "3D Yazıcı Mağazası",
  "Acenta",
  "Acil Durum Yönetim Merkezi",
  "Acil Durum Yönetmeni",
  "Acil Tıp Teknisyeni",
  "Acil Tıp Uzmanı",
  "Açık Hava Konser Alanı",
  "Açık Hava Spor Etkinlik Alanı",
  "Açık Hava Tiyatroları",
  "Adli Tabip",
  "Adli Tıp Uzmanı",
  "Afet ve Acil Durum Yardım Merkezi",
  "Afet Yönetim Eğitim Merkezi",
  "Agronomist",
  "Ağ Yöneticisi",
  "Ahşap İşleme Atolyesi",
  "Ahşap Tekne Yapımcısı",
  "Aile Hekimi",
  "Ajans",
  "Akıllı Enerji Yönetim Sistemleri",
  "Akıllı Ev Sistemleri Satıcısı",
  "Akıllı Sera Sistemleri",
  "Akıllı Tarım Şirketi",
  "Akortçu",
  "Akrobat",
  "Aktar",
  "Aktör",
  "Aktris",
  "Aktüer",
  "Akustikçi",
  "Alarm ve Kamera Sistemleri",
  "Alışveriş Merkezi (AVM)",
  "Alışveriş ve Perakende",
  "Alışveriş ve Ticaret",
  "Alışveriş ve Tüketim",
  "Alternatif Sağlık ve Terapi",
  "Alternatif Tıp Merkezi",
  "Alternatif Tıp Uygulamaları",
  "Altın ve Değerli Maden Yatırımcıları",
  "Altyapı Teknolojileri",
  "Amatör Spor Kulübü",
  "Ambalajcı",
  "Ambarcı",
  "Ambulans Şoförü",
  "Anahtarcı",
  "Analist",
  "Anaokulu",
  "Anestezi Teknikeri",
  "Anestezi Uzmanı",
  "Animasyon Stüdyosu",
  "Animatör",
  "Anne-Baba Danışmanlık Merkezi",
  "Antika İşletme",
  "Antrenör",
  "Antropolog",
  "Apartman Yöneticisi",
  "Aqua Park",
  "Araba İşletme",
  "Araba Tamircisi",
  "Araba Yıkayıcısı",
  "Arabulucu",
  "Arabuluculuk Merkezi",
  "Araç Kiralama Firması",
  "Araç Kiralama Ofisi",
  "Araştırma Laboratuvarı",
  "Araştırma Merkezi",
  "Araştırmacı",
  "Arıcı",
  "Arıcılık İşletmesi",
  "Arkeolog",
  "Arkeoloji Derneği",
  "Armatör",
  "Arpist",
  "Arşivci",
  "Artist",
  "Asansörcü",
  "Asistan",
  "Asker",
  "Askeri Tedarikçiler",
  "Astrofizikçi",
  "Astrolog",
  "Astronom",
  "Astronot",
  "Aşçı",
  "Aşçıbaşı",
  "Atık Yönetimi Firması",
  "Atlet",
  "Av Bekçisi",
  "Avcı",
  "Avukat",
  "Ayakkabı Mağazası",
  "Ayakkabı Tamircileri",
  "Ayakkabı Tamircisi",
  "Ayakkabıcı",
  "Bacacı",
  "Badanacı",
  "Bağımsız İşletme",
  "Bağımsız Medya Destek Organizasyonları",
  "Baharatçı",
  "Baharatçılar",
  "Bahçe Bitkileri Uzmanı",
  "Bahçe Düzenleme Firması",
  "Bahçe Mobilyası Üreticisi",
  "Bahçe ve Tarım Aletleri",
  "Bahçıvan",
  "Bakan",
  "Bakıcı",
  "Bakımevleri",
  "Bakır ve Kalay İşletmecisi",
  "Bakırcı",
  "Bakkal",
  "Bakkallar",
  "Bakteriyolog",
  "Balerin",
  "Balık Lokantası",
  "Balıkçı Barınakları",
  "Balıkçı",
  "Balıkçılık Kooperatifi",
  "Balıkçılık Şirketi",
  "Balon Pilotu",
  "Banka",
  "Bankacı",
  "Bankacılık ve Finans",
  "Bankalar",
  "Banker",
  "Barmeyd",
  "Basketbolcu",
  "Başhemşire",
  "Başkan",
  "Bebek Bakıcısı",
  "Bebek Bakım Hizmeti",
  "Bebek Ürünleri Mağazası",
  "Bekçi",
  "Belediye Başkanı",
  "Belediye Meclisi Üyesi",
  "Belediyeler",
  "Benzin İstasyonu",
  "Benzinci",
  "Berber",
  "Besicilik",
  "Besteci",
  "Beyaz Eşya Bayisi",
  "Bilardo Salonu",
  "Biletçi",
  "Bilgi İşlemci",
  "Bilgisayar Mühendisi",
  "Bilgisayar Programcısı",
  "Bilgisayar Tamircisi",
  "Bilgisayar Teknisyeni",
  "Bilim İnsanı",
  "Bilim Merkezi",
  "Bilim ve Teknoloji",
  "Bilirkişi",
  "Bilişim Sistemleri Mühendisi",
  "Binicilik",
  "Bisiklet Mağazası",
  "Bisikletçi",
  "Biyografi Yazarı",
  "Biyolog",
  "Biyolojik Çeşitlilik Araştırma Merkezi",
  "Biyomedikal Mühendisi",
  "Biyoyakıt Üretim Şirketi",
  "Bobinajcı",
  "Borsacı",
  "Botanikçi",
  "Bowling Salonu",
  "Boya ve Badana İşletmesi",
  "Boya ve Dekorasyon Mağazası",
  "Boyacı",
  "Bozacı",
  "Bölgesel Kalkınma Ajansı",
  "Börekçi",
  "Broker",
  "Bulaşıkçı",
  "Buldozer Operatörü",
  "Butik Oteller",
  "Butik",
  "Büfeler",
  "Bütçe Uzmanı",
  "Büyükelçi",
  "Büyükelçilik",
  "Cam Üfleme Atolyesi",
  "Cam ve Plastik Toplama Noktası",
  "Camcı",
  "Camiler",
  "Canlı Müzik Mekanı",
  "Canlı Yayın Platformu",
  "Catering Şirketi",
  "Celep",
  "Cellat",
  "Cem Evleri",
  "Cep Telefonu Mağazası",
  "Cerrah",
  "Cost Control",
  "Çalışma Alanı Kiralama Hizmeti",
  "Çamaşırcı",
  "Çamaşırhane",
  "Çamaşırhaneler",
  "Çanta ve Aksesuar Mağazası",
  "Çantacı",
  "Çarkçı",
  "Çatıcı",
  "Çaycı",
  "Çevirmen",
  "Çevre Danışmanlık Firması",
  "Çevre Koruma Derneği",
  "Çevre Mühendisi",
  "Çevre Teknolojileri Geliştiren Firmalar",
  "Çevre Temizlik Hizmeti",
  "Çevre ve Geri Dönüşüm",
  "Çevre ve İklim Çözümleri",
  "Çevre ve Peyzaj",
  "Çevrebilimci",
  "Çevrim İçi Mentorluk Hizmeti",
  "Çevrim İçi Sertifika Programları",
  "Çeyizci",
  "Çıkıkçı",
  "Çıkrıkçı",
  "Çımacı",
  "Çırak",
  "Çiçekçi",
  "Çiçekçiler",
  "Çiftçi",
  "Çiftlik İşletici",
  "Çiftlikler",
  "Çiğ Köfteciler",
  "Çikolatacı",
  "Çilingir",
  "Çilingirler",
  "Çim Biçme ve Peyzaj Ekipmanları Mağazası",
  "Çim Tohumu ve Peyzaj Hizmeti",
  "Çinici",
  "Çitçi",
  "Çoban",
  "Çocuk Bakım Merkezi",
  "Çocuk Doktoru",
  "Çocuk Eğitimi ve Gelişimi Merkezi",
  "Çocuk Eğlence Parkları",
  "Çocuk Esirgeme Kurumu",
  "Çocuk Koruma Merkezi",
  "Çocuk Kulübü",
  "Çocuk Oyun Alanı",
  "Çocuk Psikolojisi Danışmanlık Merkezi",
  "Çocuk ve Aile",
  "Çocuk ve Gençlik",
  "Çokuluslu Şirket Ofisi",
  "Çorapçı",
  "Çöpçü",
  "Dadı",
  "Dağ Evleri",
  "Dağcılık ve Tırmanış Merkezi",
  "Dağıtım Firması",
  "Daktilograf",
  "Dalgıç",
  "Dalış Okulları",
  "Damıtıcı",
  "Danışman",
  "Danışmanlık Firması",
  "Dans Akademisi",
  "Dans Kursları",
  "Dans Stüdyosu",
  "Dansçı",
  "Dayanıklı Tüketim ve Elektronik",
  "Dedektif",
  "Değirmenci",
  "Dekorasyon Mağazası",
  "Dekoratif İnşaat Malzemesi Satan Mağaza",
  "Demirci Atolyesi",
  "Demirci",
  "Demiryolu İşçisi",
  "İşçi",
  "Denetçi",
  "Denetleyici",
  "Deniz Bilimi Araştırma Merkezi",
  "Deniz Ekipmanları Mağazası",
  "Deniz Ekosistemi Koruma Derneği",
  "Deniz Kirliliği Araştırma Merkezi",
  "Deniz Otobüsü ve Feribot İskeleleri",
  "Deniz Ulaşım Şirketi",
  "Deniz ve Okyanus Çalışmaları",
  "Deniz ve Su Bilimleri",
  "Denizci",
  "Denizcilik ve Su Sporları",
  "Denizcilik",
  "Depo Yönetimi Sistemleri Geliştiricisi",
  "Depocu",
  "Depolama Hizmeti",
  "Depolar",
  "Deprem Simülasyon Merkezi",
  "Dergi ve Gazete Yayıncıları",
  "Derici",
  "Dernek",
  "Dershane",
  "Desinatör",
  "Devlet Memuru",
  "Diğer Hizmetler",
  "Diğer",
  "Dijital Eğitim Platformu",
  "Dijital Medya ve İçerik",
  "Dijital Pazarlama Ajansı",
  "Dijital ve Geleneksel Eğitim",
  "Dil Değişim Programları Organizatörleri",
  "Dil Kursları",
  "Dini Kurum",
  "Diplomat",
  "Diş Hekimi",
  "Diş Kliniği",
  "Diş Klinikleri",
  "Diş Teknisyeni",
  "Diyetisyen",
  "Dizgici",
  "Doğa Koruma Kurumu",
  "Doğa Sporları Ekipmanları Mağazası",
  "Doğa Sporları Kulübü",
  "Doğa Turları Rehberleri",
  "Doğa ve Ekoturizm",
  "Doğa ve Macera",
  "Doğa Yürüyüşü Parkurları",
  "Doğalgazcı",
  "Doğramacı",
  "Doğum Uzmanı",
  "Doktor",
  "Dokuma ve Nakış Atolyesi",
  "Dokumacı",
  "Dondurma Üreticisi",
  "Dondurmacı",
  "Dökümcü",
  "Dönerciler",
  "Döşemeci",
  "Döviz Bürosu",
  "Dövizci",
  "Dövüş Sanatları Salonu",
  "Drone Çekim Hizmeti",
  "Drone Teknolojisi Geliştiren Firmalar",
  "Dublajcı",
  "Duvarcı",
  "Düğün Salonu",
  "Dümenci",
  "Ebe(Kadın Doğum)",
  "Eczacı Kalfası",
  "Eczacı",
  "Eczane",
  "Editör",
  "Eğitim Dışı Akademik Kurum",
  "Eğitim Dışı Aktiviteler",
  "Eğitim Robotları Üreten Şirket",
  "Eğitim Teknolojileri",
  "Eğitim ve Gelişim",
  "Eğitim ve Kurslar",
  "Eğitim ve Okul",
  "Eğitim ve Sertifikasyon",
  "Eğitim",
  "Eğitimci",
  "Eğitmen",
  "Eğlence Parkları",
  "Eğlence ve Çocuk Aktiviteleri",
  "Eğlence ve Dinlenme",
  "Ehliyet Kursları",
  "E-kitap Yayıncıları",
  "Eko-Köyler",
  "Ekonomist",
  "Ekoturizm Tesisi",
  "El Sanatları Atolyesi",
  "El Sanatları ve Tasarım",
  "Elektrik Mühendisi",
  "Elektrik Şirketi",
  "Elektrik ve Doğalgaz Tedarik Şirketi",
  "Elektrik ve Elektronik Mühendislik Firması",
  "Elektrik ve Elektronik Tamir Hizmeti",
  "Elektrik ve Tesisat Hizmeti",
  "Elektrikçi",
  "Elektrik-Elektronik Mühendisi",
  "Elektrikli Araç Kiralama Hizmeti",
  "Elektrikli Araç Şarj İstasyonu",
  "Elektrikli Ev Aletleri Satıcısı",
  "Elektronik Mağazası",
  "Elektronik Mühendisi",
  "Elektronik Ürün Satan Mağaza",
  "Elektronik Ve Haberleşme Mühendisi",
  "Eleştirmen",
  "Embriyolog",
  "Emlak Ofisi",
  "Emlak ve İnşaat",
  "Emlakçı",
  "Endüstri Mühendisi",
  "Endüstri Sistemleri Mühendisi",
  "Endüstriyel Makine Üreticisi",
  "Enerji ve Çevre",
  "Enerji ve Teknoloji",
  "Enerji ve Yakıt",
  "Enerji Verimliliği Danışmanlık Firması",
  "Enstitüler",
  "Enstrüman İmalatçısı",
  "Ergonomist",
  "Eski Eşya Yenileme Atolyesi",
  "Eskici",
  "Esnaf",
  "E-spor Merkezi",
  "E-spor Organizasyonları",
  "Estetik ve Plastik Cerrahi Merkezi",
  "Estetisyen",
  "Etimolog",
  "Etkinlik Planlama Şirketi",
  "Etkinlik ve Organizasyon",
  "Etnografya Müzesi",
  "Etnolog",
  "Etolojist",
  "Etüt Merkezi",
  "Ev Dekorasyonu Ürünleri Satan Mağaza",
  "Ev Hanımı",
  "Ev Hizmeti",
  "Ev Tadilat ve Dekorasyon Firması",
  "Ev ve Ofis Hizmeti",
  "Evcil Hayvan Eğitim Hizmeti",
  "Evcil Hayvan Mağazası",
  "Evcil Hayvan ve Hayvan Hakları",
  "Evden Çalışan Küçük İşletme",
  "Evden Eve Nakliyat Firması",
  "Fabrika İşçisi",
  "Fabrika Otomasyonu Sağlayıcısı",
  "Fast Food Zinciri",
  "Fast Food Zincirleri",
  "Feribot ve Deniz Ulaşım Şirketi",
  "Fermantasyon İşçisi",
  "Festival Organizasyon Şirketi",
  "Festival ve Etkinlik Alanı",
  "Fıçıcı",
  "Fırıncı",
  "Fırınlar",
  "Fidancılar ve Bitki Satıcısı",
  "Fidanlık ve Seralar",
  "Fidanlıklar",
  "Figüran",
  "Film Stüdyosu",
  "Film ve Video Prodüksiyon",
  "Film Yapımcısı",
  "Film Yönetmeni",
  "Filozof",
  "Finans Kuruluşu",
  "Finans",
  "Finansal Danışmanlık Firması",
  "Finansör",
  "Fitness Cihazları Satıcısı",
  "Fizik Tedavi ve Rehabilitasyon Merkezi",
  "Fizikçi",
  "Fizyonomist",
  "Fizyoterapist",
  "Fon Yöneticisi",
  "Forklift Operatörü",
  "Fotoğraf Stüdyosu",
  "Fotoğrafçı",
  "Fotoğrafçılık Kulübü",
  "Freelance Proje Yönetim Ajansı",
  "Freelancer Ofis Alanı",
  "Fuar ve Kongre Merkezi",
  "Futbol Sahaları",
  "Futbolcu",
  "Galeri (Araç Satışı)",
  "Galerici",
  "Gardiyan",
  "Garson",
  "Gayrimenkul Değerleme Şirketi",
  "Gayrimenkul Geliştirme Firması",
  "Gazeteci",
  "Geçici İş Sağlama Ajansı",
  "Geleneksel El Sanatları Eğitim Merkezi",
  "Geleneksel Tatlı Üreticisi",
  "Gelir Uzman Yardımcısı",
  "Gelir Uzmanı",
  "Gemici",
  "Genç Girişimciler Kulübü",
  "Gençlik Merkezi",
  "Genetik Araştırma Merkezi",
  "Genetik Mühendisi",
  "Geri Dönüşüm Merkezi",
  "Gezgin",
  "Gıda İşleme Fabrikası",
  "Gıda İşleme Makine Üreticisi",
  "Gıda Mühendisi",
  "Gıda Teknolojisi ve Üretim",
  "Gıda ve Restoran",
  "Gıda ve Su Yardım Dağıtım Şirketi",
  "Girişim Sermayesi Şirketi",
  "Gitarist",
  "Giyim Mağazası",
  "Global Lojistik Şirketi",
  "Gökbilimci",
  "Göz Doktoru",
  "Gözetmen",
  "Gözlükçü",
  "Grafiker",
  "Gramer Uzmanı",
  "Greyder Operatörü",
  "Güfteci",
  "Gümrük Memuru",
  "Gümrük Müşavir Yardımcısı",
  "Gümrük Müşaviri",
  "Gümrük Uzmanı",
  "Gündelikçi",
  "Güneş Paneli Satıcısı",
  "Güvenlik Şirketi",
  "Güzellik Merkezi",
  "Güzellik Salonu",
  "Güzellik Uzmanı",
  "Haberci",
  "Haddeci",
  "Hakem",
  "Halı ve Perde Mağazası",
  "Halıcı",
  "Halıcılık ve Dokuma Atolyesi",
  "Halıcılık ve Kilim Atolyesi",
  "Halkbilimci",
  "Halkla İlişkiler Şirketi",
  "Hamurkâr",
  "Hareket Memuru",
  "Harita Mühendisi",
  "Haritacı",
  "Haritacılık Şirketi",
  "Hastabakıcı",
  "Hastahane",
  "Hastane",
  "Hastaneler",
  "Hattat",
  "Hava Trafikçisi",
  "Hava Yolu Şirketi",
  "Havacı",
  "Havacılık Eğitim Akademisi",
  "Havalimanları",
  "Hayvan Bakıcısı",
  "Hayvan Barınakları Destek Derneği",
  "Hayvan Barınakları",
  "Hayvan Eğitim Merkezi",
  "Hayvan Oteli",
  "Hayvan Rehabilitasyon Merkezi",
  "Hayvan Sağlığı İlaç Satıcısı",
  "Hayvan ve Evcil Hayvan Hizmeti",
  "Hayvan Yemi Üreticisi",
  "Hayvanlar ve Doğa",
  "Hazır Yemek Üretim Tesisi",
  "Hediyelik Eşya Mağazası",
  "Hemşire",
  "Hesap Uzmanı",
  "Heykel Atolyesi",
  "Heykeltıraş",
  "Hırdavatçı",
  "Hızlı Tüketim ve Servisler",
  "Hidrografi ve Oşinografi Çalışmaları",
  "Hidrolikçi",
  "Hidroponik Çiftlikler",
  "Hizmet ve Danışmanlık",
  "Hizmet",
  "Hizmetçi",
  "Hobi Bahçeleri",
  "Hobi Kulübü (Satranç, Origami, vb.)",
  "Hobi Mağazası",
  "Hobi ve El Sanatları",
  "Holding",
  "Host",
  "Hosteller",
  "Hostes",
  "Hukuk Bürosu",
  "Hukuk ve Danışmanlık",
  "Hukukçu",
  "Hurda İşleme Tesisi",
  "Hurdacı",
  "Irgat",
  "Işıkçı",
  "İcra Memuru",
  "İç Mimar",
  "İç Mimarlık Ofisi",
  "İğneci",
  "İhracat ve İthalat Şirketi",
  "İhracatçı Birlikleri",
  "İhracatçı",
  "İklim Değişikliği Eğitim Programları",
  "İklim ve Çevre Teknolojileri",
  "İklimlendirme ve Havalandırma Şirketi",
  "İktisatçı",
  "İlahiyatçı",
  "İleri Tarım ve Hayvancılık",
  "İletişim ve PR Hizmeti",
  "İlkokullar",
  "İllüzyonist",
  "İmam",
  "İnfluencer Ajansı",
  "İnsan Hakları İzleme Organizasyonları",
  "İnsan Kaynakları Uzmanı",
  "İnsan Kaynakları ve İstihdam",
  "İnsan Kaynakları Yönetim Şirketi",
  "İnşaat Firması",
  "İnşaat Malzemesi Satıcısı",
  "İnşaat Mühendisi",
  "İnşaat Mühendisliği Danışmanlıkları",
  "İnşaat Mühendislik Firması",
  "İnşaat Şirketi",
  "İnşaat ve Altyapı",
  "İnşaat ve Gayrimenkul",
  "İnşaat ve Yapı Marketler",
  "İnşaatçı",
  "İnteraktif Ders Materyalleri Üreticisi",
  "İnternet Radyosu",
  "İnternet Servis Sağlayıcısı",
  "İpçi",
  "İplikçi",
  "İstatistikçi",
  "İstihkâmcı",
  "İşaretçi",
  "İşe Alım Danışmanlık Firması",
  "İşletme Mühendisi",
  "İşletmeci",
  "İşportacı",
  "İtfaiyeci",
  "İthalatçı",
  "İyilik Marketi",
  "Jeofizik Mühendisi",
  "Jeolog",
  "Jeoloji Mühendisi",
  "Jeomorfolog",
  "Jimnastikçi",
  "Jinekolog",
  "Jokey",
  "Kabin Görevlisi",
  "Kaçış Odaları",
  "Kadın Girişimci Üretim Merkezi",
  "Kadın Terzisi",
  "Kafe",
  "Kafeler",
  "Kâğıtçı",
  "Kahveci",
  "Kahvehaneler",
  "Kâhya",
  "Kalaycı",
  "Kalıpçı",
  "Kaloriferci",
  "Kameraman",
  "Kamp Alanı",
  "Kamu Görevlisi",
  "Kamu Kurumu",
  "Kamu ve Belediye Hizmeti",
  "Kamu ve Sivil Toplum",
  "Kamyoncu",
  "Kapı ve Pencere Sistemleri Üreticisi",
  "Kapıcı",
  "Kaplamacı",
  "Kaportacı",
  "Kaptan",
  "Karaoke Salonu",
  "Karavan ve Kamp Hizmeti",
  "Karbon Ayak İzi Danışmanlık Şirketi",
  "Karbon Emisyonu Azaltma Şirketi",
  "Kardiyolog",
  "Kargo Şirketi",
  "Kargo ve Kurye Hizmeti",
  "Karikatürist",
  "Kariyer Gelişim Merkezi",
  "Karoserci",
  "Karpuzcu",
  "Kasap",
  "Kasiyer",
  "Kat Görevlisi",
  "Kâtip",
  "Katkı Maddesi ve Baharat Üreticisi",
  "Kayıkçı",
  "Kaymakam",
  "Kaynakçı",
  "Kebapçı",
  "Kemancı",
  "Kentsel Dönüşüm Şirketi",
  "Kentsel Planlama Firması",
  "Kesimci",
  "Kırsal Kalkınma ve Yerel Üretim",
  "Kırtasiyeci",
  "Kimya Mühendisi",
  "Kimya Sanayi Firması",
  "Kimyager",
  "Kişisel Antrenör Hizmeti",
  "Kişisel Bakım ve Sağlık",
  "Kişisel Blog",
  "Kişisel Gelişim Atolyesi",
  "Kişisel Gelişim Koçluğu Firması",
  "Kitapçı",
  "Klarnetçi",
  "Kodlama ve Yazılım Eğitimleri",
  "Koleksiyoncu",
  "Komedi Kulübü",
  "Komedyen",
  "Komisyoncu",
  "Konaklama ve Yeme-İçme",
  "Konser Alanı",
  "Konser Organizasyon Firması",
  "Konservatuvarlar",
  "Konserveci",
  "Konsolos",
  "Konsolosluk",
  "Kontrolör",
  "Konveyör Operatörü",
  "Kooperatifler",
  "Koreograf",
  "Koruma Görevlisi",
  "Kozmetik Ürün Mağazası",
  "Kozmolog",
  "Köfteci",
  "Kömürcü",
  "Köşe Yazarı",
  "Kreş",
  "Kriz İletişim Danışmanlıkları",
  "Kriz Yönetimi ve Afet Hazırlığı",
  "Kuaför",
  "Kumaş Üreticisi",
  "Kumaşçı",
  "Kumcu",
  "Kuru Temizleme",
  "Kuru Temizlemeci",
  "Kuruyemişçi",
  "Kurye",
  "Kuşbilimci",
  "Kuşçu",
  "Kuyumcu",
  "Küçük İşletme",
  "Küçük Perakendeci",
  "Kültür Merkezi",
  "Kültür Turları Organizasyonları",
  "Kültür ve Miras",
  "Kültür ve Sanat",
  "Kültürel Miras Koruma Merkezi",
  "Kürkçü",
  "Kütüphane",
  "Kütüphaneci",
  "Laborant",
  "Laboratuvar İşçisi",
  "Lahmacuncu",
  "Lastik Satıcısı",
  "Lehimci",
  "Levazımcı",
  "Liman İşletmesi",
  "Lise",
  "Lobici",
  "Lokanta",
  "Lokman",
  "Lokomotifçi",
  "Lunapark",
  "Lüks Araç Kiralama Hizmeti",
  "Lüks Tatil Köyleri",
  "Madenci",
  "Madencilik Şirketi",
  "Makasçı",
  "Makastar",
  "Maketçi",
  "Makine Mühendisi",
  "Makine Zabiti",
  "Makinist",
  "Mali Hizmetler Uzmanı",
  "Manav",
  "Manifaturacı",
  "Marangoz",
  "Marka Yönetim Danışmanlıkları",
  "Market Zinciri",
  "Market",
  "Masör",
  "Matbaacı",
  "Matematikçi",
  "Matkapçı",
  "Medikal Ekipman Üreticisi",
  "Medikal Teknoloji",
  "Medya Planlama Uzmanı",
  "Medya ve Yayın Teknolojisi",
  "Medya ve Yayıncılık",
  "Memur",
  "Menajer",
  "Mercan Resifi Koruma Organizasyonları",
  "Mermerci",
  "Meslek Edindirme Kursları",
  "Metal İşleme Atolyesi",
  "Metalurji Mühendisi",
  "Meteoroloji Uzmanı",
  "Metin Yazarı",
  "Metro ve Tramvay İstasyonu",
  "Mevsimlik İşçi",
  "Meydancı",
  "Meyve ve Sebze Tezgahları",
  "Meze Dükkanları",
  "Mikro Finans Kuruluşu",
  "Mikrobiyolog",
  "Milletvekili",
  "Milli Parklar",
  "Mimar ve Mühendislik",
  "Mimar",
  "Mimari ve Dekorasyon",
  "Mimarlık Ofisi",
  "Mimarlık Proje Ofisi",
  "Mobil Oyun Geliştiricisi",
  "Mobilya Mağazası",
  "Mobilya Montaj Hizmeti",
  "Mobilyacı",
  "Moda Markalarının Showroomları",
  "Moda Tasarım Akademisi",
  "Moda Tasarım Stüdyosu",
  "Moda ve Giyim",
  "Moda ve Tekstil",
  "Modacı",
  "Modelist",
  "Montajcı",
  "Montör",
  "Moteller",
  "Motor Tamircisi",
  "Motosiklet Servisi",
  "Muhabbet Tellalı",
  "Muhabir",
  "Muhafız",
  "Muhasebeci",
  "Muhtar",
  "Mutfak ve Banyo Dekorasyon Mağazası",
  "Mübaşir",
  "Müdür",
  "Müezzin",
  "Müfettiş",
  "Mühendis",
  "Mürebbiye",
  "Müsteşar",
  "Müşavir",
  "Müteahhit",
  "Müteahhitlik Hizmeti",
  "Mütercim",
  "Müze Müdürü",
  "Müze ve Sergi Salonu",
  "Müzeler",
  "Müzik Enstrümanları Satıcısı",
  "Müzik Kursları",
  "Müzik Okulu",
  "Müzik Stüdyosu",
  "Müzik ve Performans Sanatları",
  "Müzik Yönetmeni",
  "Müzisyen",
  "Nakışçı",
  "Nakliyat Firması",
  "Nakliye ve Lojistik Firması",
  "Nakliyeci",
  "Nalbant",
  "Nalbur",
  "Noter",
  "Ocakçı",
  "Odacı",
  "Oduncu",
  "Okçu",
  "Okul Müdürü",
  "Okul Öncesi Öğretmeni",
  "Okul",
  "Okutman",
  "Online Eğitim Platformu",
  "Online Eğitim Uygulamaları",
  "Online Haber Ajansı",
  "Online Pazarlama Şirketi",
  "Online Terapi Hizmeti",
  "Sanatçı",
  "Operatör",
  "Optik Mağazası",
  "Optik ve Gözlükçüler",
  "Organik Gıda ",
  "Organik Hayvancılık İşletmesi",
  "Organik Tarım Çiftlikleri",
  "Organik Ürün Marketi",
  "Organizasyon Firması",
  "Orgcu",
  "Orman Mühendisi",
  "Ornitolog (Veya Kuşbilimci)",
  "Ortaokul",
  "Otel",
  "Otelci",
  "Oto Elektrikçisi",
  "Oto Galeri",
  "Oto Lastik Tamircisi",
  "Oto Servis ve Tamirciler",
  "Oto Tamircisi",
  "Oto Yedek Parçacı",
  "Oto Yıkama ve Bakım Merkezi",
  "Oto Yıkama",
  "Otobüs Firması",
  "Otobüs Terminalleri",
  "Otomotiv Fabrikası",
  "Otomotiv ve Araç Hizmeti",
  "Otomotiv ve Ulaşım",
  "Otomotiv Yedek Parça Satıcısı",
  "Otomotiv",
  "Otoparklar",
  "Overlokçu",
  "Oyun Hostesi",
  "Oyun Konsolu ve Aksesuar Mağazası",
  "Oyun Salonu",
  "Oyun ve Eğlence Hizmeti",
  "Oyun ve Eğlence Teknolojileri",
  "Oyun Yazarı",
  "Oyun Yazılım Şirketi",
  "Oyuncak Mağazası",
  "Oyuncakçı",
  "Oyuncu",
  "Öğretim Elemanı",
  "Öğretim Görevlisi",
  "Öğretim Teknolojileri Geliştiren Firma",
  "Öğretim Üyesi",
  "Öğretmen",
  "Ön Büro Elemanı",
  "Ön Muhasebe Sorumlusu",
  "Ön Muhasebe Yardımcı Elemanı",
  "Ön Muhasebeci",
  "Örmeci",
  "Özel Dedektiflik Ofisi",
  "Özel Dikim Atolyesi",
  "Özel Eğitim Kurumu",
  "Özel Güvenlik Şirketi",
  "Özel Güvenlik ve Savunma",
  "Özel Jet Kiralama Şirketi",
  "Özel Koruma Hizmeti",
  "Özel Okullar",
  "Özel Parti ve Düğün Organizasyon Firması",
  "Özel Poliklinik",
  "Özel Şoför",
  "Paketleyici",
  "Palyaço",
  "Panayır ve Kermes Alanı",
  "Pandomimci",
  "Pansiyon",
  "Pansiyoncu",
  "Pansumancı",
  "Paramedik",
  "Park Bekçisi",
  "Pastane",
  "Pastörizör",
  "Patolog",
  "Paylaşımlı Çalışma Alanı (Co-working Spaces)",
  "Pencereci",
  "Perukçu",
  "Pet Kuaförleri",
  "Pet Shoplar",
  "Peynir Üreticisi",
  "Peyzaj Mimarı",
  "Peyzaj Mimarlık Ofisi",
  "Peyzaj Tasarım Firması",
  "Peyzaj Teknikeri",
  "Pideci",
  "Pideciler",
  "Pilates Stüdyosu",
  "Pilavcı",
  "Pilot",
  "Piyade",
  "Piyanist",
  "Podcast Stüdyosu",
  "Polis Karakolu",
  "Polisajcı",
  "Postacı",
  "Profesör",
  "Profesyonel Eğitim Akademisi",
  "Proktolog",
  "Protokol Görevlisi",
  "Prototip Üretim Atolyesi",
  "Psikiyatr",
  "Psikolog",
  "Psikolojik Danışmanlık Ve Rehberlik",
  "Radyo İstasyonu",
  "Radyolog",
  "Radyoloji Teknisyeni/Teknikeri",
  "Redaktör",
  "Rehabilitasyon Merkezi",
  "Rehber",
  "Rejisör",
  "Reklam Ajansı",
  "Reklamcı",
  "Rektör Yardımcısı",
  "Rektör",
  "Remayözcü",
  "Rent a Car Şirketi",
  "Resepsiyon Memuru",
  "Resim ve Sanat Atolyesi",
  "Ressam",
  "Restoran",
  "Restorasyon ve Tarihi Koruma",
  "Robotik ve Kodlama Atolyesi",
  "Robotik ve Kodlama Ürün Mağazası",
  "Rot Balansçı",
  "Saat Tamircisi",
  "Saat ve Mücevher Satıcısı",
  "Saatçi",
  "Sağlık Merkezi",
  "Sağlık Teknisyeni",
  "Sağlık Teknolojisi Geliştiren Şirket",
  "Sağlık ve Güzellik",
  "Sağlık",
  "Sağlıklı Yaşam ve Detoks Merkezi",
  "Sahil Koruma",
  "Sahne Tasarım ve Işıklandırma Şirketi",
  "Salepçi",
  "Sanal Gerçeklik Deneyim Merkezi",
  "Sanal Gerçeklik Deneyim Şirketi",
  "Sanal Sınıf Teknolojileri Geliştiricisi",
  "Sanal ve Dijital Hizmetler",
  "Sanat Atölyesi",
  "Sanat Galerileri",
  "Sanat Malzemeleri Satış Noktası",
  "Sanat Yönetmeni",
  "Sanayi ve Lojistik",
  "Sanayi ve Ticaret",
  "Sanayi ve Üretim",
  "Sanayici",
  "Sansürcü",
  "Santral Memuru",
  "Saraç",
  "Sarraf",
  "Satış Elemanı",
  "Satranç Kursları",
  "Savunma Sanayi Şirketi",
  "Savunma ve Güvenlik",
  "Saz Şairi",
  "Scooter ve Bisiklet Kiralama Noktası",
  "Sekreter",
  "Senarist",
  "Sendika",
  "Sepetçi",
  "Seracılar",
  "Seramik ve Çömlekçilik Atolyesi",
  "Serbest Muhasebeci Mali Müşavir",
  "Serbest Ticaret Bölgeleri",
  "Sergi Salonu",
  "Servis ve Teknik Destek Merkezi",
  "Ses Kayıt Stüdyosu",
  "Ses Teknisyeni",
  "Ses ve Işık Sistemleri Kiralama Firması",
  "Seyahat Acentesi",
  "Seyahat ve Ulaşım Hizmeti",
  "Seyis",
  "Seyyar Satıcı",
  "Sıfır Atık Proje Ofisi",
  "Sıfır Atık Üretim Tesisi",
  "Sicil Memuru",
  "Sigorta Şirketi",
  "Sigortacı",
  "Sihirbaz",
  "Silindir Operatörü",
  "Simitçi",
  "Simülasyon Teknolojileri Firması",
  "Simyacı",
  "Sinema Salonu",
  "Sinemalar",
  "Sistem Mühendisi",
  "Sistem Yöneticisi",
  "Sivil İnisiyatif Platformu",
  "Sivil Toplum ve İnsan Hakları",
  "Siyasetçi",
  "Soğuk Demirci",
  "Sokak Çalgıcısı",
  "Sokak Hayvanları Besleme Grupları",
  "Sokak Lezzetleri Noktası",
  "Sokak İşletme",
  "Solaryum Merkezi",
  "Son Ütücü",
  "Sosyal Etki ve Topluluk Gelişimi",
  "Sosyal Etkinlikler ve Organizasyon",
  "Sosyal Girişimcilik Organizasyonları",
  "Sosyal Güvenlik Merkezi",
  "Sosyal Hizmet Uzmanı",
  "Sosyal Hizmetler",
  "Sosyal Medya Yönetim Şirketi",
  "Sosyal Yardım Kuruluşu",
  "Sosyolog",
  "Spa Merkezi",
  "Spa ve Wellness Merkezi",
  "Spiker",
  "Spor Kamp Alanı",
  "Spor Kulübü",
  "Spor Mağazası",
  "Spor Malzemeleri ve Hizmeti",
  "Spor Salonu",
  "Spor ve Eğlence",
  "Spor ve Fitness",
  "Sporcu Beslenme ve Takviyeleri Üreticisi",
  "Sporcu",
  "Stadyum",
  "Start-up Kuluçka Merkezi",
  "STEM Eğitim Programları",
  "Stenograf",
  "Stilist",
  "Su Altı Fotoğrafçılığı Atolyesi",
  "Su Kayağı ve Jet Ski Merkezi",
  "Su Sporları Merkezi",
  "Su Tesisatçısı",
  "Su Ürünleri Yetiştiriciliği Kooperatifi",
  "Su ve Doğalgaz Dağıtım Şirketi",
  "Sucu",
  "Suflör",
  "Sulama Sistemleri Mağazası",
  "Sulama Sistemleri Üreticisi",
  "Sunucu",
  "Susuz Araç Yıkama",
  "Sünnetçi",
  "Süpermarket",
  "Sürdürülebilir Moda Atolyesi",
  "Sürdürülebilirlik ve Yenilik",
  "Süt Ürünleri İşleme Tesisi",
  "Sütçü",
  "Şair",
  "Şapkacı",
  "Şarkı Sözü Yazarı",
  "Şarkıcı",
  "Şarküter",
  "Şarküteri, Gıda Pazarları Ve Bakkal Satış Elemanı",
  "Şehir İçi Taşımacılık Firması",
  "Şehir Plancısı",
  "Şehir Turları Rehberlik Hizmeti",
  "Şehir Turu Otobüsleri",
  "Şekerci",
  "Şemsiyeci",
  "Şıracı",
  "Şifre Çözümleyici",
  "Şirket",
  "Şoför",
  "Tabakçı",
  "Tabelacı",
  "Tahsildar",
  "Takı Tasarım Atolyesi",
  "Takı ve Aksesuar Dükkanı",
  "Takı ve Kuyumcu",
  "Taksi Durakları",
  "Taksici",
  "Tarım Aletleri Satıcısı",
  "Tarım Drone Hizmeti",
  "Tarım İşçisi",
  "Tarım Makinesi Satıcısı",
  "Tarım Malzemesi Satıcısı",
  "Tarım Teknolojileri",
  "Tarım ve Bahçe",
  "Tarım ve Hayvancılık İşletmesi",
  "Tarım ve Hayvancılık",
  "Tarihçi",
  "Tarihi Eser Restorasyon Firması",
  "Tarihi Yapı Rehberlik Hizmeti",
  "Tasarımcı",
  "Taşçı",
  "Taşımacılık Firması",
  "Taşımacılık ve Araç Hizmeti",
  "Taşımacılık ve Lojistik",
  "Taşlayıcı",
  "Tatil Köyü",
  "Tatlıcı",
  "Tatlıcılar (Baklavacılar, Lokmacılar)",
  "Tavuk Çiftliği",
  "Tavukçu",
  "Tayfa",
  "Teknik Eğitim Merkezi",
  "Tekniker",
  "Teknisyen",
  "Teknoloji Danışmanlık Firması",
  "Teknoloji Geliştirme Bölgeleri (Teknoparklar)",
  "Teknoloji Geliştirme ve İnovasyon",
  "Teknoloji Mağazası",
  "Teknoloji Perakendeciliği",
  "Teknoloji Transfer Ofisi",
  "Teknoloji Uzmani",
  "Teknoloji ve İletişim",
  "Tekstil Fabrikası",
  "Tekstil İhracatçısı Firmalar",
  "Tekstil Üretim Tesisi",
  "Telefon Operatörü",
  "Telekomünikasyon Şirketi",
  "Tele-tıp Hizmeti",
  "Televizyon Tamircisi",
  "Tellal",
  "Temizlik Firması",
  "Temizlik Şirketi",
  "Temizlikçi",
  "Temsilci",
  "Tenis Kortu",
  "Terapist",
  "Tercüman",
  "Termal Otel",
  "Terzi",
  "Tesisatçı",
  "Test Mühendisi",
  "Test Pilotu",
  "Tesviyeci",
  "Teşrifatçı",
  "Tezgahtar",
  "Tıp Doktoru",
  "Tıp Merkezi",
  "Ticaret Odası",
  "Ticaret ve Pazarlama",
  "Tiyatro Eğitim Merkezi",
  "Tiyatro Salonu",
  "Tiyatro Yönetmeni",
  "Tiyatrolar",
  "Tohum ve Fide Üreticisi",
  "Topçu",
  "Toplum Destekli Tarım (CSA)",
  "Toplum Merkezi",
  "Toplumsal Eşitlik Platformu",
  "Toptan ve Dağıtım",
  "Toptancılar",
  "Tornacı",
  "Tren İstasyonu",
  "Tuhafiyeci",
  "Tur Operatörleri",
  "Turizm ve Eğlence",
  "Turizm ve Konaklama",
  "Turizm ve Tatil Hizmeti",
  "Turizm",
  "Turizmci",
  "Turşucu",
  "Tuzcu",
  "TV Kanalları",
  "Uçak Bakım Mühendisi",
  "Uçuş Teknisyeni",
  "Ulaşım Sorumlusu",
  "Ulaşım ve Seyahat",
  "Ulaşım",
  "Ulaştırma",
  "Uluslararası Fuar Alanı",
  "Uluslararası İş ve Ticaret",
  "Uluslararası İşletme",
  "Uluslararası Kurum",
  "Uluslararası Nakliye Firması",
  "Uluslararası Okul",
  "Uluslararası STK'lar",
  "Uluslararası Ticaret Danışmanlığı",
  "Ustabaşı",
  "Uydu Antenci",
  "Uydu Teknolojileri Şirketi",
  "Uzaktan Çalışma Platformu",
  "Uzaktan Çalışma ve Freelance",
  "Uzaktan Eğitim Platformu",
  "Uzaktan İşletme Eğitimleri",
  "Uzay Araştırma Merkezi",
  "Uzay Bilimcisi",
  "Uzay Mühendisi",
  "Uzay ve Havacılık",
  "Uzman Çavuş",
  "Üniversite",
  "Üretici",
  "Üretim Fabrikası",
  "Ürolog",
  "Üst Düzey Yönetici",
  "Ütücü",
  "Üzümcü",
  "Vaiz",
  "Vakıf",
  "Vatman",
  "Vergi Daireleri",
  "Vergi Denetmeni",
  "Vergi Müfettişi",
  "Vergi Tahakkuk Memuru",
  "Veri Hazırlama Ve Kontrol İşletmeni",
  "Veritabanı Yöneticisi",
  "Vestiyerci",
  "Veteriner Hekim",
  "Veteriner Kliniği",
  "Veteriner Sağlık Teknikeri",
  "Veteriner Sağlık Teknisyeni",
  "Veznedar",
  "Video Editörü",
  "Video İçerik Üretim Ajansı",
  "Video Prodüksiyon Şirketi",
  "Vinç Operatörü",
  "Vitrinci",
  "VR/AR Cihazları Satıcısı",
  "VR/AR Video Üreticisi",
  "Yabancı Dil Eğitim Merkezi",
  "Yabancı Yatırım Danışmanlık Firması",
  "Yangın Güvenliği Ekipmanları Satan Firmalar",
  "Yapay Zeka Geliştirme Şirketi",
  "Yapay Zeka Laboratuvarları",
  "Yapı Marketler",
  "Yaratıcı Sanatlar",
  "Yardım ve Destek Kurumu",
  "Yardımcı Hakem",
  "Yardımcı Hizmetli",
  "Yardımcı Pilot",
  "Yaşam Tarzı ve Hobi",
  "Yat Limanları",
  "Yat Üreticisi",
  "Yatırım Danışmanlık Şirketi",
  "Yatırım Uzmanı",
  "Yatırım ve Finans",
  "Yayıncı",
  "Yaz Kampları",
  "Yazar",
  "Yazı İşleri Müdürü",
  "Yazılım Firması",
  "Yazılım Mühendisi",
  "Yelkenci",
  "Yeme-İçme ve Gıda Satışı",
  "Yeminli Mali Müşavir",
  "Yeminli Tercüman",
  "Yeniden Ağaçlandırma Projeleri",
  "Yenilenebilir Enerji Kaynakları Geliştiricisi",
  "Yenilenebilir Enerji Şirketi",
  "Yer Gösterici",
  "Yer Teknisyeni",
  "Yerel Halk Dansı Grupları",
  "Yerel Üretici Pazarı",
  "Yerel ve Geleneksel İşletme",
  "Yerölçmeci",
  "Yeşil Enerji Şirketi",
  "Yetişkin Eğitim Merkezi",
  "Yetiştiricilik",
  "Yiyecek Üretimi ve Dağıtımı",
  "Yiyecek ve İçecek Üretimi",
  "Yoga Stüdyosu",
  "Yoga ve Meditasyon Merkezi",
  "Yol Bekçisi",
  "Yol ve Köprü İnşaat Şirketi",
  "Yorgancı",
  "Yorumcu",
  "Yönetici",
  "Yönetmen",
  "Yöresel Ürün Satıcısı",
  "Yumurtacı",
  "Yurt Dışı Eğitim ve Dil Kampı Organizasyonları",
  "Yurt",
  "Yüksek Kalite Mücevher Mağazası",
  "Yüzme Havuzu",
  "Yüzücü",
  "Zabıt Katibi",
  "Zabıta",
  "Zanaat ve El İşi",
  "Zayıflama Merkezi",
  "Zeytin ve Zeytinyağı İşletmesi",
  "Zeytinyağı Üreticisi",
  "Ziraat Mühendisi",
  "Zirai Ürün Satıcısı",
  "Zoolog",
  "Hizmet Sektörü",
  "Kahvaltı Salonu",
  "Paket Servis Restoranları",
  "Otomat Satış Hizmeti",
  "Yemek Dağıtım Şirketi",
  "Kentsel Ulaşım ve Taşımacılık",
  "Minibüs Durağı",
  "Dolmuş Hattı",
  "Şehir İçi Otobüs Durağı",
  "Bisiklet Kiralama Hizmeti",
  "Scooter Paylaşım Hizmeti",
  "Reklam ve Pazarlama",
  "Grafik Tasarım Ofisi",
  "Sosyal Medya Yönetim Firması",
  "Dijital Pazarlama Şirketi",
  "Basılı Reklam Ürünleri Satan Firmalar",
  "Arabuluculuk Hizmeti",
  "Vergi Danışmanlık Ofisi",
  "Göçmenlik Danışmanlık Firması",
  "Patent ve Marka Danışmanlık Şirketi",
  "Robotik ve Kodlama Eğitim Merkezi",
  "Özel Ders Veren Kurum",
  "Eğitim Materyali Satıcısı",
  "Sertifikalı Eğitim Programları",
  "Giyim Butikleri",
  "Moda Tasarım Atolyesi",
  "Kumaş Mağazası",
  "Ünlü Markaların Mağazası",
  "Doğa ve Outdoor Aktiviteler",
  "Dağcılık ve Kamp Malzemeleri Satan Mağaza",
  "Trekking ve Doğa Rehberleri",
  "Outdoor Sporlar Eğitim Merkezi",
  "Doğa Fotoğrafçılığı Kulübü",
  "Eğlence Teknolojisi",
  "Konsol Oyun Mağazası",
  "VR (Sanal Gerçeklik) Oyun Salonu",
  "E-spor Turnuva Organizasyonları",
  "Sanat ve Tasarım",
  "Sanat Atolyesi",
  "Çerçeveleme Hizmeti",
  "Heykel Stüdyosu",
  "El Sanatları Mağazası",
  "Dijital Sanat Üretim Ofisi",
  "Toplum ve Yardımlaşma",
  "Sosyal Yardım Vakıfları",
  "Gıda Bankaları",
  "Kadın Dayanışma Merkezi",
  "Hayvan Hakları Derneği",
  "Hayvan Yem ve Ekipman Satıcısı",
  "Süt ve Süt Ürünleri İşletmesi",
  "Ziraat Mühendislik Hizmeti",
  "Denizcilik ve Balıkçılık",
  "Liman Hizmeti",
  "Tekne Kiralama Firması",
  "Deniz Malzemeleri Satıcısı",
  "Balıkçılık Teknolojisi Firması",
  "Su Sporları Kulübü",
  "Kültür ve Eğlence",
  "Kitap ve Kütüphane Hizmeti",
  "Müzik ve Enstrüman Mağazası",
  "Tiyatro ve Performans Grupları",
  "Film ve Dizi Çekim Ajansı",
  "Finansal Hizmetler",
  "Finans Teknolojisi (FinTech) Şirketi",
  "Altın Alım-Satım Firması",
  "Kredi Danışmanlık Şirketi",
  "Leasing Şirketi",
  "İklim ve Çevre",
  "Geri Dönüşüm Tesisi",
  "Atık Yönetimi Şirketi",
  "Çevre Dostu Ürün Satıcısı",
  "Ekolojik Eğitim Merkezi",
  "Uluslararası Hizmetler",
  "Yurt Dışı Eğitim Danışmanlık Firması",
  "Çeviri ve Tercüme Bürosu",
  "Uluslararası Taşımacılık Firması",
  "Kültürel Etkinlik Organizatörleri",
  "Ticaret ve Perakende",
  "Outlet Mağazası",
  "Züccaciye ve Ev Eşyası Mağazası",
  "İkinci El Mağazası",
  "Saat ve Takı Mağazası",
  "Tuhafiyeler",
  "Eğlence ve Hobi",
  "Hobi Mağazası (Model Yapımı, El İşi, vb.)",
  "Kitap Kulübü",
  "Video Oyun Kiralama ve Satış Noktası",
  "Paintball Alanı",
  "Sanal Gerçeklik Merkezi",
  "Dans ve Tiyatro Grupları",
  "Özel Hizmetler",
  "Organizasyon Şirketi (Düğün, Davet, vb.)",
  "Kına ve Nişan Hazırlık Hizmeti",
  "Fotoğraf ve Video Çekim Hizmeti",
  "Mezarlık Bakım ve Çiçek Hizmeti",
  "Özel Şoför Hizmeti",
  "Teknoloji ve Elektronik",
  "Drone Satıcısı ve Eğitim Merkezi",
  "Bilgisayar ve Laptop Satıcısı",
  "Yazılım Geliştirme Firması",
  "İnternet ve Ağ Hizmeti Sağlayıcısı",
  "Akıllı Ev Sistemleri Firması",
  "Eğitim ve Araştırma",
  "Araştırma ve Geliştirme (AR-GE) Merkezi",
  "Öğrenci Etüt Merkezi",
  "Öğrenci",
  "Bilim ve Teknoloji Müzesi",
  "Deney Atolyesi",
  "Eğitim Yayıncılık Şirketi",
  "Spor ve Aktivite",
  "Spor Ekipmanları Satıcısı",
  "Profesyonel Spor Akademisi",
  "Kayak ve Kış Sporları Merkezi",
  "Atletizm ve Koşu Parkurları",
  "Evcil Hayvan ve Hayvan Sağlığı",
  "Veteriner Klinikleri",
  "Köpek Eğitim Merkezi",
  "Akvaryum Malzemeleri Satıcısı",
  "Tarım ve Kırsal Hizmetler",
  "Zirai İlaç ve Gübre Satıcısı",
  "Kümes Hayvancılığı Malzemeleri Satıcısı",
  "Tarım Makineleri Bayisi",
  "Organik Pazarlar",
  "Kooperatifler ve Tarımsal Üretim Tesisi",
  "Ulaşım ve Taşımacılık",
  "Nakliyat ve Lojistik Firması",
  "Yüksek Hızlı Tren İstasyonu",
  "Şehirler Arası Taşımacılık Firması",
  "Araç Muayene İstasyonu",
  "Kamu ve Resmi Hizmetler",
  "Tapu Kadastro Müdürlüğü",
  "Adliye",
  "Sosyal Hizmet Merkezi",
  "Askerlik Şubesi",
  "Moda ve Stil",
  "Moda Evleri",
  "Haute Couture Tasarım Stüdyosu",
  "Kiralık Kıyafet Hizmeti",
  "Aksesuar Tasarım Mağazası",
  "Saç ve Makyaj Stüdyosu",
  "Hurdacılar ve Geri Dönüşümcüler",
  "Hurda Araç Alım Satım Noktası",
  "Antikacılar",
  "Nostalji Ürünleri Mağazası",
  "Geçici Depolama Hizmeti",
  "İnşaat ve Dekorasyon",
  "Prefabrik Yapı Üreticisi",
  "Mermer ve Granit Satıcısı",
  "İnşaat Proje Danışmanlık Firması",
  "Parke ve Zemin Kaplama Mağazası",
  "Dekoratif Aydınlatma Mağazası",
  "Gıda Üretimi ve İşleme",
  "Süt ve Süt Ürünleri Üreticisi",
  "Unlu Mamul Fabrikası",
  "Meşrubat ve İçecek Üreticisi",
  "Konserve ve Hazır Yemek Üreticisi",
  "Şekerleme ve Çikolata Fabrikası",
  "Baharat İşleme Tesisi",
  "Doğa ve Çevre Hizmeti",
  "Peyzaj ve Bahçe Düzenleme Şirketi",
  "Çevre Danışmanlık Hizmeti",
  "Doğa Rehberliği Firması",
  "Ekolojik Ürün Mağazası",
  "Bitki ve Çiçek Yetiştiricileri",
  "Doğalgaz Şirketi",
  "Akaryakıt İstasyonu",
  "Yenilenebilir Enerji Danışmanlık Firması",
  "Enerji Depolama Sistemleri Tedarikçileri",
  "Isı Yalıtım ve Enerji Verimliliği Uzmanları",
  "Emlak ve Gayrimenkul",
  "Konut ve İş Yeri Kiralama Firması",
  "Toplu Konut Projeleri Üreticisi",
  "Arsa ve Tarla Satış Ofisi",
  "Kentsel Dönüşüm Proje Danışmanlık Firması",
  "Televizyon Kanalı",
  "Gazete ve Dergi Ofisi",
  "Çevrim İçi İçerik Üretim Platformu",
  "Reklam Film Çekim Stüdyosu",
  "Spor ve Rekreasyon",
  "Fitness ve Wellness Merkezi",
  "Açık Hava Spor Tesisi",
  "Golf Kulübü",
  "Yüzme Havuzu ve Aquapark",
  "Binicilik Merkezi",
  "Kültürel Etkinlikler ve Sanat",
  "Sergi ve Galeri Mekanı",
  "Halk Eğitim Merkezi",
  "Geleneksel El Sanatları Atolyesi",
  "Uluslararası Film ve Sanat Festivalleri",
  "Yat Üretim ve Satış Firması",
  "Dalış Kursları ve Merkezi",
  "Rüzgar Sörfü Eğitim Alanı",
  "Balıkçılık Malzemeleri Satıcısı",
  "Çocuk ve Eğitim",
  "Kreş ve Gündüz Bakım Evleri",
  "Çocuk Etkinlik Merkezi",
  "Zekâ Geliştirme Oyuncakları Mağazası",
  "Özel Eğitim ve Rehabilitasyon Merkezi",
  "Çocuk Festivalleri Organizasyonları",
  "Gelinlik ve Abiye Mağazası",
  "Damatlık ve Erkek Giyim Butikleri",
  "Çocuk Giyim Mağazası",
  "Spor Giyim Mağazası",
  "Kışlık Giysi ve Ayakkabı Satıcısı",
  "Güvenlik ve Koruma",
  "CCTV Kamera ve Alarm Sistemleri Satıcısı",
  "Yangın Söndürme Ekipmanları Mağazası",
  "Risk Yönetimi ve Güvenlik Danışmanlıkları",
  "Çelik Kapı ve Güvenlik Sistemleri Üreticisi",
  "Lojistik ve Depolama",
  "Uluslararası Kargo Firması",
  "Soğuk Hava Depoları",
  "Depolama ve Stoklama Hizmeti",
  "Taşımacılık ve Nakliyat Şirketi",
  "Kargo Dağıtım Şubesi",
  "Lojistik Danışmanlık Firması",
  "Zanaat ve El Sanatları",
  "Deri İşleme Atolyesi",
  "Halı Dokuma Atolyesi",
  "Marangozlar ve Ahşap İşleme Atolyesi",
  "Takı ve Mücevher Tasarım Atolyesi",
  "Teknoloji ve Yazılım",
  "Web Tasarım ve SEO Hizmeti",
  "Veri Analitik ve Bulut Bilişim Şirketi",
  "Oyun Geliştirme Stüdyosu",
  "Yapay Zeka ve Robotik Çalışma Merkezi",
  "Tohum ve Fide Satıcısı",
  "Büyükbaş ve Küçükbaş Hayvan Çiftlikleri",
  "Organik Yumurta ve Süt Üreticisi",
  "Modern Sera Sistemleri Üreticisi",
  "Hayvan Bakım Ürünleri Tedarikçileri",
  "Toptan ve Ticaret",
  "Toptancı Hal ve Depolar",
  "Gıda Toptancısı",
  "Elektrik ve Elektronik Ürün Toptancısı",
  "İnşaat Malzemesi Toptancısı",
  "Kimyasal Ürün Toptancısı",
  "Yol ve Köprü İnşaat Firması",
  "Baraj ve HES Proje Yapan Şirket",
  "İleri Teknoloji Altyapı Firması",
  "Kentsel Yenileme ve Restorasyon Şirketi",
  "İnşaat Mühendislik Danışmanlık Hizmeti",
  "Sağlık ve Medikal",
  "Tıbbi Cihaz Satıcısı",
  "Medikal Sarf Malzeme Tedarikçileri",
  "Ambulans Hizmeti",
  "Sağlık Turizmi Acentesi",
  "Yaşlı ve Hasta Bakım Evleri",
  "Plastik Geri Dönüşüm Tesisi",
  "Elektronik Atık İşleme Merkezi",
  "Kağıt ve Karton Geri Dönüşümcüler",
  "Doğal Enerji Kaynakları Araştırma Firması",
  "Çevre Eğitim ve Bilinçlendirme Programları",
  "İletişim ve Telekomünikasyon",
  "Uydu ve Anten Hizmeti",
  "Çağrı Merkezi Hizmeti",
  "Telefon Tamir ve Teknik Destek Noktası",
  "Fiber Optik Altyapı Hizmeti",
  "Eğitim ve Akademik",
  "STEM Eğitim Merkezi",
  "Özel Akademik Araştırma Enstitüleri",
  "Eğitim Materyali ve Teknolojisi Sağlayıcısı",
  "Üniversite ve Mezun Derneği",
  "Eğlence ve Organizasyon",
  "Ses ve Işık Sistemleri Kiralama Hizmeti",
  "Parti Malzemeleri Mağazası",
  "Konser ve Etkinlik Mekanı",
  "Organizasyon Danışmanlık Firması",
  "Turizm ve Seyahat",
  "Doğa ve Macera Turları Düzenleyen Firmalar",
  "Kültür Turları Organizatörleri",
  "Kaplıca ve Termal Tesisler",
  "Kamp ve Karavan Hizmeti Sağlayan Şirket",
  "Zeytinyağı ve Zeytin İşleme Tesisi",
  "Dondurma ve Tatlı Üreticisi",
  "Kurutulmuş Meyve ve Ceviz İşleme Tesisi",
  "Alkollü ve Alkolsüz İçecek Üreticisi",
  "Baharat ve Bitki Çayı Paketleme Firması",
  "El Sanatları ve Zanaat",
  "Seramik ve Porselen Atolyesi",
  "Ahşap Oyma ve Mobilya Üreticisi",
  "Dokuma ve İplik Üreticisi",
  "Geleneksel Takı Tasarımı ve Üretimi",
  "Minyatür ve Hat Sanatı Atolyesi",
  "Satış Ofisi",
  "Arsa ve Tarla Danışmanlık Firması",
  "Emlak Yönetim Şirketi",
  "Kiralama ve Taahhüt Firması",
  "Kat Mülkiyeti ve Site Yönetim Hizmeti",
  "Güneş Paneli Üreticisi ve Montaj Firması",
  "Elektrik Dağıtım ve Üretim Firması",
  "Rüzgar Türbini Üreticisi",
  "Biyogaz ve Atık Yönetimi Tesisi",
  "Hidroelektrik Santral (HES) İşletmesi",
  "İmalat ve Üretim",
  "Metal İşleme ve Kaynak Atolyesi",
  "Otomotiv Parça Üreticisi",
  "Plastik Kalıp ve Enjeksiyon Fabrikası",
  "Kimyasal Ürün Üreticisi",
  "Ambalaj ve Paketleme Tesisi",
  "Dijital Hizmetler",
  "Çevrim İçi Eğitim Portalları",
  "E-ticaret Danışmanlık Firması",
  "SEO ve Dijital Reklam Ajansı",
  "Mobil Uygulama Geliştirme Şirketi",
  "Video Üretim ve Yayın Hizmeti",
  "Sanayi ve Altyapı",
  "Ağır Makine Üreticisi",
  "Endüstriyel Bakım ve Onarım Firması",
  "Boru ve Çelik İşleme Fabrikası",
  "Fabrika ve Depo İnşaat Şirketi",
  "Endüstriyel Yedek Parça Tedarikçileri",
  "Tarım ve Gıda İşletmesi",
  "Fidanlıklar ve Bahçe Malzemeleri Satıcısı",
  "Büyükbaş Hayvancılık Çiftlikleri",
  "Organik Ürün Kooperatifi",
  "Balık Üretme ve İşleme Tesisi",
  "Modern Seracılık Teknolojisi Sağlayıcısı",
  "Eğitim ve Akademik Hizmetler",
  "Dil Eğitim Merkezi",
  "Burs Veren Vakıf ve Kurum",
  "Akademik Yayın ve Kitapçılar",
  "Sınav Hazırlık Kursları",
  "Online Ders ve Ödev Platformu",
  "Sosyal ve Toplum Hizmeti",
  "Yaşlı Bakım ve Rehabilitasyon Merkezi",
  "Psikolojik Danışmanlık Hizmeti",
  "Kadın Sığınma Evleri",
  "Çocuk Esirgeme ve Koruma Kuruluşu",
  "Engelli Destek ve Eğitim Merkezi",
  "Spor ve Fiziksel Aktivite",
  "Kapalı Spor Salonu",
  "Bireysel Antrenör Hizmeti",
  "Doğa Sporları Organizasyonları",
  "Su Sporları Eğitmenleri",
  "Esneklik ve Yoga Stüdyosu",
  "Spor Ayakkabı Mağazası",
  "Vintage ve İkinci El Giyim Butikleri",
  "Çanta ve Aksesuar Satıcısı",
  "Özel Sipariş Giyim Tasarımcıları",
  "Tekstil Boyama ve Tamir Atolyesi",
  "Medya ve Sanat",
  "İnfluencer ve İçerik Üretim Ajansı",
  "Belgesel ve Film Prodüksiyon Şirketi",
  "Grafik Tasarım ve Animasyon Atolyesi",
  "Dijital Sanat Üretim Stüdyosu",
  "Kamu Hizmeti",
  "Belediye Hizmeti (Parklar, Temizlik, vb.)",
  "Postaneler",
  "Elektrik ve Su İdaresi Şubesi",
  "Tapu ve Kadastro Müdürlüğü",
  "Sosyal Güvenlik Kurumu",
  "Bungalov ve Dağ Evleri",
  "Şehir Turları Düzenleyen Firmalar",
  "Tarihi Mekanlar ve Rehberlik Hizmeti",
  "Butik Oteller ve Misafirhaneler",
  "Kamp ve Karavan Kiralama Hizmeti",
  "Şehir İçi Minibüs ve Otobüs Kooperatifi",
  "Özel Limuzin ve VIP Araç Kiralama Hizmeti",
  "Helikopter ve Özel Jet Kiralama Şirketi",
  "Otobüs Terminalleri ve Seyahat Acentesi",
  "Finans ve Sigorta",
  "Sigorta Brokerleri ve Acentesi",
  "Finansal Danışmanlık Hizmeti",
  "Yatırım Şirketi",
  "Leasing ve Finansal Kiralama Firması",
  "Kredi Kartı Hizmeti Sunan Kurum",
  "Sağlık ve Alternatif Tıp",
  "Diş Sağlığı ve Estetik Merkezi",
  "Akupunktur ve Refleksoloji Merkezi",
  "Estetik ve Plastik Cerrahi Klinikleri",
  "Spa ve Termal Tedavi Merkezi",
  "Beslenme ve Diyet Danışmanlık Merkezi",
  "Eğitim ve Öğretim",
  "Kodlama ve Yazılım Kursları",
  "Robotik ve STEM Atolyesi",
  "Online Sınav ve Sertifika Platformu",
  "Resim ve Müzik Kursları",
  "Çocuk Gelişim Atolyesi",
  "Doğa ve Çevre",
  "Doğa Koruma ve Araştırma Derneği",
  "Milli Parklar ve Koruma Alanı",
  "Çevre ve Atık Yönetimi Danışmanlık Firması",
  "Topluluk Bahçeciliği Girişimleri",
  "Enerji Verimliliği Eğitim ve Denetim Hizmeti",
  "Kültürel Hizmetler",
  "Dil ve Kültür Merkezi",
  "Ulusal ve Uluslararası Fuar Organizatörleri",
  "Kültürel Miras Restorasyon Şirketi",
  "Geleneksel Müzik ve Dans Grupları",
  "Şehir Tiyatroları ve Opera Binaları",
  "Hobi ve Eğlence",
  "Drone Uçuş Alanı ve Eğitmenleri",
  "Hobi Bahçeleri Kiralama Hizmeti",
  "Elektrikli Scooter ve Bisiklet Kiralama Şirketi",
  "Koleksiyon ve Antika Satış Mağazası",
  "Hobi Malzemeleri ve Kit Mağazası",
  "Hukuk Bürosu ve Avukatlar",
  "Arabuluculuk ve Alternatif Çözüm Merkezi",
  "İş ve Ticaret Hukuku Danışmanlık Hizmeti",
  "Fikri Mülkiyet ve Patent Hizmeti",
  "Göçmenlik ve Vize Danışmanlık Ofisi",
  "Arıcılık ve Bal Üretim Çiftlikleri",
  "Tavuk Çiftlikleri ve Yumurta Üretim Tesisi",
  "Zirai Danışmanlık Hizmeti",
  "Hayvan Yem Üreticisi",
  "Sulama Sistemleri Üreten Firmalar",
  "Elektronik ve Teknoloji",
  "Cep Telefonu Tamir ve Teknik Servis Noktası",
  "Oyun Konsolu ve Aksesuar Satıcısı",
  "Güvenlik Yazılımı Geliştiren Firmalar",
  "Akıllı Teknolojiler ve IoT Sistemleri Sağlayıcısı",
  "Güzellik ve Bakım",
  "Kozmetik ve Kişisel Bakım Mağazası",
  "Lazer Epilasyon ve Cilt Bakım Merkezi",
  "Saç Ekimi ve Tedavi Klinikleri",
  "Güzellik Yarışmaları ve Organizasyon Firması",
  "Profesyonel Temizlik Şirketi",
  "Haşere Kontrol ve İlaçlama Hizmeti",
  "Kombi ve Klima Bakım Servisi",
  "Ev Eşyası Kiralama Hizmeti",
  "Eğlence ve Etkinlik Organizasyonu",
  "Düğün ve Nişan Organizasyon Şirketi",
  "Çocuk Doğum Günü ve Animasyon Hizmeti",
  "Kına Gecesi ve Geleneksel Etkinlik Organizasyonları",
  "Festival ve Konser Bilet Satış Noktası",
  "İnşaat ve Taşımacılık",
  "Vinç Kiralama Hizmeti",
  "Tünel ve Metro İnşaat Firması",
  "Yalıtım ve Mantolama Şirketi",
  "Prefabrik Yapı İnşa Eden Şirket",
  "Yol ve Otoyol İnşaat Şirketi",
  "Denizcilik ve Lojistik",
  "Gemi ve Tekne Kiralama Hizmeti",
  "Marina ve Yat Limanları",
  "Deniz Taşımacılığı Firması",
  "Balıkçılık ve Deniz Ürünleri İşleme Merkezi",
  "Yat Yapımı ve Bakımı Hizmeti",
  "Evcil Hayvan ve Veterinerlik",
  "Pet Shop ve Hayvan Malzemeleri Satıcısı",
  "Evcil Hayvan Oteli",
  "Veteriner Klinik ve Hastaneleri",
  "Hayvan Eğitimi ve Davranış Danışmanlıkları",
  "Sokak Hayvanları Koruma ve Tedavi Merkezi",
  "Oto Yıkama ve Detaylı Temizlik Servisi",
  "Araç Kaplama ve Modifiye Atolyesi",
  "İkinci El Araç Galerileri",
  "Oto Kiralama Hizmeti",
  "Lastik Değişimi ve Tamir Servisi",
  "Ambalaj ve Etiketleme Firması",
  "Gıda İşleme Makinaları Üreticisi",
  "Çelik Konstrüksiyon ve Fabrika Binaları Üretimi",
  "Endüstriyel Ekipman ve Makine Tedarikçileri",
  "Cam ve Plastik Ürün Üretim Fabrikası",
  "Turizm ve Rekreasyon",
  "Kayak Merkezi ve Tesisi",
  "Tarihi Yerler ve Rehberlik Hizmeti",
  "Macera Parkları ve Zipline Alanı",
  "Eko Turizm ve Doğa Yürüyüşleri Organizasyonları",
  "Tekne Turları ve Su Sporları Hizmeti",
  "Finans ve Ekonomi",
  "Kripto Para Danışmanlık Hizmeti",
  "Bankacılık ve Finans Teknolojileri Firması",
  "Mikro Kredi Sağlayan Kurum",
  "Risk Yönetimi ve Portföy Danışmanlık Şirketi",
  "Özel Dikim Moda Evleri",
  "Tişört ve Promosyon Ürünleri Üreticisi",
  "Kumaş ve Tekstil Ürünleri Mağazası",
  "Ayakkabı ve Deri Ürünleri Atolyesi",
  "Ünlü Tasarımcı Mağazası",
  "Gıda ve Restoranlar",
  "Vegan ve Vejetaryen Restoranlar",
  "Gurme Yemek Lokantası",
  "Pastane ve Tatlıcılar",
  "Kahve Dükkanları ve Kafeler",
  "Eğlence ve Medya",
  "Sinema ve Film Prodüksiyon Stüdyosu",
  "İnfluencer ve Sosyal Medya Ajansı",
  "Online Yayın ve Video Platformu",
  "Video Kurgu ve Animasyon Hizmeti",
  "Dijital İçerik Üretim Atolyesi",
  "Bahçe ve Peyzaj",
  "Bahçe Düzenleme ve Çim Alan Hizmeti",
  "Bitki ve Çiçek Satış Mağazası",
  "Peyzaj Mimarlığı Danışmanlık Hizmeti",
  "Bahçe Mobilyaları ve Dekorasyon Ürünleri",
  "Sulama Sistemleri Montaj Hizmeti",
  "Bilgi Teknolojileri",
  "Siber Güvenlik Danışmanlık Şirketi",
  "Blockchain ve Kripto Yazılım Firması",
  "E-Ticaret Platform Sağlayıcısı",
  "Veri Merkezi ve Hosting Hizmeti",
  "IT ve Teknoloji Eğitim Firması",
  "Ziraat ve Gıda Teknolojileri",
  "Modern Sulama Teknolojisi Sağlayıcısı",
  "Tarım Makineleri Üreticisi",
  "Gıda Kalite ve Güvenlik Kontrol Laboratuvarları",
  "Tarımsal İlaç ve Gübre Satıcısı",
  "Organik Tarım Ürünleri Marketi",
  "Kişisel Gelişim ve Danışmanlık",
  "Hayat Koçluğu ve Kişisel Gelişim Merkezi",
  "Aile ve Evlilik Danışmanlık Hizmeti",
  "Stres Yönetimi ve Zihin Haritalama Atolyesi",
  "NLP (Neuro-Linguistic Programming) Eğitim Merkezi",
  "Çocuk ve Gençlik Gelişim Merkezi",
  "Yüzme Havuzları ve Kulübü",
  "Profesyonel Antrenörler ve Spor Eğitimcileri",
  "Spor Takımları için Tesisler ve Akademiler",
  "Açık Hava Fitness Parkurları",
  "Tenis ve Golf Sahaları",
  "Dayanıklı Tüketim ve Elektrikli Aletler",
  "Elektronik Ürün Servis ve Satış Noktası",
  "Beyaz Eşya Bayisi ve Servisi",
  "Akıllı Ev Sistemleri Satış Noktası",
  "Ev Sinema ve Ses Sistemleri Üreticisi",
  "Küçük Ev Aletleri Tamir Hizmeti",
  "Mühendislik ve Proje Hizmeti",
  "Mekanik Tesisat ve HVAC Danışmanlık Firması",
  "Jeolojik ve Topografik Araştırma Şirketi",
  "Mimarlık ve Tasarım Ofisi",
  "Bina Enerji Verimliliği Danışmanlık Firması",
  "İnşaat Malzemesi Test ve Denetim Laboratuvarları",
  "CCTV Kamera ve Güvenlik Sistemleri Sağlayıcısı",
  "Alarm ve Yangın Güvenliği Firması",
  "Güvenlik Eğitim ve Sertifikasyon Merkezi",
  "Kasa ve Güvenlik Ekipmanları Üreticisi",
  "Hukuk ve Adalet",
  "Tercüme ve Hukuki Çeviri Ofisi",
  "Uluslararası Hukuk Danışmanları",
  "Adli Bilişim ve Dijital Delil Analiz Merkezi",
  "Vergi ve Ticaret Hukuku Uzmanları",
  "Sözleşme Hazırlama ve Danışmanlık Hizmeti",
  "Akıllı Tahta ve Eğitim Cihazı Üreticisi",
  "Dijital Eğitim İçeriği Sağlayıcısı",
  "Online Eğitim ve Webinar Platformu",
  "Simülasyon Eğitim ve VR Teknolojisi Üreticisi",
  "Üniversite ve Okul Laboratuvar Sistemleri Sağlayıcısı",
  "Taşımacılık ve Ulaştırma",
  "Hızlı Tren ve Metro Proje Şirketi",
  "Kargo İzleme ve Yönetim Sistemleri",
  "Lojistik Depo ve Nakliye Şirketi",
  "Özel Yolcu Taşımacılığı Hizmeti",
  "Uluslararası Deniz ve Hava Taşımacılığı Firması",
  "Kozmetik ve Moda",
  "Profesyonel Kuaför ve Makyaj Sanatçıları",
  "Kozmetik Ürün Test ve Üretim Firması",
  "Kişisel Stil ve Moda Danışmanları",
  "Parfüm ve Koku Ürünleri Üreticisi",
  "Özel Dikim Gelinlik ve Abiye Atolyesi",
  "Eğlence ve Oyun",
  "Çevrim İçi ve Masaüstü Oyun Mağazası",
  "Escape Room ve Macera Evleri",
  "Sanal Gerçeklik Oyun Merkezi",
  "Çocuk Eğlence Parkları ve Trambolin Alanı",
  "Turnuva ve Espor Organizasyonları",
  "Rüzgar ve Güneş Enerjisi Danışmanlık Firması",
  "Yeşil Bina Sertifikasyon Hizmeti",
  "İklim Değişikliği Araştırma Merkezi",
  "Atık Su Yönetimi ve Arıtma Sistemleri",
  "Karbon Ayak İzi Azaltma Proje Danışmanlıkları",
  "Mobilya ve Dekorasyon",
  "Özel Mobilya Tasarım Atolyesi",
  "Ofis Mobilyası Üreticisi",
  "Perde ve Döşemelik Kumaş Satıcısı",
  "Ev Dekorasyon Aksesuar Mağazası",
  "Ahşap ve Metal Dekor Ürünleri Üreticisi",
  "İletişim ve Medya",
  "Halkla İlişkiler ve İletişim Danışmanlık Şirketi",
  "Radyo ve Podcast Yayıncıları",
  "Dijital İçerik Platformu",
  "Gazete ve Dergi Yayıncıları",
  "Robotik Kodlama ve STEM Eğitim Merkezi",
  "Satranç ve Zeka Oyunları Kursları",
  "Çocuk Tiyatrosu ve Sanat Atolyesi",
  "Sertifika Programı Sunan Eğitim Kurumu",
  "Özel Depolama Alanı Kiralama Şirketi",
  "Paketleme ve Lojistik Firması",
  "Ağır Yük ve Proje Lojistik Şirketi",
  "Liman Hizmeti ve Nakliye Firması",
  "Asansör ve Yürüyen Merdiven Üreticisi",
  "Çatı ve İzolasyon Malzemeleri Tedarikçileri",
  "Prefabrik ve Modüler Yapı Firması",
  "Beton ve İnşaat Malzemeleri Satıcısı",
  "Yapı Denetim ve Proje Yönetim Firması",
  "Gıda ve Tarım Ürünleri",
  "Yerel Üretici Pazarları",
  "Zeytinyağı ve Doğal Ürün Satış Noktası",
  "Hububat ve Bakliyat Üreticisi",
  "Tarım Ekipmanları Satış ve Tamir Hizmeti",
  "Tohum ve Fidan Üreticisi",
  "Rehabilitasyon Cihazları Üreticisi",
  "Medikal Ekipman ve Malzeme Tedarikçileri",
  "Psikoterapi ve Grup Terapi Hizmeti",
  "Sağlık Teknolojileri Geliştiren Şirket",
  "Diyabet ve Kronik Hastalık Yönetim Hizmeti",
  "Açık Hava Spor Ekipmanları Satıcısı",
  "Sporcu Besin ve Takviye Ürünleri Mağazası",
  "Yoga ve Meditasyon Eğitim Merkezi",
  "Koşu ve Bisiklet Kulübü",
  "Spor Kompleksleri ve Çok Amaçlı Salonlar",
  "Konaklama ve Tatil",
  "Glamping (Lüks Kamp) Tesisi",
  "Tatil Köyleri ve Yazlık Ev Kiralama Hizmeti",
  "Aileye Yönelik Tatil Alanı",
  "Deniz ve Dağ Tatil Organizatörleri",
  "Kültür Turu ve Gezi Firması",
  "Sanayi ve Teknoloji",
  "3D Yazıcı Üreticisi ve Hizmeti",
  "Endüstriyel Robot Üreticisi",
  "İleri Malzeme ve Nanoteknoloji Şirketi",
  "Veri Analizi ve Büyük Veri Çözümleri Sağlayıcısı",
  "Elektronik Devre ve Çip Üreticisi",
  "Toplum Hizmeti",
  "Kan Bağışı ve Organ Nakli Merkezi",
  "Kriz Merkezi ve Acil Yardım Hatları",
  "Gönüllü ve Sivil Toplum Kuruluşu",
  "Toplum Merkezi ve Gençlik Programları",
  "Bağımlılık Tedavi ve Rehabilitasyon Merkezi",
  "Moda ve Tasarım",
  "Tekstil Baskı ve Desen Tasarım Atolyesi",
  "Moda Fotoğrafçılığı Stüdyosu",
  "Özel Ayakkabı ve Çanta Tasarımcıları",
  "Takı Tasarım ve Üretim Firması",
  "Moda Show ve Defile Organizasyonları",
  "Eğlence ve Teknoloji",
  "Sanal Gerçeklik Oyun Salonu",
  "Oyun Konsolu ve VR Cihaz Satış Noktası",
  "İnteraktif Sergi ve Etkinlik Organizatörleri",
  "Çevrim İçi Film ve Dizi Platformu",
  "Mobil Oyun Geliştirme Şirketi",
  "Sosyal ve Toplumsal Hizmetler",
  "Yaşlı Bakım ve Huzurevi Hizmeti",
  "Kadın Sığınma ve Destek Merkezi",
  "Çocuk Esirgeme ve Rehabilitasyon Kurumu",
  "Engelli Destek ve Danışmanlık Merkezi",
  "Sosyal Yardım ve Gıda Bankaları",
  "Yeme-İçme ve Konaklama Hizmeti",
  "Gurme Restoran ve Şarap Evleri",
  "Sokak Lezzetleri ve Mobil Yemek Araçları",
  "Çiftlikte Kahvaltı ve Yerel Lezzet Deneyimleri",
  "Butik Oteller ve Konuk Evleri",
  "Sanat ve Zanaat",
  "Seramik ve Cam Atolyesi",
  "Ahşap Oyma ve Marangoz Atolyesi",
  "Ebru Sanatı ve Kaligrafi Kursları",
  "Geleneksel El Sanatları ve Hediyelik Ürün Satıcısı",
  "Modern Sanat Galerileri ve Sergi Salonu",
  "Çevre ve Yenilenebilir Enerji",
  "Elektrikli Araç Şarj İstasyonu İşletmesi",
  "Atık Geri Dönüşüm ve Yeniden Kullanım Merkezi",
  "Güneş Paneli Üretim ve Montaj Şirketi",
  "Biyogaz ve Yeşil Enerji Üretim Firması",
  "Çevre Eğitim ve Bilinçlendirme Kuruluşu",
  "Bilişim ve Dijital Hizmetler",
  "Web Tasarım ve SEO Ajansı",
  "Dijital Pazarlama ve Sosyal Medya Danışmanlıkları",
  "Bulut Bilişim ve Veri Yedekleme Hizmeti",
  "Yapay Zeka ve Makine Öğrenimi Çözümleri",
  "Arsa ve Tarla Danışmanlık Hizmeti",
  "Lüks ve Premium Gayrimenkul Ajansı",
  "İnşaat Projesi Satış Ofisi",
  "Emlak Değerleme ve Danışmanlık Firması",
  "Konut ve Ticari Kiralama Ofisi",
  "Büyük Zincir Marketler",
  "Yerel Pazarlar ve Organik Ürün Satıcısı",
  "Kıyafet ve Aksesuar Mağazası",
  "Elektronik Cihaz Mağazası",
  "Oyuncak ve Çocuk Ürünleri Satıcısı",
  "Taşımacılık ve Dağıtım",
  "Uluslararası Nakliye ve Lojistik Firması",
  "Kurye ve Paket Teslim Hizmeti",
  "Özel Şoför Hizmeti Sağlayan Firmalar",
  "Hızlı Teslimat ve E-Ticaret Dağıtım Acentesi",
  "Demiryolu ve Hava Kargo Taşımacılığı",
  "Bilim ve Araştırma",
  "Teknoloji Geliştirme ve Araştırma Merkezi",
  "Bilim Müzesi ve Eğitim Atolyesi",
  "Laboratuvar Test ve Analiz Hizmeti",
  "Uzay Araştırmaları ve Teknoloji Şirketi",
  "Genetik ve Biyoteknoloji Geliştirme Firması",
  "Çocuk Eğlence Parkları ve Lunaparklar",
  "Su Parkları ve Akvaryumlar",
  "Açık Hava Sinemaları ve Tiyatrolar",
  "Kamp ve Doğa Yürüyüşü Organizasyonları",
  "Balon Turları ve Hava Sporları Merkezi",
  "Sağlık ve Wellness",
  "Alternatif Tıp ve Akupunktur Merkezi",
  "Spa ve Wellness Retreat Merkezi",
  "Sağlık Koçluğu ve Beslenme Danışmanlığı",
  "Hamam ve Geleneksel Banyo Hizmeti",
  "Fitness Stüdyosu ve Pilates Salonu",
  "Elektrik ve Doğalgaz Dağıtım Şirketi",
  "Biyodizel ve Yenilenebilir Yakıt Üreticisi",
  "Petrol ve Akaryakıt İstasyonu",
  "Enerji Tasarrufu Danışmanlık Firması",
  "Elektrik Üretim ve Dağıtım Tesisi",
];
