part of 'jobs.dart';

final List<String> _jobsPart1 = <String>[
  "Sanatçı",
  "Müzisyen",
  "Avukat",
  "Ürün Hizmet",
  "Esnaf",
  "Giyim",
  "Dijital İçerik Üreticisi",
  "Video İçeriği Üreticisi",
  "Dijital Pazarlama Uzmanı",
  "Yazılım Mühendisi",
  "Eğitim",
  "Girişimci",
  "Sağlık/Güzellik",
  "Editör",
  "Yazar",
  "Kişisel",
  "Mühendis",
  "Doktor",
  "Yönetici",
  "Öğretmen",
  "Öğrenci",
  "3D Yazıcı Mağazası",
  "Acenta",
  "Acil Durum Yönetim Merkezi",
  "Acil Durum Yönetmeni",
  "Acil Tıp Teknisyeni",
  "Acil Tıp Uzmanı",
  "Açık Hava Konser Alanı",
  "Açık Hava Spor Etkinlik Alanı",
  "Açık Hava Tiyatroları",
  "Adli Tabip",
  "Adli Tıp Uzmanı",
  "Afet ve Acil Durum Yardım Merkezi",
  "Afet Yönetim Eğitim Merkezi",
  "Agronomist",
  "Ağ Yöneticisi",
  "Ahşap İşleme Atolyesi",
  "Ahşap Tekne Yapımcısı",
  "Aile Hekimi",
  "Ajans",
  "Akıllı Enerji Yönetim Sistemleri",
  "Akıllı Ev Sistemleri Satıcısı",
  "Akıllı Sera Sistemleri",
  "Akıllı Tarım Şirketi",
  "Akortçu",
  "Akrobat",
  "Aktar",
  "Aktör",
  "Aktris",
  "Aktüer",
  "Akustikçi",
  "Alarm ve Kamera Sistemleri",
  "Alışveriş Merkezi (AVM)",
  "Alışveriş ve Perakende",
  "Alışveriş ve Ticaret",
  "Alışveriş ve Tüketim",
  "Alternatif Sağlık ve Terapi",
  "Alternatif Tıp Merkezi",
  "Alternatif Tıp Uygulamaları",
  "Altın ve Değerli Maden Yatırımcıları",
  "Altyapı Teknolojileri",
  "Amatör Spor Kulübü",
  "Ambalajcı",
  "Ambarcı",
  "Ambulans Şoförü",
  "Anahtarcı",
  "Analist",
  "Anaokulu",
  "Anestezi Teknikeri",
  "Anestezi Uzmanı",
  "Animasyon Stüdyosu",
  "Animatör",
  "Anne-Baba Danışmanlık Merkezi",
  "Antika İşletme",
  "Antrenör",
  "Antropolog",
  "Apartman Yöneticisi",
  "Aqua Park",
  "Araba İşletme",
  "Araba Tamircisi",
  "Araba Yıkayıcısı",
  "Arabulucu",
  "Arabuluculuk Merkezi",
  "Araç Kiralama Firması",
  "Araç Kiralama Ofisi",
  "Araştırma Laboratuvarı",
  "Araştırma Merkezi",
  "Araştırmacı",
  "Arıcı",
  "Arıcılık İşletmesi",
  "Arkeolog",
  "Arkeoloji Derneği",
  "Armatör",
  "Arpist",
  "Arşivci",
  "Artist",
  "Asansörcü",
  "Asistan",
  "Asker",
  "Askeri Tedarikçiler",
  "Astrofizikçi",
  "Astrolog",
  "Astronom",
  "Astronot",
  "Aşçı",
  "Aşçıbaşı",
  "Atık Yönetimi Firması",
  "Atlet",
  "Av Bekçisi",
  "Avcı",
  "Avukat",
  "Ayakkabı Mağazası",
  "Ayakkabı Tamircileri",
  "Ayakkabı Tamircisi",
  "Ayakkabıcı",
  "Bacacı",
  "Badanacı",
  "Bağımsız İşletme",
  "Bağımsız Medya Destek Organizasyonları",
  "Baharatçı",
  "Baharatçılar",
  "Bahçe Bitkileri Uzmanı",
  "Bahçe Düzenleme Firması",
  "Bahçe Mobilyası Üreticisi",
  "Bahçe ve Tarım Aletleri",
  "Bahçıvan",
  "Bakan",
  "Bakıcı",
  "Bakımevleri",
  "Bakır ve Kalay İşletmecisi",
  "Bakırcı",
  "Bakkal",
  "Bakkallar",
  "Bakteriyolog",
  "Balerin",
  "Balık Lokantası",
  "Balıkçı Barınakları",
  "Balıkçı",
  "Balıkçılık Kooperatifi",
  "Balıkçılık Şirketi",
  "Balon Pilotu",
  "Banka",
  "Bankacı",
  "Bankacılık ve Finans",
  "Bankalar",
  "Banker",
  "Barmeyd",
  "Basketbolcu",
  "Başhemşire",
  "Başkan",
  "Bebek Bakıcısı",
  "Bebek Bakım Hizmeti",
  "Bebek Ürünleri Mağazası",
  "Bekçi",
  "Belediye Başkanı",
  "Belediye Meclisi Üyesi",
  "Belediyeler",
  "Benzin İstasyonu",
  "Benzinci",
  "Berber",
  "Besicilik",
  "Besteci",
  "Beyaz Eşya Bayisi",
  "Bilardo Salonu",
  "Biletçi",
  "Bilgi İşlemci",
  "Bilgisayar Mühendisi",
  "Bilgisayar Programcısı",
  "Bilgisayar Tamircisi",
  "Bilgisayar Teknisyeni",
  "Bilim İnsanı",
  "Bilim Merkezi",
  "Bilim ve Teknoloji",
  "Bilirkişi",
  "Bilişim Sistemleri Mühendisi",
  "Binicilik",
  "Bisiklet Mağazası",
  "Bisikletçi",
  "Biyografi Yazarı",
  "Biyolog",
  "Biyolojik Çeşitlilik Araştırma Merkezi",
  "Biyomedikal Mühendisi",
  "Biyoyakıt Üretim Şirketi",
  "Bobinajcı",
  "Borsacı",
  "Botanikçi",
  "Bowling Salonu",
  "Boya ve Badana İşletmesi",
  "Boya ve Dekorasyon Mağazası",
  "Boyacı",
  "Bozacı",
  "Bölgesel Kalkınma Ajansı",
  "Börekçi",
  "Broker",
  "Bulaşıkçı",
  "Buldozer Operatörü",
  "Butik Oteller",
  "Butik",
  "Büfeler",
  "Bütçe Uzmanı",
  "Büyükelçi",
  "Büyükelçilik",
  "Cam Üfleme Atolyesi",
  "Cam ve Plastik Toplama Noktası",
  "Camcı",
  "Camiler",
  "Canlı Müzik Mekanı",
  "Canlı Yayın Platformu",
  "Catering Şirketi",
  "Celep",
  "Cellat",
  "Cem Evleri",
  "Cep Telefonu Mağazası",
  "Cerrah",
  "Cost Control",
  "Çalışma Alanı Kiralama Hizmeti",
  "Çamaşırcı",
  "Çamaşırhane",
  "Çamaşırhaneler",
  "Çanta ve Aksesuar Mağazası",
  "Çantacı",
  "Çarkçı",
  "Çatıcı",
  "Çaycı",
  "Çevirmen",
  "Çevre Danışmanlık Firması",
  "Çevre Koruma Derneği",
  "Çevre Mühendisi",
  "Çevre Teknolojileri Geliştiren Firmalar",
  "Çevre Temizlik Hizmeti",
  "Çevre ve Geri Dönüşüm",
  "Çevre ve İklim Çözümleri",
  "Çevre ve Peyzaj",
  "Çevrebilimci",
  "Çevrim İçi Mentorluk Hizmeti",
  "Çevrim İçi Sertifika Programları",
  "Çeyizci",
  "Çıkıkçı",
  "Çıkrıkçı",
  "Çımacı",
  "Çırak",
  "Çiçekçi",
  "Çiçekçiler",
  "Çiftçi",
  "Çiftlik İşletici",
  "Çiftlikler",
  "Çiğ Köfteciler",
  "Çikolatacı",
  "Çilingir",
  "Çilingirler",
  "Çim Biçme ve Peyzaj Ekipmanları Mağazası",
  "Çim Tohumu ve Peyzaj Hizmeti",
  "Çinici",
  "Çitçi",
  "Çoban",
  "Çocuk Bakım Merkezi",
  "Çocuk Doktoru",
  "Çocuk Eğitimi ve Gelişimi Merkezi",
  "Çocuk Eğlence Parkları",
  "Çocuk Esirgeme Kurumu",
  "Çocuk Koruma Merkezi",
  "Çocuk Kulübü",
  "Çocuk Oyun Alanı",
  "Çocuk Psikolojisi Danışmanlık Merkezi",
  "Çocuk ve Aile",
  "Çocuk ve Gençlik",
  "Çokuluslu Şirket Ofisi",
  "Çorapçı",
  "Çöpçü",
  "Dadı",
  "Dağ Evleri",
  "Dağcılık ve Tırmanış Merkezi",
  "Dağıtım Firması",
  "Daktilograf",
  "Dalgıç",
  "Dalış Okulları",
  "Damıtıcı",
  "Danışman",
  "Danışmanlık Firması",
  "Dans Akademisi",
  "Dans Kursları",
  "Dans Stüdyosu",
  "Dansçı",
  "Dayanıklı Tüketim ve Elektronik",
  "Dedektif",
  "Değirmenci",
  "Dekorasyon Mağazası",
  "Dekoratif İnşaat Malzemesi Satan Mağaza",
  "Demirci Atolyesi",
  "Demirci",
  "Demiryolu İşçisi",
  "İşçi",
  "Denetçi",
  "Denetleyici",
  "Deniz Bilimi Araştırma Merkezi",
  "Deniz Ekipmanları Mağazası",
  "Deniz Ekosistemi Koruma Derneği",
  "Deniz Kirliliği Araştırma Merkezi",
  "Deniz Otobüsü ve Feribot İskeleleri",
  "Deniz Ulaşım Şirketi",
  "Deniz ve Okyanus Çalışmaları",
  "Deniz ve Su Bilimleri",
  "Denizci",
  "Denizcilik ve Su Sporları",
  "Denizcilik",
  "Depo Yönetimi Sistemleri Geliştiricisi",
  "Depocu",
  "Depolama Hizmeti",
  "Depolar",
  "Deprem Simülasyon Merkezi",
  "Dergi ve Gazete Yayıncıları",
  "Derici",
  "Dernek",
  "Dershane",
  "Desinatör",
  "Devlet Memuru",
  "Diğer Hizmetler",
  "Diğer",
  "Dijital Eğitim Platformu",
  "Dijital Medya ve İçerik",
  "Dijital Pazarlama Ajansı",
  "Dijital ve Geleneksel Eğitim",
  "Dil Değişim Programları Organizatörleri",
  "Dil Kursları",
  "Dini Kurum",
  "Diplomat",
  "Diş Hekimi",
  "Diş Kliniği",
  "Diş Klinikleri",
  "Diş Teknisyeni",
  "Diyetisyen",
  "Dizgici",
  "Doğa Koruma Kurumu",
  "Doğa Sporları Ekipmanları Mağazası",
  "Doğa Sporları Kulübü",
  "Doğa Turları Rehberleri",
  "Doğa ve Ekoturizm",
  "Doğa ve Macera",
  "Doğa Yürüyüşü Parkurları",
  "Doğalgazcı",
  "Doğramacı",
  "Doğum Uzmanı",
  "Doktor",
  "Dokuma ve Nakış Atolyesi",
  "Dokumacı",
  "Dondurma Üreticisi",
  "Dondurmacı",
  "Dökümcü",
  "Dönerciler",
  "Döşemeci",
  "Döviz Bürosu",
  "Dövizci",
  "Dövüş Sanatları Salonu",
  "Drone Çekim Hizmeti",
  "Drone Teknolojisi Geliştiren Firmalar",
  "Dublajcı",
  "Duvarcı",
  "Düğün Salonu",
  "Dümenci",
  "Ebe(Kadın Doğum)",
  "Eczacı Kalfası",
  "Eczacı",
  "Eczane",
  "Editör",
  "Eğitim Dışı Akademik Kurum",
  "Eğitim Dışı Aktiviteler",
  "Eğitim Robotları Üreten Şirket",
  "Eğitim Teknolojileri",
  "Eğitim ve Gelişim",
  "Eğitim ve Kurslar",
  "Eğitim ve Okul",
  "Eğitim ve Sertifikasyon",
  "Eğitim",
  "Eğitimci",
  "Eğitmen",
  "Eğlence Parkları",
  "Eğlence ve Çocuk Aktiviteleri",
  "Eğlence ve Dinlenme",
  "Ehliyet Kursları",
  "E-kitap Yayıncıları",
  "Eko-Köyler",
  "Ekonomist",
  "Ekoturizm Tesisi",
  "El Sanatları Atolyesi",
  "El Sanatları ve Tasarım",
  "Elektrik Mühendisi",
  "Elektrik Şirketi",
  "Elektrik ve Doğalgaz Tedarik Şirketi",
  "Elektrik ve Elektronik Mühendislik Firması",
  "Elektrik ve Elektronik Tamir Hizmeti",
  "Elektrik ve Tesisat Hizmeti",
  "Elektrikçi",
  "Elektrik-Elektronik Mühendisi",
  "Elektrikli Araç Kiralama Hizmeti",
  "Elektrikli Araç Şarj İstasyonu",
  "Elektrikli Ev Aletleri Satıcısı",
  "Elektronik Mağazası",
  "Elektronik Mühendisi",
  "Elektronik Ürün Satan Mağaza",
  "Elektronik Ve Haberleşme Mühendisi",
  "Eleştirmen",
  "Embriyolog",
  "Emlak Ofisi",
  "Emlak ve İnşaat",
  "Emlakçı",
  "Endüstri Mühendisi",
  "Endüstri Sistemleri Mühendisi",
  "Endüstriyel Makine Üreticisi",
  "Enerji ve Çevre",
  "Enerji ve Teknoloji",
  "Enerji ve Yakıt",
  "Enerji Verimliliği Danışmanlık Firması",
  "Enstitüler",
  "Enstrüman İmalatçısı",
  "Ergonomist",
  "Eski Eşya Yenileme Atolyesi",
  "Eskici",
  "Esnaf",
  "E-spor Merkezi",
  "E-spor Organizasyonları",
  "Estetik ve Plastik Cerrahi Merkezi",
  "Estetisyen",
  "Etimolog",
  "Etkinlik Planlama Şirketi",
  "Etkinlik ve Organizasyon",
  "Etnografya Müzesi",
  "Etnolog",
  "Etolojist",
  "Etüt Merkezi",
  "Ev Dekorasyonu Ürünleri Satan Mağaza",
  "Ev Hanımı",
  "Ev Hizmeti",
  "Ev Tadilat ve Dekorasyon Firması",
  "Ev ve Ofis Hizmeti",
  "Evcil Hayvan Eğitim Hizmeti",
  "Evcil Hayvan Mağazası",
  "Evcil Hayvan ve Hayvan Hakları",
  "Evden Çalışan Küçük İşletme",
  "Evden Eve Nakliyat Firması",
  "Fabrika İşçisi",
  "Fabrika Otomasyonu Sağlayıcısı",
  "Fast Food Zinciri",
  "Fast Food Zincirleri",
  "Feribot ve Deniz Ulaşım Şirketi",
  "Fermantasyon İşçisi",
  "Festival Organizasyon Şirketi",
  "Festival ve Etkinlik Alanı",
  "Fıçıcı",
  "Fırıncı",
  "Fırınlar",
  "Fidancılar ve Bitki Satıcısı",
  "Fidanlık ve Seralar",
  "Fidanlıklar",
  "Figüran",
  "Film Stüdyosu",
  "Film ve Video Prodüksiyon",
  "Film Yapımcısı",
  "Film Yönetmeni",
  "Filozof",
  "Finans Kuruluşu",
  "Finans",
  "Finansal Danışmanlık Firması",
  "Finansör",
  "Fitness Cihazları Satıcısı",
  "Fizik Tedavi ve Rehabilitasyon Merkezi",
  "Fizikçi",
  "Fizyonomist",
  "Fizyoterapist",
  "Fon Yöneticisi",
  "Forklift Operatörü",
  "Fotoğraf Stüdyosu",
  "Fotoğrafçı",
  "Fotoğrafçılık Kulübü",
  "Freelance Proje Yönetim Ajansı",
  "Freelancer Ofis Alanı",
  "Fuar ve Kongre Merkezi",
  "Futbol Sahaları",
  "Futbolcu",
  "Galeri (Araç Satışı)",
  "Galerici",
  "Gardiyan",
  "Garson",
  "Gayrimenkul Değerleme Şirketi",
  "Gayrimenkul Geliştirme Firması",
  "Gazeteci",
  "Geçici İş Sağlama Ajansı",
  "Geleneksel El Sanatları Eğitim Merkezi",
  "Geleneksel Tatlı Üreticisi",
  "Gelir Uzman Yardımcısı",
  "Gelir Uzmanı",
  "Gemici",
  "Genç Girişimciler Kulübü",
  "Gençlik Merkezi",
  "Genetik Araştırma Merkezi",
  "Genetik Mühendisi",
  "Geri Dönüşüm Merkezi",
  "Gezgin",
  "Gıda İşleme Fabrikası",
  "Gıda İşleme Makine Üreticisi",
  "Gıda Mühendisi",
  "Gıda Teknolojisi ve Üretim",
  "Gıda ve Restoran",
  "Gıda ve Su Yardım Dağıtım Şirketi",
  "Girişim Sermayesi Şirketi",
  "Gitarist",
  "Giyim Mağazası",
  "Global Lojistik Şirketi",
  "Gökbilimci",
  "Göz Doktoru",
  "Gözetmen",
  "Gözlükçü",
  "Grafiker",
  "Gramer Uzmanı",
  "Greyder Operatörü",
  "Güfteci",
  "Gümrük Memuru",
  "Gümrük Müşavir Yardımcısı",
  "Gümrük Müşaviri",
  "Gümrük Uzmanı",
  "Gündelikçi",
  "Güneş Paneli Satıcısı",
  "Güvenlik Şirketi",
  "Güzellik Merkezi",
  "Güzellik Salonu",
  "Güzellik Uzmanı",
  "Haberci",
  "Haddeci",
  "Hakem",
  "Halı ve Perde Mağazası",
  "Halıcı",
  "Halıcılık ve Dokuma Atolyesi",
  "Halıcılık ve Kilim Atolyesi",
  "Halkbilimci",
  "Halkla İlişkiler Şirketi",
  "Hamurkâr",
  "Hareket Memuru",
  "Harita Mühendisi",
  "Haritacı",
  "Haritacılık Şirketi",
  "Hastabakıcı",
  "Hastahane",
  "Hastane",
  "Hastaneler",
  "Hattat",
  "Hava Trafikçisi",
  "Hava Yolu Şirketi",
  "Havacı",
  "Havacılık Eğitim Akademisi",
  "Havalimanları",
  "Hayvan Bakıcısı",
  "Hayvan Barınakları Destek Derneği",
  "Hayvan Barınakları",
  "Hayvan Eğitim Merkezi",
  "Hayvan Oteli",
  "Hayvan Rehabilitasyon Merkezi",
  "Hayvan Sağlığı İlaç Satıcısı",
  "Hayvan ve Evcil Hayvan Hizmeti",
  "Hayvan Yemi Üreticisi",
  "Hayvanlar ve Doğa",
  "Hazır Yemek Üretim Tesisi",
  "Hediyelik Eşya Mağazası",
  "Hemşire",
  "Hesap Uzmanı",
  "Heykel Atolyesi",
  "Heykeltıraş",
  "Hırdavatçı",
  "Hızlı Tüketim ve Servisler",
  "Hidrografi ve Oşinografi Çalışmaları",
  "Hidrolikçi",
  "Hidroponik Çiftlikler",
  "Hizmet ve Danışmanlık",
  "Hizmet",
  "Hizmetçi",
  "Hobi Bahçeleri",
  "Hobi Kulübü (Satranç, Origami, vb.)",
  "Hobi Mağazası",
  "Hobi ve El Sanatları",
  "Holding",
  "Host",
  "Hosteller",
  "Hostes",
  "Hukuk Bürosu",
  "Hukuk ve Danışmanlık",
  "Hukukçu",
  "Hurda İşleme Tesisi",
  "Hurdacı",
  "Irgat",
  "Işıkçı",
  "İcra Memuru",
  "İç Mimar",
  "İç Mimarlık Ofisi",
  "İğneci",
  "İhracat ve İthalat Şirketi",
  "İhracatçı Birlikleri",
  "İhracatçı",
  "İklim Değişikliği Eğitim Programları",
  "İklim ve Çevre Teknolojileri",
  "İklimlendirme ve Havalandırma Şirketi",
  "İktisatçı",
  "İlahiyatçı",
  "İleri Tarım ve Hayvancılık",
  "İletişim ve PR Hizmeti",
  "İlkokullar",
  "İllüzyonist",
  "İmam",
  "İnfluencer Ajansı",
  "İnsan Hakları İzleme Organizasyonları",
  "İnsan Kaynakları Uzmanı",
  "İnsan Kaynakları ve İstihdam",
  "İnsan Kaynakları Yönetim Şirketi",
  "İnşaat Firması",
  "İnşaat Malzemesi Satıcısı",
  "İnşaat Mühendisi",
  "İnşaat Mühendisliği Danışmanlıkları",
  "İnşaat Mühendislik Firması",
  "İnşaat Şirketi",
  "İnşaat ve Altyapı",
  "İnşaat ve Gayrimenkul",
  "İnşaat ve Yapı Marketler",
  "İnşaatçı",
  "İnteraktif Ders Materyalleri Üreticisi",
  "İnternet Radyosu",
  "İnternet Servis Sağlayıcısı",
  "İpçi",
  "İplikçi",
  "İstatistikçi",
  "İstihkâmcı",
  "İşaretçi",
  "İşe Alım Danışmanlık Firması",
  "İşletme Mühendisi",
  "İşletmeci",
  "İşportacı",
  "İtfaiyeci",
  "İthalatçı",
  "İyilik Marketi",
  "Jeofizik Mühendisi",
  "Jeolog",
  "Jeoloji Mühendisi",
  "Jeomorfolog",
  "Jimnastikçi",
  "Jinekolog",
  "Jokey",
  "Kabin Görevlisi",
  "Kaçış Odaları",
  "Kadın Girişimci Üretim Merkezi",
  "Kadın Terzisi",
  "Kafe",
  "Kafeler",
  "Kâğıtçı",
  "Kahveci",
  "Kahvehaneler",
  "Kâhya",
  "Kalaycı",
  "Kalıpçı",
  "Kaloriferci",
  "Kameraman",
  "Kamp Alanı",
  "Kamu Görevlisi",
  "Kamu Kurumu",
  "Kamu ve Belediye Hizmeti",
  "Kamu ve Sivil Toplum",
  "Kamyoncu",
  "Kapı ve Pencere Sistemleri Üreticisi",
  "Kapıcı",
  "Kaplamacı",
  "Kaportacı",
  "Kaptan",
  "Karaoke Salonu",
  "Karavan ve Kamp Hizmeti",
  "Karbon Ayak İzi Danışmanlık Şirketi",
  "Karbon Emisyonu Azaltma Şirketi",
  "Kardiyolog",
  "Kargo Şirketi",
  "Kargo ve Kurye Hizmeti",
  "Karikatürist",
  "Kariyer Gelişim Merkezi",
  "Karoserci",
  "Karpuzcu",
  "Kasap",
  "Kasiyer",
  "Kat Görevlisi",
  "Kâtip",
  "Katkı Maddesi ve Baharat Üreticisi",
  "Kayıkçı",
  "Kaymakam",
  "Kaynakçı",
  "Kebapçı",
  "Kemancı",
  "Kentsel Dönüşüm Şirketi",
  "Kentsel Planlama Firması",
  "Kesimci",
  "Kırsal Kalkınma ve Yerel Üretim",
  "Kırtasiyeci",
  "Kimya Mühendisi",
  "Kimya Sanayi Firması",
  "Kimyager",
  "Kişisel Antrenör Hizmeti",
  "Kişisel Bakım ve Sağlık",
  "Kişisel Blog",
  "Kişisel Gelişim Atolyesi",
];
