#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

COMMON_EXCLUDES=(
  --glob
  '!.git/**'
  --glob
  '!functions/node_modules/**'
  --glob
  '!cloudflare-shortlink-worker/node_modules/**'
  --glob
  '!ios/Pods/**'
  --glob
  '!build/**'
  --glob
  '!**/*.md'
  --glob
  '!firebase-debug.log'
  --glob
  '!scripts/check_repo_security_regressions.sh'
)

check_literal() {
  local label="$1"
  local pattern="$2"

  if rg -n --fixed-strings "${COMMON_EXCLUDES[@]}" "$pattern" .; then
    echo
    echo "[FAIL] $label"
    return 1
  fi

  echo "[PASS] $label"
  return 0
}

check_literal_in_file() {
  local label="$1"
  local pattern="$2"
  local file="$3"

  if rg -n --fixed-strings "$pattern" "$file"; then
    echo
    echo "[FAIL] $label"
    return 1
  fi

  echo "[PASS] $label"
  return 0
}

check_context_literal_in_file() {
  local label="$1"
  local anchor="$2"
  local forbidden="$3"
  local file="$4"

  if rg -n -C 6 --fixed-strings "$anchor" "$file" | rg -n --fixed-strings "$forbidden"; then
    echo
    echo "[FAIL] $label"
    return 1
  fi

  echo "[PASS] $label"
  return 0
}

failures=0

check_literal "Hardcoded legacy NETGSM usercode bulunmadi" "3326062598" || failures=$((failures + 1))
check_literal "Hardcoded legacy NETGSM parola bulunmadi" "BursCity42@" || failures=$((failures + 1))
check_literal "Hardcoded App Check debug token setenv geri gelmedi" 'setenv("FIRAAppCheckDebugToken"' || failures=$((failures + 1))
check_literal "Runner scheme icinde App Check debug env geri gelmedi" "FIRAAppCheckDebugToken" || failures=$((failures + 1))
check_literal "Genis iOS ATS acilimi geri gelmedi" "NSAllowsArbitraryLoads" || failures=$((failures + 1))
check_literal "App Check gevsetme flag'i geri gelmedi" "enforceAppCheck: false" || failures=$((failures + 1))
check_literal "Current user cache tekrar ham toJson ile yazilmiyor" "jsonEncode(user.toJson())" || failures=$((failures + 1))
check_literal "Legacy cache sifresi tekrar hydrate edilmiyor" "sifre: json['sifre'] ?? ''" || failures=$((failures + 1))
check_literal "Auth akisinda ham email logu geri gelmedi" 'print("Email: ${signInEmail.value}")' || failures=$((failures + 1))
check_literal "Auth akisinda parola uzunlugu logu geri gelmedi" 'print("Şifre: ${'"'"'*'"'"' * password.value.length}")' || failures=$((failures + 1))
check_literal "Auth akisinda UID logu geri gelmedi" 'print("Giriş başarılı! Kullanıcı UID: ${userCredential.user?.uid}")' || failures=$((failures + 1))
check_literal "Auth akisinda hata mesaji dump'i geri gelmedi" 'print("Giriş hatası oluştu: ${e.code} - ${e.message}")' || failures=$((failures + 1))
check_literal "Sifre guncelleme akisinda hata mesaji dump'i geri gelmedi" 'print("Hata: ${e.code} - ${e.message}")' || failures=$((failures + 1))
check_literal_in_file "Sign in session cache hata dump'i geri gelmedi" "print('⚠️ Session cache clear error: \$e');" "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Sign in giris basladi print'i geri gelmedi" 'print("Giriş işlemi başlatılıyor...");' "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Sign in giris basarili print'i geri gelmedi" 'print("Giriş başarılı");' "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Sign in unread controller print'i geri gelmedi" 'print("✅ UnreadMessagesController başlatıldı");' "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Sign in post-login warmup print'i geri gelmedi" 'print("🔄 Post-login warmup başladı...");' "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Sign in nickname bulundu print'i geri gelmedi" 'print("nickname bulundu");' "lib/Modules/SignIn/sign_in_controller.dart" || failures=$((failures + 1))
check_literal "Notification loglarinda uid dump'i geri gelmedi" 'console.log("onUserNotificationCreate sent", { uid, type, tokenPresent: true });' || failures=$((failures + 1))
check_literal "Current user init logunda uid dump'i geri gelmedi" "print('🔄 Initializing CurrentUserService for user: \${firebaseUser.uid}');" || failures=$((failures + 1))
check_literal "Scholarship detail logunda uid dump'i geri gelmedi" "print('Başvuru durumu kontrol ediliyor: \${currentUser.uid}');" || failures=$((failures + 1))
check_literal "DenemeGrid logunda userID dump'i geri gelmedi" "debugPrint('[DenemeGrid] profile fetch failed for \$userID: \$e');" || failures=$((failures + 1))
check_literal "DenemeGrid logunda docID dump'i geri gelmedi" "debugPrint('[DenemeGrid] applicant count fetch failed for \$docID: \$e');" || failures=$((failures + 1))
check_literal "Hybrid feed logunda authorId dump'i geri gelmedi" 'console.log(`[HybridFeed] Celebrity fan-in: ${authorId} (${followerCount} followers)`);' || failures=$((failures + 1))
check_literal "Author denorm logunda postId dump'i geri gelmedi" 'console.log(`[AuthorDenorm] Post ${context.params.postId} author alanları güncellendi`);' || failures=$((failures + 1))
check_literal "Author denorm logunda uid dump'i geri gelmedi" '`${uid} profil değişikliği' || failures=$((failures + 1))
check_literal "Email verify warning logunda uid dump'i geri gelmedi" "uid: caller.uid," || failures=$((failures + 1))
check_literal "Current user cache logunda nickname dump'i geri gelmedi" "print('✅ User loaded from cache: \${user.nickname}');" || failures=$((failures + 1))
check_literal "Current user persist logunda nickname dump'i geri gelmedi" "print('💾 User cached: \${user.nickname}');" || failures=$((failures + 1))
check_literal_in_file "Current user generic init logu geri gelmedi" "print('🔄 Initializing CurrentUserService');" "lib/Services/current_user_service.dart" || failures=$((failures + 1))
check_literal_in_file "Current user cache loaded print'i geri gelmedi" "print('✅ User loaded from cache');" "lib/Services/current_user_service.dart" || failures=$((failures + 1))
check_literal_in_file "Current user cache persisted print'i geri gelmedi" "print('💾 User cached');" "lib/Services/current_user_service.dart" || failures=$((failures + 1))
check_literal_in_file "Current user firebase sync start print'i geri gelmedi" "print('🔥 Firebase sync started');" "lib/Services/current_user_service.dart" || failures=$((failures + 1))
check_literal_in_file "Current user logout print'i geri gelmedi" "print('👋 User logged out - State cleared');" "lib/Services/current_user_service.dart" || failures=$((failures + 1))
check_literal_in_file "Iz Birak subscription uid/post hata dump'i geri gelmedi" "print('[IzBirakSubscription] subscribe failed post=\$normalizedPostId uid=\$uid error=\$e');" "lib/Core/Services/iz_birak_subscription_service.dart" || failures=$((failures + 1))
check_literal_in_file "Mandatory follow hata dump'i geri gelmedi" "[MandatoryFollow] follow failed error=\$e fallback=\$fallbackError" "lib/Core/Services/mandatory_follow_service.dart" || failures=$((failures + 1))
check_literal_in_file "Blocked texts kufur dump'i geri gelmedi" "print('TESPİT EDİLEN KÜFÜR: \$word');" "lib/Core/blocked_texts.dart" || failures=$((failures + 1))
check_literal_in_file "NSFW dosya yolu dump'i geri gelmedi" "print('NSFW check failed for \${dosya.path}: \$e');" "lib/Core/nude_control.dart" || failures=$((failures + 1))
check_literal_in_file "Firestore init debug print'i geri gelmedi" "print('✅ Firestore initialized with optimized settings');" "lib/Core/Services/firestore_config.dart" || failures=$((failures + 1))
check_literal_in_file "Firestore init error dump'i geri gelmedi" "print('❌ Firestore initialization error: \$e');" "lib/Core/Services/firestore_config.dart" || failures=$((failures + 1))
check_literal_in_file "Firestore cache clear print'i geri gelmedi" "print('✅ Firestore cache cleared');" "lib/Core/Services/firestore_config.dart" || failures=$((failures + 1))
check_literal_in_file "Firestore cache clear hata dump'i geri gelmedi" "print('❌ Failed to clear Firestore cache: \$e');" "lib/Core/Services/firestore_config.dart" || failures=$((failures + 1))
check_literal_in_file "Draft media cleanup hata dump'i geri gelmedi" "print('Error cleaning up draft media: \$e');" "lib/Core/Services/draft_service.dart" || failures=$((failures + 1))
check_literal_in_file "Media enhancement filter hata dump'i geri gelmedi" "print('Error applying filter: \$e');" "lib/Core/Services/media_enhancement_service.dart" || failures=$((failures + 1))
check_literal_in_file "Media enhancement adjustments hata dump'i geri gelmedi" "print('Error applying adjustments: \$e');" "lib/Core/Services/media_enhancement_service.dart" || failures=$((failures + 1))
check_literal_in_file "Media enhancement full processing hata dump'i geri gelmedi" "print('Error in full processing: \$e');" "lib/Core/Services/media_enhancement_service.dart" || failures=$((failures + 1))
check_literal_in_file "Recommended users follow list hata dump'i geri gelmedi" "print('Error loading following list: \$e');" "lib/Modules/RecommendedUserList/recommended_user_list_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Recommended users liste hata dump'i geri gelmedi" "print('Error loading recommended users: \$e');" "lib/Modules/RecommendedUserList/recommended_user_list_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Recommended user follow toggle hata dump'i geri gelmedi" 'print("Bir hata oluştu: $e");' "lib/Modules/RecommendedUserList/RecommendedUserContent/recommended_user_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "In-app notification toplu silme print'i geri gelmedi" 'print("Tüm bildirimler toplu olarak silindi!");' "lib/Modules/InAppNotifications/in_app_notifications_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story seens viewer hata dump'i geri gelmedi" 'print("Görüntüleme listesi alınamadı: $e");' "lib/Modules/Story/StoryViewer/StorySeens/story_seens_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story seens count hata dump'i geri gelmedi" 'print("Toplam görülme alınamadı: $e");' "lib/Modules/Story/StoryViewer/StorySeens/story_seens_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story highlights load hata dump'i geri gelmedi" "print('loadHighlights error: \$e');" "lib/Modules/Story/StoryHighlights/story_highlights_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story highlights create hata dump'i geri gelmedi" "print('createHighlight error: \$e');" "lib/Modules/Story/StoryHighlights/story_highlights_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story highlights add hata dump'i geri gelmedi" "print('addStoryToHighlight error: \$e');" "lib/Modules/Story/StoryHighlights/story_highlights_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story highlights delete hata dump'i geri gelmedi" "print('deleteHighlight error: \$e');" "lib/Modules/Story/StoryHighlights/story_highlights_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Story highlights update hata dump'i geri gelmedi" "print('updateHighlight error: \$e');" "lib/Modules/Story/StoryHighlights/story_highlights_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar preload hata dump'i geri gelmedi" "print('[NavBar] ShortController preload error: \$e');" "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar animation hata dump'i geri gelmedi" "print('[NavBar] Animation interrupted: \$e');" "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar typing dispose hata dump'i geri gelmedi" "print('[NavBar] typingController dispose error: \$e');" "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar deleting dispose hata dump'i geri gelmedi" "print('[NavBar] deletingController dispose error: \$e');" "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar animationController dispose hata dump'i geri gelmedi" "print('[NavBar] animationController dispose error: \$e');" "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar debug version bypass print'i geri gelmedi" 'print("🔧 DEBUG MODE: Version kontrolü bypass edildi");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar current version print'i geri gelmedi" 'print("📱 Cihaz versiyonu: $currentVersion");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar min version print'i geri gelmedi" 'print("🔥 Firebase minimum versiyon: $requiredVersion");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar update gerekli print'i geri gelmedi" 'print("⚠️ Güncelleme gerekli: Mevcut $currentVersion < Gerekli $requiredVersion");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar version uygun print'i geri gelmedi" 'print("✅ Version uygun: $currentVersion");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar version hata dump'i geri gelmedi" 'print("❌ Version kontrolü hatası: $e");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "NavBar store launch hata dump'i geri gelmedi" 'print("Mağaza açma hatası: $e");' "lib/Modules/NavBar/nav_bar_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Saved posts hydrate hata dump'i geri gelmedi" "print('❌ SavedPostsController hydrate error: \$e');" "lib/Modules/Profile/SavedPosts/saved_posts_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Edit post setData hata dump'i geri gelmedi" 'print("setData error: $e");' "lib/Modules/EditPost/edit_post_controller.dart" || failures=$((failures + 1))
check_literal_in_file "CV yukleme hata dump'i geri gelmedi" "print('CV verisi yüklenirken hata: \$e');" "lib/Modules/Profile/Cv/cv_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post sharers count ve userIDs dump'i geri gelmedi" "print('PostSharers: Found \${sharers.length} sharers with userIDs: \$userIDs');" "lib/Modules/Social/PostSharers/post_sharers_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post sharers fetch hata dump'i geri gelmedi" "print('Error loading post sharers: \$e');" "lib/Modules/Social/PostSharers/post_sharers_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post sharers users data hata dump'i geri gelmedi" "print('Error loading users data: \$e');" "lib/Modules/Social/PostSharers/post_sharers_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Liked posts hydrate hata dump'i geri gelmedi" "print('❌ LikedPostControllers hydrate error: \$e');" "lib/Modules/Profile/LikedPosts/liked_posts_controller.dart" || failures=$((failures + 1))
check_literal_in_file "About profile fetch hata dump'i geri gelmedi" 'print("Profil verisi alınamadı: $e");' "lib/Modules/Profile/AboutProfile/about_profile_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My statistic load hata dump'i geri gelmedi" "print('MyStatisticController load error: \$e');" "lib/Modules/Profile/MyStatistic/my_statistic_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My statistic follower count hata dump'i geri gelmedi" "print('Follower counts error: \$e');" "lib/Modules/Profile/MyStatistic/my_statistic_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My statistic post count hata dump'i geri gelmedi" "print('Post counts/views error: \$e');" "lib/Modules/Profile/MyStatistic/my_statistic_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My statistic story views hata dump'i geri gelmedi" "print('Story views error: \$e');" "lib/Modules/Profile/MyStatistic/my_statistic_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Archives dispose print'i geri gelmedi" 'print("Disposed AgendaContentController");' "lib/Modules/Profile/Archives/archives_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details user fetch hata dump'i geri gelmedi" "print('getUserData hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details CV check hata dump'i geri gelmedi" "print('cvCheck hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details saved check hata dump'i geri gelmedi" "print('checkSaved hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details toggle save hata dump'i geri gelmedi" "print('toggleSave hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details similar jobs hata dump'i geri gelmedi" "print('getSimilar hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details reviews fetch hata dump'i geri gelmedi" "print('fetchReviews hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details submit review hata dump'i geri gelmedi" "print('submitReview hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details delete review hata dump'i geri gelmedi" "print('deleteReview hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details basvuru check hata dump'i geri gelmedi" "print('checkBasvuru hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details basvuru toggle hata dump'i geri gelmedi" "print('toggleBasvuru hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job details edit refresh hata dump'i geri gelmedi" "print('goToEdit hatası: \$e');" "lib/Modules/JobFinder/JobDetails/job_details_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job content saved check hata dump'i geri gelmedi" 'print("checkSaved hatası: $e");' "lib/Modules/JobFinder/JobContent/job_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job content toggle save hata dump'i geri gelmedi" 'print("toggleSave hatası: $e");' "lib/Modules/JobFinder/JobContent/job_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Career profile CV yukleme hata dump'i geri gelmedi" 'print("CV yükleme hatası: $e");' "lib/Modules/JobFinder/CareerProfile/career_profile_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Career profile findingJob toggle hata dump'i geri gelmedi" 'print("findingJob toggle hatası: $e");' "lib/Modules/JobFinder/CareerProfile/career_profile_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Saved jobs hata dump'i geri gelmedi" 'print("Kaydedilen ilanlar hatası: $e");' "lib/Modules/JobFinder/SavedJobs/saved_job_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My applications load hata dump'i geri gelmedi" 'print("Başvurular yüklenirken hata: $e");' "lib/Modules/JobFinder/MyApplications/my_applications_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My applications cancel hata dump'i geri gelmedi" 'print("Başvuru iptal hatası: $e");' "lib/Modules/JobFinder/MyApplications/my_applications_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Application review load hata dump'i geri gelmedi" 'print("Başvuranlar yüklenirken hata: $e");' "lib/Modules/JobFinder/ApplicationReview/application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Application review CV hata dump'i geri gelmedi" 'print("CV yükleme hatası: $e");' "lib/Modules/JobFinder/ApplicationReview/application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Application review profil hata dump'i geri gelmedi" 'print("Profil yükleme hatası: $e");' "lib/Modules/JobFinder/ApplicationReview/application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Application review durum hata dump'i geri gelmedi" 'print("Durum güncelleme hatası: $e");' "lib/Modules/JobFinder/ApplicationReview/application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Finding job apply CV hata dump'i geri gelmedi" "print('CV kontrol hatası: \$e');" "lib/Modules/JobFinder/FindingJobApply/finding_job_apply_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My job ads active hata dump'i geri gelmedi" 'print("getActive() hatası: $e");' "lib/Modules/JobFinder/MyJobAds/my_job_ads_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My job ads deactive hata dump'i geri gelmedi" 'print("getDeactive() hatası: $e");' "lib/Modules/JobFinder/MyJobAds/my_job_ads_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder refresh hata dump'i geri gelmedi" 'print("İlan güncelleme hatası: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder search hata dump'i geri gelmedi" 'print("Arama hatası: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder start hata dump'i geri gelmedi" 'print("Hata oluştu: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder konum siralama hata dump'i geri gelmedi" 'print("Konum bazli is siralama hatasi: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder sessiz kapatma hata dump'i geri gelmedi" 'print("Eski ilanlar sessiz kapatilamadi: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job finder city load hata dump'i geri gelmedi" 'print("Error loading cities: $e");' "lib/Modules/JobFinder/job_finder_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator city load hata dump'i geri gelmedi" 'print("Error loading cities: $e");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator konum servisleri print'i geri gelmedi" 'print("Konum servisleri kapalı.");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator konum izin print'i geri gelmedi" 'print("Konum izni reddedildi.");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator adres dump'i geri gelmedi" 'print("Tam Adres: ${adres.value}");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator adres bulunamadi print'i geri gelmedi" 'print("Adres bulunamadı.");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator konum hata dump'i geri gelmedi" 'print("Konum alma hatası: $e");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator upload hata dump'i geri gelmedi" 'print("Yükleme hatası: $e");' "lib/Modules/JobFinder/JobCreator/job_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator ters geocode sehir print'i geri gelmedi" 'print("Sehir: $sehir");' "lib/Modules/JobFinder/JobCreator/job_creator.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator ters geocode ilce print'i geri gelmedi" 'print("Ilce: $ilce");' "lib/Modules/JobFinder/JobCreator/job_creator.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator ters geocode adres print'i geri gelmedi" 'print("Adres bulunamadı.");' "lib/Modules/JobFinder/JobCreator/job_creator.dart" || failures=$((failures + 1))
check_literal_in_file "Job creator ters geocode hata dump'i geri gelmedi" 'print("Ters geocode hatası: $e");' "lib/Modules/JobFinder/JobCreator/job_creator.dart" || failures=$((failures + 1))
check_literal_in_file "Short content interaction status hata dump'i geri gelmedi" "print('Load user interaction status error: \$e');" "lib/Modules/Short/short_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Short content follow hata dump'i geri gelmedi" "print('Bir hata oluştu: \$e');" "lib/Modules/Short/short_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Short refresh blocked print'i geri gelmedi" "print('[Shorts] Refresh blocked - already refreshing or loading');" "lib/Modules/Short/short_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Short warmStart hata dump'i geri gelmedi" "print('[Shorts] warmStart error: \$e');" "lib/Modules/Short/short_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Single short injected fallback print'i geri gelmedi" "print('[SingleShortView] Injected controller hazır değil, local controller kullanılıyor.');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short fetch hata dump'i geri gelmedi" 'print("fetch error: $e");' "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short didPop position dump'i geri gelmedi" "print('[SingleShortView] 🔙 Saved position: \${ctrl.value.position} for \${currentModel.docID}');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short didPop hata dump'i geri gelmedi" "print('[SingleShortView] Error during didPop: \$e');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short completion print'i geri gelmedi" "print('[SingleShortView] 🎬 Video \$index tamamlandı');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short duration dump'i geri gelmedi" "print('[SingleShortView] ⏱️  \${position.inSeconds}/\${duration.inSeconds}s');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short next page print'i geri gelmedi" "print('[SingleShortView] ⏭️  Video \$nextIndex\\'e geçiliyor (nextPage ile)');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Single short rewind print'i geri gelmedi" "print('[SingleShortView] 📝 Son video, başa sarılıyor');" "lib/Modules/Short/single_short_view.dart" || failures=$((failures + 1))
check_literal_in_file "Story viewer init prefetch hata dump'i geri gelmedi" 'print("story viewer init prefetch error: $e");' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story row refresh hata dump'i geri gelmedi" 'print("🚨 Story row refresh error: $e");' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story viewer user change dump'i geri gelmedi" 'print("🔄 Story user changed - UserID: ${widget.storyOwnerUsers[index].userID}, Index: $index");' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story screenshot detected print'i geri gelmedi" "print('📸 Screenshot detected - notified story owner');" "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story screenshot hata dump'i geri gelmedi" 'print('"'"'Screenshot alert error: $e'"'"');' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story fully viewed dump'i geri gelmedi" 'print("✅ User ${user.nickname} fully viewed - Latest story time: $latestStoryTime");' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "Story fully viewed hata dump'i geri gelmedi" 'print("🚨 markUserAsFullyViewed error: $e");' "lib/Modules/Story/StoryViewer/story_viewer.dart" || failures=$((failures + 1))
check_literal_in_file "User story download hata dump'i geri gelmedi" 'print('"'"'Story download error: $e'"'"');' "lib/Modules/Story/StoryViewer/user_story_content.dart" || failures=$((failures + 1))
check_literal_in_file "Chat message text dump'i geri gelmedi" 'print("✏️ Mesaj text: '"'"'\'"'"''"'"'$text'"'"'\'"'"''"'"'");' "lib/Modules/Chat/chat_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Chat notification body dump'i geri gelmedi" 'print("🔔 Notif body: $notifBody");' "lib/Modules/Chat/chat_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Chat conversation hata dump'i geri gelmedi" 'print("🔥 HATA: conversation yazımı başarısız: $e");' "lib/Modules/Chat/chat_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Chat resim upload hata dump'i geri gelmedi" 'print("Resim upload error: $e");' "lib/Modules/Chat/chat_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Chat voice upload hata dump'i geri gelmedi" 'print("Voice upload error: $e");' "lib/Modules/Chat/chat_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Splash first launch auth session print'i geri gelmedi" "print('🔐 First launch detected with existing Firebase Auth session');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash auth cleanup print'i geri gelmedi" "print('🧹 Clearing Firebase Auth to force login screen...');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash auth cleared print'i geri gelmedi" "print('✅ Auth cleared - User will see login screen');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash first launch flag print'i geri gelmedi" "print('📝 First launch flag set');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash first launch hata dump'i geri gelmedi" 'print('"'"'❌ First launch auth cleanup error: $e'"'"');' "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash startup trace init logu geri gelmedi" "debugPrint('[StartupTrace] launch->Splash.initState =" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash startup trace first frame logu geri gelmedi" "debugPrint('[StartupTrace] launch->Splash.firstFrame =" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash startup trace watchdog logu geri gelmedi" "debugPrint('[StartupTrace] watchdog fired -> fallback navigation');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash startup trace nav decision logu geri gelmedi" "debugPrint('[StartupTrace] launch->NavDecision(" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash startup sync trace logu geri gelmedi" "debugPrint('[StartupSync] phase=begin');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Splash cache proxy hata logu geri gelmedi" "debugPrint('[Splash] Cache proxy init error: \$e');" "lib/Modules/Splash/splash_view.dart" || failures=$((failures + 1))
check_literal_in_file "Explore cache quota hata dump'i geri gelmedi" "print('Explore cache quota apply error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore recent search id fetch hata dump'i geri gelmedi" "print('Explore recent search ids fetch error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore recent search cache load hata dump'i geri gelmedi" "print('Explore recent search cache load error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore recent search cache save hata dump'i geri gelmedi" "print('Explore recent search cache save error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore recent search save hata dump'i geri gelmedi" "print('Explore recent search save error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore recent search delete hata dump'i geri gelmedi" "print('Explore recent search delete error: \$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore fetchVideo start debug print geri gelmedi" 'print("[Explore] fetchVideo:start lastDoc=${lastVideoDoc != null}");' "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore fetchPhoto start debug print geri gelmedi" 'print("[Explore] fetchPhoto:start lastDoc=${lastPhotoDoc != null}");' "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore floods fallback hata dump'i geri gelmedi" "print('[FLOODS] server filter failed; fallback. err=\$e');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore floods privacy filter debug print geri gelmedi" "print('[FLOODS] privacyFilter removed=\$removed kept=\${filtered.length}');" "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Explore typesense hata dump'i geri gelmedi" 'print("❌ Typesense arama hatası: $e");' "lib/Modules/Explore/explore_controller.dart" || failures=$((failures + 1))
check_literal "Story save logunda storyId dump'i geri gelmedi" 'print("Story kaydedildi: $storyId (${serialized.length} element)");' || failures=$((failures + 1))
check_literal "Dispose loglarinda docID dump'i geri gelmedi" 'print("Disposed AgendaContentController for $docID");' || failures=$((failures + 1))
check_literal "Flood error logunda rootID dump'i geri gelmedi" "print('🔥 Kök flood alınamadı: \$rootID – \$e');" || failures=$((failures + 1))
check_literal "Flood error logunda docID dump'i geri gelmedi" "print('🔥 Flood verisi alınamadı: \$docID – \$e');" || failures=$((failures + 1))
check_literal "Copy link debug print docID geri gelmedi" "print(widget.model.docID);" || failures=$((failures + 1))
check_literal "Flood listing init docID debug print geri gelmedi" "print(widget.mainModel.docID);" || failures=$((failures + 1))
check_literal "Antreman yorumlarinda ham user data dump'i geri gelmedi" 'log("User data for $userID: $data");' || failures=$((failures + 1))
check_literal "Test soru upload logunda signed URL dump'i geri gelmedi" 'print("Download URL: $downloadUrl");' || failures=$((failures + 1))
check_literal "Cikmis soru sonucunda cevap dump'i geri gelmedi" "print(cevaplar[index]);" || failures=$((failures + 1))
check_literal "Cikmis soru sonucunda secim dump'i geri gelmedi" "print(secim.value);" || failures=$((failures + 1))
check_literal "Cikmis soru yil seciminde ana baslik debug dump'i geri gelmedi" 'print("DEVELOPER ${widget.anaBaslik}");' || failures=$((failures + 1))
check_literal "Cikmis soru yil seciminde baslik2 debug dump'i geri gelmedi" 'print("DEVELOPER ${widget.baslik2}");' || failures=$((failures + 1))
check_literal "Cikmis soru yil seciminde baslik3 debug dump'i geri gelmedi" 'print("DEVELOPER ${widget.baslik3}");' || failures=$((failures + 1))
check_literal_in_file "Answer key controller kitapcik sayisi debug logu geri gelmedi" 'log("Çekilen kitapçık sayısı: ${bookList.length}");' "lib/Modules/Education/AnswerKey/answer_key_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Answer key controller fetch hata logu geri gelmedi" 'log("Veri çekme hatası: $e");' "lib/Modules/Education/AnswerKey/answer_key_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Answer key controller loadMore hata logu geri gelmedi" 'log("AnswerKeyController.loadMore error: $e");' "lib/Modules/Education/AnswerKey/answer_key_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Answer key typesense hata logu geri gelmedi" 'log("Answer key typesense search error: $e");' "lib/Modules/Education/AnswerKey/answer_key_controller.dart" || failures=$((failures + 1))
check_literal "Category answer key hata dump'i geri gelmedi" 'print("Error fetching booklets: $e");' || failures=$((failures + 1))
check_literal "My test results hata dump'i geri gelmedi" 'print("Error fetching test results: $e");' || failures=$((failures + 1))
check_literal "Saved tests hata dump'i geri gelmedi" 'print("Error fetching saved tests: $e");' || failures=$((failures + 1))
check_literal "Optical form delete hata dump'i geri gelmedi" 'print("Error deleting optical form: $e");' || failures=$((failures + 1))
check_literal "Test entry success debug print geri gelmedi" 'print("buldu");' || failures=$((failures + 1))
check_literal "Test entry miss debug print geri gelmedi" 'print("veriyok");' || failures=$((failures + 1))
check_literal "Test entry error dump'i geri gelmedi" 'print("Error fetching test: $e");' || failures=$((failures + 1))
check_literal_in_file "Solve test fetch question error dump'i geri gelmedi" 'print("Error fetching questions: $e");' "lib/Modules/Education/Tests/SolveTest/solve_test_controller.dart" || failures=$((failures + 1))
check_literal "Solve test user data error dump'i geri gelmedi" 'print("Error fetching user data: $e");' || failures=$((failures + 1))
check_literal "Solve test submit error dump'i geri gelmedi" 'print("Yanitlar eklenirken hata: $error");' || failures=$((failures + 1))
check_literal "Scholarship detail apply status debug print geri gelmedi" "print('Başvuru durumu kontrol ediliyor');" || failures=$((failures + 1))
check_literal "Scholarship detail type debug print geri gelmedi" "print('Burs başvuru tipi: \$type');" || failures=$((failures + 1))
check_literal "Scholarship detail apply state dump'i geri gelmedi" "print('Son başvuru durumu: \${allreadyApplied.value}');" || failures=$((failures + 1))
check_literal "Scholarship detail invalid id debug print geri gelmedi" "print('Geçersiz burs ID');" || failures=$((failures + 1))
check_literal "Scholarship detail error dump'i geri gelmedi" "print('Başvuru durumu kontrol edilirken hata: \$e');" || failures=$((failures + 1))
check_literal "Scholarship detail apply save error dump'i geri gelmedi" "print('Başvuru kaydedilirken hata: \$e');" || failures=$((failures + 1))
check_literal "Scholarship detail page index debug print geri gelmedi" "print('Güncellenen sayfa indeksi: \$pageIndex');" || failures=$((failures + 1))
check_literal "Scholarship detail follow error dump'i geri gelmedi" 'print("Takip işlemi hatası: $e");' || failures=$((failures + 1))
check_literal "Scholarship detail delete debug print geri gelmedi" 'print("deleteScholarship hatası.");' || failures=$((failures + 1))
check_literal "Scholarship detail cancel error dump'i geri gelmedi" "print('Başvuru iptal edilirken hata: \$e');" || failures=$((failures + 1))
check_literal_in_file "Dormitory cities hata dump'i geri gelmedi" 'print("Error loading cities: $e");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Dormitory yurt data hata dump'i geri gelmedi" 'print("Error loading yurt data: $e");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Dormitory Firestore hata dump'i geri gelmedi" 'print("Error fetching Firestore data: $e");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Dormitory idari secim debug print'i geri gelmedi" 'print("SELECTED $v");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Dormitory yurt secim debug print'i geri gelmedi" 'print("SELECTED YURT $v");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Dormitory save hata dump'i geri gelmedi" 'print("Error saving data: $e");' "lib/Modules/Education/Scholarships/DormitoryInfo/dormitory_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Family info cities hata dump'i geri gelmedi" 'print("Error loading cities: $e");' "lib/Modules/Education/Scholarships/FamilyInfo/family_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Family info fetch hata dump'i geri gelmedi" "print('Error fetching family info: \$e');" "lib/Modules/Education/Scholarships/FamilyInfo/family_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Family info secim debug print'i geri gelmedi" 'print("SELECTED $v");' "lib/Modules/Education/Scholarships/FamilyInfo/family_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Family info app bottom sheet secim logu geri gelmedi" 'log("SELECTED $v");' "lib/Modules/Education/Scholarships/FamilyInfo/family_info_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarship applications detail load hata dump'i geri gelmedi" 'print("Error loading detailed data: $e");' "lib/Modules/Education/Scholarships/ScholarshipApplicationsContent/scholarship_applications_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarship applications init load hata dump'i geri gelmedi" 'print("Error loading initial data: $e");' "lib/Modules/Education/Scholarships/ScholarshipApplicationsContent/scholarship_applications_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarship applications data load hata dump'i geri gelmedi" 'print("Error getting data: $e");' "lib/Modules/Education/Scholarships/ScholarshipApplicationsContent/scholarship_applications_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarship applications student info hata dump'i geri gelmedi" 'print("Error checking student info: $e");' "lib/Modules/Education/Scholarships/ScholarshipApplicationsContent/scholarship_applications_content_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized init hata dump'i geri gelmedi" "print('Error initializing data: \$e');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized user data hata dump'i geri gelmedi" "print('Error loading user data: \$e');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized vitrin hata dump'i geri gelmedi" "print('Error loading vitrin data: \$error');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized burs yukleme hata dump'i geri gelmedi" "print('Error loading scholarships data: \$error');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized burs isleme hata dump'i geri gelmedi" "print('Error processing scholarships data: \$e');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized konum izin print'i geri gelmedi" 'print("Konum izni verilmedi.");' "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized konum hata dump'i geri gelmedi" 'print("Konum bilgisi alınırken hata oluştu: $e");' "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized Firestore konum hata dump'i geri gelmedi" "print('Error updating location in Firestore: \$e');" "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Personalized refresh print'i geri gelmedi" 'print("List refreshed!");' "lib/Modules/Education/Scholarships/Personalized/personalized_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship file webp hata logu geri gelmedi" "log('WebP sıkıştırma hatası (file): \$e');" "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship bytes webp hata logu geri gelmedi" "log('WebP sıkıştırma hatası (bytes): \$e');" "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship firebase url logu geri gelmedi" "log('Bu bir Firebase URL\\'si, yükleme yapılmayacak: \$localPath');" "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship image upload hata logu geri gelmedi" "log('Görsel yüklenirken bir hata oluştu: \$e');" "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship template upload hata logu geri gelmedi" "log('Şablon görüntüsü yakalanırken/yüklenirken hata oluştu: \$e'," "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create scholarship publish hata logu geri gelmedi" "log('Burs paylaşılırken bir hata oluştu: \$e');" "lib/Modules/Education/Scholarships/CreateScholarship/create_scholarship_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships search hata dump'i geri gelmedi" "print('typesense scholarship search error: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships erken fetch skip print'i geri gelmedi" "print('Skipping fetch, too soon since last refresh');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships fetch start print'i geri gelmedi" "print('Starting fetchScholarships at \${DateTime.now()}');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships cache load print'i geri gelmedi" "print('Loaded scholarships from local cache: \${cached.length}');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships query timing print'i geri gelmedi" "Firestore queries took:" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships first page count print'i geri gelmedi" "print('Bireysel docs: \${bireyselSnapshot.docs.length}');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships user fetch timing print'i geri gelmedi" "users fetch (getAll) took:" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships fetch complete print'i geri gelmedi" "Total scholarships: \${combined.length}, fetch completed at \${DateTime.now()}" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships fetch hata dump'i geri gelmedi" "print('fetchScholarships error: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore skip print'i geri gelmedi" "print('Skipping loadMoreScholarships: already loading or no more data');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships pagination cursor print'i geri gelmedi" "print('Skipping loadMoreScholarships: pagination cursor is null');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore start print'i geri gelmedi" "print('Starting loadMoreScholarships at \${DateTime.now()}');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore Firestore timing print'i geri gelmedi" "Firestore queries for loadMore took:" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore query timing print'i geri gelmedi" "users fetch (getAll) for loadMore took:" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore page count print'i geri gelmedi" "print('Bireysel docs (more): \${bireyselSnapshot.docs.length}');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore complete print'i geri gelmedi" "Total scholarships after loadMore: \${allScholarships.length}, loadMore completed at \${DateTime.now()}" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships loadMore hata dump'i geri gelmedi" "print('loadMoreScholarships error: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships page index print'i geri gelmedi" "print('Updated page index for scholarship \$scholarshipIndex: \$pageIndex');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships like hata dump'i geri gelmedi" "print('toggleLike error: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships bookmark hata dump'i geri gelmedi" "print('toggleBookmark error: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships share hata dump'i geri gelmedi" "print('Error downloading or sharing the image: \$e');" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Scholarships expanded state print'i geri gelmedi" "Toggled expanded for index \$index" "lib/Modules/Education/Scholarships/scholarships_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring batch fetch hata logu geri gelmedi" 'log("Error batch fetching users: $e");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring fetch count logu geri gelmedi" 'log("Fetched ${page.items.length} tutoring items");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring load hata logu geri gelmedi" 'log("Error loading tutoring data: $e");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring loadMore hata logu geri gelmedi" 'log("Error loading more tutoring data: $e");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring search hata logu geri gelmedi" 'log("Tutoring typesense search error: $e");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring favorite hata logu geri gelmedi" 'log("Error toggling favorite: $e");' "lib/Modules/Education/Tutoring/tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "TutoringSearch batch hata logu geri gelmedi" 'log("Error batch fetching users: $e");' "lib/Modules/Education/Tutoring/TutoringSearch/tutoring_search_controller.dart" || failures=$((failures + 1))
check_literal_in_file "TutoringSearch init hata logu geri gelmedi" 'log("Error fetching initial data: $e");' "lib/Modules/Education/Tutoring/TutoringSearch/tutoring_search_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring application review load hata dump'i geri gelmedi" 'print("Özel ders başvuranları yüklenirken hata: $e");' "lib/Modules/Education/Tutoring/TutoringApplicationReview/tutoring_application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring application review CV hata dump'i geri gelmedi" 'print("CV yükleme hatası: $e");' "lib/Modules/Education/Tutoring/TutoringApplicationReview/tutoring_application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring application review profil hata dump'i geri gelmedi" 'print("Profil yükleme hatası: $e");' "lib/Modules/Education/Tutoring/TutoringApplicationReview/tutoring_application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring application review durum hata dump'i geri gelmedi" 'print("Durum güncelleme hatası: $e");' "lib/Modules/Education/Tutoring/TutoringApplicationReview/tutoring_application_review_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail user hata logu geri gelmedi" 'log("Error fetching user data: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail missing doc logu geri gelmedi" 'log("Tutoring document does not exist");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail fetch hata logu geri gelmedi" 'log("Error fetching tutoring detail: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail basvuru check hata logu geri gelmedi" 'log("checkBasvuru error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail toggle basvuru hata logu geri gelmedi" 'log("toggleBasvuru error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail unpublish hata logu geri gelmedi" 'log("unpublishTutoring error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail similar hata logu geri gelmedi" 'log("getSimilar error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail reviews hata logu geri gelmedi" 'log("fetchReviews error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail submit review hata logu geri gelmedi" 'log("submitReview error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail delete review hata logu geri gelmedi" 'log("deleteReview error: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My tutoring applications load hata dump'i geri gelmedi" 'print("Özel ders başvuruları yüklenirken hata: $e");' "lib/Modules/Education/Tutoring/MyTutoringApplications/my_tutoring_applications_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My tutoring applications cancel hata dump'i geri gelmedi" 'print("Özel ders başvuru iptal hatası: $e");' "lib/Modules/Education/Tutoring/MyTutoringApplications/my_tutoring_applications_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Saved tutorings hata dump'i geri gelmedi" 'print("Error loading saved tutorings: $e");' "lib/Modules/Education/Tutoring/SavedTutorings/saved_tutorings_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Location tutoring batch hata logu geri gelmedi" 'log("Error batch fetching users: $e");' "lib/Modules/Education/Tutoring/LocationBasedTutoring/location_based_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Location tutoring fetch hata logu geri gelmedi" 'log("Error fetching location-based tutoring data: $e");' "lib/Modules/Education/Tutoring/LocationBasedTutoring/location_based_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Location tutoring city hata logu geri gelmedi" 'log("Error getting city from coordinates: $e");' "lib/Modules/Education/Tutoring/LocationBasedTutoring/location_based_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring filter city secim logu geri gelmedi" 'log("SELECTED $v");' "lib/Modules/Education/Tutoring/FilterBottomSheet/tutoring_filter_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring filter load cities hata logu geri gelmedi" 'log("Error loading cities: $e");' "lib/Modules/Education/Tutoring/FilterBottomSheet/tutoring_filter_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My tutorings fetch hata logu geri gelmedi" 'log("Error fetching my tutorings: $e");' "lib/Modules/Education/Tutoring/MyTutorings/my_tutorings_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My tutorings users hata logu geri gelmedi" 'log("Error fetching users: $e");' "lib/Modules/Education/Tutoring/MyTutorings/my_tutorings_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create tutoring geocode hata logu geri gelmedi" "log('Geocoding failed: \$e');" "lib/Modules/Education/Tutoring/CreateTutoring/create_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create tutoring verification upload hata logu geri gelmedi" "log('Verification doc upload failed: \$e');" "lib/Modules/Education/Tutoring/CreateTutoring/create_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create tutoring cities hata logu geri gelmedi" 'log("Error loading cities: $e");' "lib/Modules/Education/Tutoring/CreateTutoring/create_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Create tutoring update hata logu geri gelmedi" 'log("İlan Güncellenirken Hata: $e");' "lib/Modules/Education/Tutoring/CreateTutoring/create_tutoring_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring category secim logu geri gelmedi" 'log("Kategori seçildi: ${category.name}");' "lib/Modules/Education/Tutoring/tutoring_category.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring widget missing user logu geri gelmedi" 'log("User ID not found");' "lib/Modules/Education/Tutoring/tutoring_widget_builder.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail delete hata logu geri gelmedi" 'log("Error deleting tutoring: $e");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail.dart" || failures=$((failures + 1))
check_literal_in_file "Tutoring detail widget missing user logu geri gelmedi" 'log("User ID not found");' "lib/Modules/Education/Tutoring/TutoringDetail/tutoring_detail.dart" || failures=$((failures + 1))
check_literal "Past test results preview hata dump'i geri gelmedi" 'print("Error fetching test results: $e");' || failures=$((failures + 1))
check_literal "My tests hata dump'i geri gelmedi" 'print("Error fetching tests: $e");' || failures=$((failures + 1))
check_literal "Test past result count hata dump'i geri gelmedi" 'print("Error fetching answer count: $e");' || failures=$((failures + 1))
check_literal_in_file "My booklet results fetch hata logu geri gelmedi" 'log("fetchBookletResults error: $e");' "lib/Modules/Education/AnswerKey/MyBookletResults/my_booklet_results_controller.dart" || failures=$((failures + 1))
check_literal_in_file "My booklet results optik sonuc hata logu geri gelmedi" 'log("fetchOptikSonuclari error: $error");' "lib/Modules/Education/AnswerKey/MyBookletResults/my_booklet_results_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Saved optical forms hata logu geri gelmedi" 'log("SavedOpticalFormsController.getData error: $e");' "lib/Modules/Education/AnswerKey/SavedOpticalForms/saved_optical_forms_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Optical preview baglanti debug print'i geri gelmedi" '? "İnternet bağlantısı var."' "lib/Modules/Education/AnswerKey/OpticalPreview/optical_preview_controller.dart" || failures=$((failures + 1))
check_literal "Solve test basari logunda testID dump'i geri gelmedi" 'print("Yanitlar başarıyla eklendi: $testID");' || failures=$((failures + 1))
check_literal "Past result sayim logunda snapshot uzunlugu dump'i geri gelmedi" 'print("Snapshot docs: ${filtered.length}");' || failures=$((failures + 1))
check_literal "Past result logunda timestamp dump'i geri gelmedi" 'print("Fetched timeStamp: ${timeStamp.value}");' || failures=$((failures + 1))
check_literal "Past result logunda docID dump'i geri gelmedi" 'print("Hiç veri bulunamadı: ${model.docID}");' || failures=$((failures + 1))
check_literal "Create test question ekrani image URL dump'i geri gelmedi" "print(controller.model.img)" || failures=$((failures + 1))
check_literal "Scholarship share logunda shortUrl dump'i geri gelmedi" "print('Sharing: \$shortUrl');" || failures=$((failures + 1))
check_literal "Booklet answer logunda reklam unit dump'i geri gelmedi" 'log("GOOGLE ADMOB RANDOM ID: $adUnitId");' || failures=$((failures + 1))
check_literal "Booklet answer logunda sonuc dump'i geri gelmedi" 'log("Doğru: $correct, Yanlış: $wrong, Puan: $score");' || failures=$((failures + 1))
check_literal_in_file "Booklet answer reklam fetch hata logu geri gelmedi" 'log("Reklam verisi çekme hatası: $e");' "lib/Modules/Education/AnswerKey/BookletAnswer/booklet_answer_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Booklet answer sonuc kaydetme hata logu geri gelmedi" 'log("Test sonucu kaydetme hatası: $e");' "lib/Modules/Education/AnswerKey/BookletAnswer/booklet_answer_controller.dart" || failures=$((failures + 1))
check_literal "Answer key content logunda docID ve nickname dump'i geri gelmedi" 'log("Kullanıcı verisi çekildi: ${model.docID} için nickname: ${nickname.value}",' || failures=$((failures + 1))
check_literal "Booklet preview logunda cevap anahtari listesi dump'i geri gelmedi" 'log("Çekilen cevap anahtarları: ${newList.map((e) => e.baslik).toList()}",' || failures=$((failures + 1))
check_literal_in_file "Booklet preview save state hata logu geri gelmedi" 'log("Kaydet durumu okunamadı: $e");' "lib/Modules/Education/AnswerKey/BookletPreview/booklet_preview_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Booklet preview answer key fetch hata logu geri gelmedi" 'log("Cevap anahtarlarını çekme hatası: $e");' "lib/Modules/Education/AnswerKey/BookletPreview/booklet_preview_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Booklet preview user data hata logu geri gelmedi" 'log("Kullanıcı verisi çekme hatası: $e");' "lib/Modules/Education/AnswerKey/BookletPreview/booklet_preview_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Booklet preview bookmark hata logu geri gelmedi" 'log("Yer işareti değiştirme hatası: $e");' "lib/Modules/Education/AnswerKey/BookletPreview/booklet_preview_controller.dart" || failures=$((failures + 1))
check_literal "Upload queue image logunda dosya adi dump'i geri gelmedi" "\${p.basename(imagePath)}" || failures=$((failures + 1))
check_literal "Upload queue preflight logunda path dump'i geri gelmedi" "path=\${ref.fullPath}" || failures=$((failures + 1))
check_literal "Upload queue preflight logunda uid dump'i geri gelmedi" "uid=\$userID" || failures=$((failures + 1))
check_literal "Upload queue preflight logunda post owner dump'i geri gelmedi" "postUserID=" || failures=$((failures + 1))
check_literal "Upload queue video logunda URL dump'i geri gelmedi" "MB url=\$videoUrl" || failures=$((failures + 1))
check_literal "Upload queue thumbnail logunda URL dump'i geri gelmedi" "url=\$thumbnailUrl" || failures=$((failures + 1))
check_literal "WebP preflight logunda path uid dump'i geri gelmedi" "[UploadPreflight][WebP] path=\${ref.fullPath} uid=\$uid bytes=\${data.length}" || failures=$((failures + 1))
check_literal_in_file "Post shell preflight logunda docID dump'i geri gelmedi" "docID=\$docID " "lib/Modules/PostCreator/post_creator_controller_upload_support.dart" || failures=$((failures + 1))
check_literal_in_file "Post shell preflight logunda uid dump'i geri gelmedi" "uid=\$uid " "lib/Modules/PostCreator/post_creator_controller_upload_support.dart" || failures=$((failures + 1))
check_literal_in_file "Post shell preflight logunda server user dump'i geri gelmedi" "serverUserID=\$shellUserId" "lib/Modules/PostCreator/post_creator_controller_upload_support.dart" || failures=$((failures + 1))
check_literal "Post creator image preflight logunda path uid dump'i geri gelmedi" 'path=Posts/$docID/image_$j.webp' || failures=$((failures + 1))
check_literal "Post creator image preflight logunda post owner dump'i geri gelmedi" 'postUserID=${postDoc?["userID"]}' || failures=$((failures + 1))
check_literal "Post creator video preflight logunda path dump'i geri gelmedi" 'path=${videoRef.fullPath}' || failures=$((failures + 1))
check_literal "Post creator thumbnail logunda URL dump'i geri gelmedi" "url=\$thumbnailUrl" || failures=$((failures + 1))
check_literal_in_file "Post creator image preflight exists logu geri gelmedi" "debugPrint('[UploadPreflight][PostCreator][Image] '" "lib/Modules/PostCreator/post_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post creator NSFW sample logu geri gelmedi" "debugPrint('[NSFW][PostCreator][Video][Frame] \$sample');" "lib/Modules/PostCreator/post_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post creator quote relation debug logu geri gelmedi" "debugPrint('[QuotePublish/direct] reshare relation persisted');" "lib/Modules/PostCreator/post_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post creator quote relation alt debug logu geri gelmedi" "debugPrint('[QuotePublish/direct-alt] reshare relation persisted');" "lib/Modules/PostCreator/post_creator_controller.dart" || failures=$((failures + 1))
check_literal_in_file "Post creator post shell server debug logu geri gelmedi" "debugPrint('[UploadPreflight][PostShell] '" "lib/Modules/PostCreator/post_creator_controller_upload_support.dart" || failures=$((failures + 1))
check_literal "Quote publish direct logunda docID dump'i geri gelmedi" '[QuotePublish/direct] docID=$docID quoted=$_isQuotedPost original=$_sharedOriginalPostID source=$_sharedSourcePostID user=$currentUserId' || failures=$((failures + 1))
check_literal "Quote publish direct-alt logunda docID dump'i geri gelmedi" '[QuotePublish/direct-alt] docID=$docID quoted=$_isQuotedPost original=$_sharedOriginalPostID source=$_sharedSourcePostID user=$currentUserId' || failures=$((failures + 1))
check_literal "Post like search logunda query dump'i geri gelmedi" 'query=\"$normalized\"' || failures=$((failures + 1))
check_literal "Post like search logunda term dump'i geri gelmedi" 'term=\"$term\"' || failures=$((failures + 1))
check_literal "Tag posts logunda tag dump'i geri gelmedi" 'print(">>> Tag post araması başlıyor! [TAG: $tag]")' || failures=$((failures + 1))
check_literal "Tag posts logunda sonuc dump'i geri gelmedi" 'print(">>> Tag sonuç: ${fetchedPosts.length}")' || failures=$((failures + 1))
check_literal_in_file "Agenda ilk video trigger logunda docID dump'i geri gelmedi" "print('🎬 İlk video manuel trigger: \${firstPost.docID}');" "lib/Modules/Agenda/agenda_controller.dart" || failures=$((failures + 1))
check_literal "Deleted stories controller logunda uid dump'i geri gelmedi" 'DeletedStoriesController.fetch: uid=$uid' || failures=$((failures + 1))
check_literal "Deleted stories repository logunda uid dump'i geri gelmedi" 'Deleted stories fetch: uid=$uid' || failures=$((failures + 1))
check_literal "Mandatory follow logunda uid dump'i geri gelmedi" '[MandatoryFollow] follow failed uid=$uid' || failures=$((failures + 1))
check_literal "Reshare helper post owner dump'i geri gelmedi" "print('  postUserID: \$postUserID');" || failures=$((failures + 1))
check_literal "Reshare helper original owner dump'i geri gelmedi" "print('  existingOriginalUserID: \$existingOriginalUserID');" || failures=$((failures + 1))
check_literal "Reshare helper original post dump'i geri gelmedi" "print('  existingOriginalPostID: \$existingOriginalPostID');" || failures=$((failures + 1))
check_literal "Reshare helper current post dump'i geri gelmedi" "print('  currentPostID: \$currentPostID');" || failures=$((failures + 1))
check_literal "Reshare helper current user dump'i geri gelmedi" "print('  currentUserID: \$currentUserID');" || failures=$((failures + 1))
check_literal "User profile sync logunda userId dump'i geri gelmedi" '[User Profile Sync] Started for user: ${userId}' || failures=$((failures + 1))
check_literal "User profile sync missing snapshot logunda userId dump'i geri gelmedi" '[User Profile Sync] Missing before/after snapshot for user: ${userId}' || failures=$((failures + 1))
check_literal "User profile sync skip logunda userId dump'i geri gelmedi" '[User Profile Sync] No displayable fields changed. Skipping sync for user: ${userId}' || failures=$((failures + 1))
check_literal "User profile sync no posts logunda userId dump'i geri gelmedi" '[User Profile Sync] No posts found for user: ${userId}' || failures=$((failures + 1))
check_literal "User profile sync no posts responseunda userId dump'i geri gelmedi" 'No posts found for user: ${userId}' || failures=$((failures + 1))
check_literal "User profile sync fail logunda userId dump'i geri gelmedi" '[User Profile Sync] Failed for user: ${userId}' || failures=$((failures + 1))
check_literal "Manual sync fail logunda userId dump'i geri gelmedi" '[Manual Sync] Failed for user: ${userId}' || failures=$((failures + 1))
check_literal "Hybrid feed create logunda postId dump'i geri gelmedi" '[HybridFeed] Fan-out complete: ${postId}' || failures=$((failures + 1))
check_literal "Hybrid feed delete logunda postId dump'i geri gelmedi" '[HybridFeed] Post ${postId} feed items cleaned up' || failures=$((failures + 1))
check_literal "Hybrid feed follower logunda followerId dump'i geri gelmedi" '[HybridFeed] Backfilled ${postsSnap.size} posts for new follower ${followerId}' || failures=$((failures + 1))
check_literal "HLS processing logunda target id dump'i geri gelmedi" '[HLS] Processing video for ${target.type}: ${target.id}' || failures=$((failures + 1))
check_literal "HLS complete logunda URL dump'i geri gelmedi" '[HLS] Complete for ${target.type}:${target.id}. HLS URL: ${hlsUrl}' || failures=$((failures + 1))
check_literal "HLS story delete logunda path dump'i geri gelmedi" '[HLS] Story source deleted: ${filePath}' || failures=$((failures + 1))
check_literal "HLS error logunda target id dump'i geri gelmedi" '[HLS] Error processing ${target.type}:${target.id}:' || failures=$((failures + 1))
check_literal "Tutoring notification logunda tutor/doc dump'i geri gelmedi" '[TutoringNotif] Application notification sent to ${tutorUID} for ${docId}' || failures=$((failures + 1))
check_literal "Tutoring notification status logunda applicant dump'i geri gelmedi" '[TutoringNotif] Status update notification sent to ${applicantId}: ${newStatus}' || failures=$((failures + 1))
check_literal "Thumbnail skip logunda filePath dump'i geri gelmedi" 'Already a thumbnail, skipping:' || failures=$((failures + 1))
check_literal "Thumbnail avatar skip logunda filePath dump'i geri gelmedi" 'Profile avatar source file, skipping thumbnail generation:' || failures=$((failures + 1))
check_literal "Thumbnail non-image logunda filePath dump'i geri gelmedi" 'Not an image file, skipping:' || failures=$((failures + 1))
check_literal "Thumbnail temp download logunda path dump'i geri gelmedi" 'Downloaded to temp:' || failures=$((failures + 1))
check_literal "Thumbnail small image logunda filePath dump'i geri gelmedi" 'Image is already <= 600px, skipping thumbnail generation:' || failures=$((failures + 1))
check_literal "Thumbnail generation logunda temp path dump'i geri gelmedi" 'Generated ${width}px thumbnail:' || failures=$((failures + 1))
check_literal "Thumbnail upload logunda storage path dump'i geri gelmedi" 'Uploaded thumbnail to:' || failures=$((failures + 1))
check_literal "Thumbnail cleanup logunda temp path dump'i geri gelmedi" 'Cleaned up temp file:' || failures=$((failures + 1))
check_literal "Thumbnail complete logunda filePath dump'i geri gelmedi" '✅ Thumbnail generation complete for: ${filePath}' || failures=$((failures + 1))
check_literal "Shared post cascade logunda source post id dump'i geri gelmedi" '[cascadeDeleteSharedPosts] source=${postId}' || failures=$((failures + 1))
check_literal "Backfill posts logunda doc id dump'i geri gelmedi" "console.error('backfillPostsOriginalFields: error on', doc.id, e);" || failures=$((failures + 1))
check_literal "countDocuments logunda collection path dump'i geri gelmedi" 'console.error("countDocuments error", collection.path, err);' || failures=$((failures + 1))
check_literal "purge post logunda docPath dump'i geri gelmedi" 'console.error("purgePostSubcollections error", docPath, error);' || failures=$((failures + 1))
check_literal "purge student logunda docPath dump'i geri gelmedi" "console.error('purgeStudentSubcollections error', docPath, name, err);" || failures=$((failures + 1))
check_literal "purge student fatal logunda docPath dump'i geri gelmedi" "console.error('purgeStudentSubcollections fatal error', docPath, err);" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda email dump'i geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "emailLower," "functions/src/11_resend.ts" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda uid dump'i geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "uid," "functions/src/11_resend.ts" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda sağlayici body dump'i geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "netgsmBody," "functions/src/11_resend.ts" || failures=$((failures + 1))
check_context_literal_in_file "Signup SMS logunda phone dump'i geri gelmedi" 'console.error("sendSignupSmsCode netgsm-error", {' "phone," "functions/src/11_resend.ts" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda email dump'i lib tarafinda geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "emailLower," "functions/lib/11_resend.js" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda uid dump'i lib tarafinda geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "uid," "functions/lib/11_resend.js" || failures=$((failures + 1))
check_context_literal_in_file "Password reset SMS logunda sağlayici body dump'i lib tarafinda geri gelmedi" 'console.error("sendPasswordResetSmsCode netgsm-error", {' "netgsmBody," "functions/lib/11_resend.js" || failures=$((failures + 1))
check_context_literal_in_file "Signup SMS logunda phone dump'i lib tarafinda geri gelmedi" 'console.error("sendSignupSmsCode netgsm-error", {' "phone," "functions/lib/11_resend.js" || failures=$((failures + 1))

if [[ "$failures" -gt 0 ]]; then
  echo
  echo "Security regression scan failed with $failures finding(s)."
  exit 1
fi

echo
echo "Security regression scan passed."
