part of 'tutoring_controller.dart';

extension TutoringModelExtension on TutoringModel {
  TutoringModel copyWith({
    String? docID,
    String? aciklama,
    String? baslik,
    String? brans,
    String? cinsiyet,
    List<String>? dersYeri,
    num? end,
    List<String>? favorites,
    num? fiyat,
    List<String>? imgs,
    String? ilce,
    bool? onayVerildi,
    String? sehir,
    bool? telefon,
    num? timeStamp,
    String? userID,
    bool? whatsapp,
    bool? ended,
    num? endedAt,
    num? viewCount,
    num? applicationCount,
    num? averageRating,
    num? reviewCount,
    Map<String, List<String>>? availability,
    double? lat,
    double? long,
    bool? verified,
    List<String>? verificationDocs,
    String? avatarUrl,
    String? displayName,
    String? nickname,
    String? shortId,
    String? shortUrl,
    String? rozet,
  }) {
    return TutoringModel(
      docID: docID ?? this.docID,
      aciklama: aciklama ?? this.aciklama,
      baslik: baslik ?? this.baslik,
      brans: brans ?? this.brans,
      cinsiyet: cinsiyet ?? this.cinsiyet,
      dersYeri: dersYeri ?? this.dersYeri,
      end: end ?? this.end,
      favorites: favorites ?? this.favorites,
      fiyat: fiyat ?? this.fiyat,
      imgs: imgs ?? this.imgs,
      ilce: ilce ?? this.ilce,
      onayVerildi: onayVerildi ?? this.onayVerildi,
      sehir: sehir ?? this.sehir,
      telefon: telefon ?? this.telefon,
      timeStamp: timeStamp ?? this.timeStamp,
      userID: userID ?? this.userID,
      whatsapp: whatsapp ?? this.whatsapp,
      ended: ended ?? this.ended,
      endedAt: endedAt ?? this.endedAt,
      viewCount: viewCount ?? this.viewCount,
      applicationCount: applicationCount ?? this.applicationCount,
      averageRating: averageRating ?? this.averageRating,
      reviewCount: reviewCount ?? this.reviewCount,
      availability: availability ?? this.availability,
      lat: lat ?? this.lat,
      long: long ?? this.long,
      verified: verified ?? this.verified,
      verificationDocs: verificationDocs ?? this.verificationDocs,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      displayName: displayName ?? this.displayName,
      nickname: nickname ?? this.nickname,
      shortId: shortId ?? this.shortId,
      shortUrl: shortUrl ?? this.shortUrl,
      rozet: rozet ?? this.rozet,
    );
  }
}
