part of 'antreman_controller.dart';

const Map<String, Map<String, List<String>>> _antremanSubjects =
    <String, Map<String, List<String>>>{
  'LGS': <String, List<String>>{
    'LGS': <String>[
      'Türkçe',
      'Matematik',
      'Fen Bilimleri',
      'İnkilap Tarihi',
      'Din Kültürü',
      'Yabancı Dil',
    ],
  },
  'YKS': <String, List<String>>{
    'TYT': <String>[
      'Türkçe',
      'Temel Matematik',
      'Fen Bilimleri',
      'Sosyal Bilimler',
    ],
    'AYT': <String>[
      'Edebiyat - Sosyal Bilimler 1',
      'Matematik',
      'Sosyal Bilimler 2',
      'Fen Bilimleri',
    ],
    'YDT': <String>['İngilizce', 'Almanca', 'Arapça', 'Fransızca', 'Rusça'],
  },
  'KPSS': <String, List<String>>{
    'Orta Öğretim': <String>['Genel Kültür', 'Genel Yetenek'],
    'Ön Lisans': <String>['Genel Kültür', 'Genel Yetenek'],
    'Lisans': <String>[
      'Genel Kültür',
      'Genel Yetenek',
      'Eğitim Bilimleri',
      'Çalışma Ekonomisi',
      'İstatistik',
      'Uluslararası İlişkiler',
      'Kamu Yönetimi',
      'Hukuk',
      'İktisat',
      'İşletme',
      'Maliye',
      'Muhasebe',
      'Almanca Öğretmenliği',
      'Beden Eğitimi',
      'Biyoloji Öğretmenliği',
      'Coğrafya Öğretmenliği',
      'Din Kültürü',
      'Edebiyat Öğretmenliği',
      'Fen Bilimleri Öğretmenliği',
      'Fizik Öğretmenliği',
      'Matematik Öğretmenliği',
      'İmam Hatip Öğretmenliği',
      'İngilizce Öğretmenliği',
      'Kimya Öğretmenliği',
      'Lise Matematik Öğretmenliği',
      'Okul Öncesi Öğretmenliği',
      'Rehberlik',
      'Sınıf Öğretmenliği',
      'Sosyal Bilgiler Öğretmenliği',
      'Tarih Öğretmenliği',
      'Türkçe Öğretmenliği',
      'Eğitim Bilimleri',
    ],
  },
  'YDS': <String, List<String>>{
    'İngilizce': <String>['Test Of English'],
    'Almanca': <String>['DeutschTest'],
    'Fransızca': <String>['Test De Français'],
    'Rusça': <String>['ТЕСТ НА ЗНАНИЕ РУССКОГО ЯЗЫКА'],
    'Arapça': <String>['Arapça'],
  },
  'ALES': <String, List<String>>{
    'ALES': <String>[
      'Sözel',
      'Sayısal',
      'Sözel 1',
      'Sözel 2',
      'Sayısal 1',
      'Sayısal 2',
    ],
  },
  'DGS': <String, List<String>>{
    'DGS': <String>['Sayısal', 'Sözel'],
  },
  'DUS': <String, List<String>>{
    'DUS': <String>['Temel Bilimler', 'Klinik Bilimler'],
  },
  'TUS': <String, List<String>>{
    'TTBT': <String>['Temel Tıp Bilimleri'],
    'KTBT': <String>['Klinik Tıp Bilimleri'],
  },
};

const Map<String, IconData> _antremanIcons = <String, IconData>{
  'LGS': CupertinoIcons.lightbulb,
  'YKS': CupertinoIcons.book_fill,
  'TYT': CupertinoIcons.book_fill,
  'AYT': CupertinoIcons.doc_text,
  'YDT': CupertinoIcons.flag,
  'ALES': CupertinoIcons.graph_square_fill,
  'DGS': CupertinoIcons.archivebox,
  'YDS': CupertinoIcons.pen,
  'TUS': CupertinoIcons.pencil,
  'DUS': CupertinoIcons.doc_on_clipboard,
  'KPSS Ortaöğretim': CupertinoIcons.person_3_fill,
  'KPSS Ön Lisans': CupertinoIcons.list_bullet,
  'KPSS GY-GK': CupertinoIcons.info_circle_fill,
  'KPSS Eğitim Bilimleri': CupertinoIcons.book,
  'KPSS Alan Bilgisi': CupertinoIcons.briefcase_fill,
  'KPSS A Grubu 1': CupertinoIcons.lock_fill,
  'KPSS A Grubu 2': CupertinoIcons.wrench_fill,
};
